import {describe,it,expect} from 'vitest';
import {Transform} from '@forgeax/engine/scene';
import {createBoxGeometry} from '@forgeax/engine/geometry';
import {setup} from './equipment-fixture.ts';
import {createSkills} from '../native-skills.ts';
import {createNativeArena} from '../native-arena.ts';
import {createVehicles} from '../native-vehicles.ts';
import {vehicleDefs} from '../../original/vehicle-rules.ts';
import {classArmor,weaponClassSpeed,empCarve,skillPlacement} from '../class-skill-rules.ts';
import {createBuilding} from '../native-building.ts';
import {fireGun} from '../native-gunfire.ts';
import type {ModeId} from '../catalog.ts';
const kit={primary:'ar',secondary:'usp',gadget1:'medkit',gadget2:'ammo',grenade:'frag',melee:'knife'};
async function fixture(mode:ModeId='tdm',id='medic'){
 const s=await setup({...kit,primary:mode==='conquest'?'ak74':'ar'},mode),{b,physics,world}=s;b.classId=id;Object.assign(b,{stealthUntil:0,shieldUntil:0,shieldHealth:0,bonusShot:0,spawnProtection:0,interacting:false});
 const host:any={assets:{loadByGuid:async()=>({ok:true,value:createBoxGeometry(.5,1.8,.5).unwrap()})}};
 const callbacks={notice:(text:string)=>{b.notice=text;},respawn:()=>{b.health=100;b.armor=classArmor(mode,id);b.dead=false;b.downed=false;b.skills?.spawnLife();},leave:()=>{},setWeapon:()=>{}};
 const bridge=new Proxy(b,{get:(o,k)=>k in callbacks?(callbacks as any)[k]:o[k]});
 const arena=await createNativeArena(world,host,mode,{seed:44,bases:[{x:12,y:1.04,z:12},{x:50,y:1.04,z:50}]},bridge,physics,()=>false);b.arena=arena;arena.match.phase='battle';for(const u of arena.units){u.alive=false;u.respawn=1e6;}const friend=arena.units.find(u=>u.team==='ally')!,enemy=arena.units.find(u=>u.team==='enemy')!;
 for(const [u,p] of [[friend,[32,1.94,30]],[enemy,[30,1.94,18]]] as const){u.alive=true;u.hp=100;u.protection=0;u.think=1e6;u.cooldown=1e6;u.path=[];physics.teleport(u.entity,p as [number,number,number]);}
 physics.teleport(b.playerBody,[30,1.94,30]);world.set(b.camera,Transform,{pos:[30,2.84,30]}).unwrap();b.health=50;b.armor=0;
 const skills=createSkills(world,b);b.skills=skills;s.advance(.1);
 const step=(seconds:number,arenaUpdate=false)=>{for(let i=0;i<Math.ceil(seconds*60);i++){s.advance(1/60);b.skillCooldown=Math.max(0,b.skillCooldown-1/60);if(arenaUpdate)arena.update(1/60);skills.update(1/60);}};
 return {...s,b,arena,host,friend,enemy,skills,step,dispose(){skills.dispose();b.vehicles?.dispose();arena.dispose();s.dispose();}};
}
describe('EQ-06 class gameplay on the native arena and Rapier',()=>{
 it('conquest stimulant heals over one second, refuses full health, retains grenade inventory and resets per life',async()=>{const s=await fixture('conquest','assault');try{const {b,skills}=s;expect(skills.activate()).toBe(true);expect(b.health).toBe(50);skills.update(.25);expect(b.health).toBe(75);skills.update(.75);expect(b.health).toBe(100);expect(b.skillCooldown).toBe(60);expect(b.grenades).toBe(2);skills.spawnLife();expect(skills.activate()).toBe(false);expect(b.skillCooldown).toBe(0);expect(weaponClassSpeed('conquest','assault')).toBe(1.15);expect(weaponClassSpeed('core','vanguard')).toBe(1.15);expect(weaponClassSpeed('conquest','support')).toBe(1);}finally{s.dispose();}});
 it('support holds X for 3 seconds to revive a real downed ally, cancels on release and does not spend a ticket',async()=>{const s=await fixture('conquest','support');try{const {b,arena,skills,friend,enemy}=s;skills.spawnLife();expect(b.armor).toBe(100);arena.damage(friend,200,enemy,'ar');expect(friend.downed).toBe(true);expect(arena.match.score.ally).toBe(1000);b.keys.add('KeyX');skills.activate();skills.update(2);expect(friend.alive).toBe(false);skills.release();expect(skills.snapshot().progress).toBe(0);skills.activate();skills.update(2.99);expect(friend.alive).toBe(false);skills.update(.02);expect(friend.hp).toBe(50);expect(friend.alive).toBe(true);expect(friend.protection).toBe(1.5);expect(arena.downed).toHaveLength(0);expect(arena.match.score.ally).toBe(1000);expect(skills.snapshot().tally.revives).toBe(1);}finally{s.dispose();}});
 it('revive range and target changes reset progress; bleed-out settles death and tickets exactly once',async()=>{const s=await fixture('conquest','support');try{const {b,arena,skills,friend,enemy}=s;arena.damage(friend,200,enemy,'ar');b.keys.add('KeyX');skills.activate();skills.update(1);b.physics.teleport(b.playerBody,[40,1.94,30]);skills.update(1);expect(skills.snapshot().progress).toBe(0);expect(friend.alive).toBe(false);arena.update(28.1);expect(arena.downed).toHaveLength(0);expect(arena.match.score.ally).toBe(999);arena.update(.1);expect(arena.match.score.ally).toBe(999);}finally{s.dispose();}});
 it('engineer repairs a real friendly vehicle at 10 HP/s, cannot repair outside 5m and has no instant T repair skill',async()=>{const s=await fixture('conquest','engineer');try{const {b,skills,world,host}=s;b.vehicles=await createVehicles(world,host,b,()=>false);const v=b.vehicles.vehicles.find((v:any)=>v.team==='ally')!,max=vehicleDefs[v.type as keyof typeof vehicleDefs].maxHp;b.physics.teleport(v.entity,[30,1+vehicleDefs[v.type as keyof typeof vehicleDefs].size.y/2,28]);v.hp=max-100;b.keys.add('KeyX');skills.activate();skills.update(1);expect(v.hp).toBe(max-90);skills.release();skills.update(1);expect(v.hp).toBe(max-90);b.physics.teleport(b.playerBody,[50,1.94,30]);skills.activate();skills.update(1);expect(v.hp).toBe(max-90);skills.spawnLife();expect(b.buildBlocks).toBe(20);}finally{s.dispose();}});
 it('medic preview spends nothing until release; heals only health, friendly targets and the original 5.5m area',async()=>{const s=await fixture('tdm','medic');try{const {b,skills,friend,enemy}=s;b.pitch=-.9;expect(skills.activate()).toBe(true);expect(b.skillCooldown).toBe(0);expect(skills.snapshot().healers).toHaveLength(0);skills.cancel();skills.release();expect(skills.snapshot().healers).toHaveLength(0);skills.activate();skills.release();const p=skills.snapshot().healers[0].position;b.physics.teleport(b.playerBody,[p[0],p[1]+.9,p[2]]);b.physics.teleport(friend.entity,[p[0]+5,p[1]+.9,p[2]]);b.physics.teleport(enemy.entity,[p[0]+1,p[1]+.9,p[2]]);friend.hp=20;enemy.hp=20;b.health=20;b.armor=25;skills.update(1);expect(b.health).toBe(34);expect(b.armor).toBe(25);expect(friend.hp).toBe(34);expect(enemy.hp).toBe(20);b.physics.teleport(b.playerBody,[p[0]+6,p[1]+.9,p[2]]);skills.update(1);expect(b.health).toBe(34);skills.update(6);expect(skills.snapshot().healers).toHaveLength(0);skills.spawnLife();expect(b.armor).toBe(100);}finally{s.dispose();}});
 it('ghost is immune to hostile damage during 6 seconds; breaking stealth on fire grants one successful infantry hit',async()=>{const s=await fixture('tdm','ghost');try{const {b,skills,arena,enemy}=s;enemy.hp=1000;enemy.yaw=0;b.weapon={...b.weapon,spread:0,adsSpread:0,damage:20};b.armor=0;b.health=100;skills.activate();expect(b.bonusShot).toBe(0);arena.damage(arena.player,30,enemy,'ar');expect(b.health).toBe(100);b.firing=true;b.yaw=Math.PI/2;fireGun(b,()=>.5);expect(b.stealthUntil).toBe(0);expect(b.bonusShot).toBe(40);b.cooldown=0;b.firing=true;b.yaw=0;fireGun(b,()=>.5);expect(b.bonusShot).toBe(0);expect(skills.snapshot().tally.ambushHits).toBe(1);expect(skills.snapshot().tally.rearHits).toBe(1);expect(enemy.hp).toBeCloseTo(1000-66*1.6);b.skillCooldown=0;skills.activate();b.elapsed+=6;skills.update(.01);expect(b.bonusShot).toBe(40);b.dead=true;skills.update(.01);expect(b.bonusShot).toBe(0);expect(b.skillCooldown).toBe(0);}finally{s.dispose();}});
 it('shotgun ghost bonus is consumed by one pellet, not repeated across all pellets',async()=>{const s=await fixture('tdm','ghost');try{const {b,skills,enemy}=s;b.weapon={...b.weapon,pellets:8,spread:0,adsSpread:0,damage:10};b.weaponId='sg';b.ammoState.sg={mag:8,reserve:24};enemy.hp=2000;skills.activate();b.firing=true;fireGun(b,()=>.5);expect(skills.snapshot().tally.ambushHits).toBe(1);expect(b.lastGunshot.rays).toHaveLength(8);}finally{s.dispose();}});
 it('shield uses normalized frontal dot .2, 280 HP and 6 percent reduction; overflow still damages the player',async()=>{const s=await fixture('tdm','juggernaut');try{const {b,skills,arena,enemy}=s;b.health=100;b.armor=0;skills.activate();arena.damage(arena.player,100,enemy,'ar');expect(b.health).toBe(100);expect(b.shieldHealth).toBeCloseTo(186);b.physics.teleport(enemy.entity,[40,1.94,29]);arena.damage(arena.player,10,enemy,'ar');expect(b.health).toBeCloseTo(90.6);expect(b.shieldHealth).toBeCloseTo(186);b.physics.teleport(enemy.entity,[30,1.94,20]);arena.damage(arena.player,210,enemy,'ar');expect(b.shieldUntil).toBe(0);expect(b.health).toBeCloseTo(79.2);expect(skills.snapshot().tally.shieldAbsorbed).toBe(280);}finally{s.dispose();}});
 it('shield uses the actual explosion position rather than the owner position',async()=>{const s=await fixture('tdm','juggernaut');try{const {b,skills,arena}=s;b.health=100;b.armor=0;skills.activate();arena.damage(arena.player,50,arena.player,'frag',false,[30,2,34]);expect(b.health).toBe(53);expect(b.shieldHealth).toBe(280);arena.damage(arena.player,50,arena.player,'frag',false,[30,2,26]);expect(b.health).toBe(53);expect(b.shieldHealth).toBe(233);}finally{s.dispose();}});
 it('engineer turret costs 12, deals 9 at one second intervals, prioritizes nearest visible foe, refunds 8 and has at most 8s recall cooldown',async()=>{const s=await fixture('tdm','engineer');try{const {b,skills,enemy,friend}=s;b.buildBlocks=20;b.pitch=-.4;skills.activate();expect(b.buildBlocks).toBe(20);skills.release();expect(b.buildBlocks).toBe(8);expect(b.deployables).toHaveLength(1);skills.update(.34);expect(enemy.hp).toBe(100);skills.update(.02);expect(enemy.hp).toBe(91);skills.update(.5);expect(enemy.hp).toBe(91);skills.update(.5);expect(enemy.hp).toBe(82);expect(friend.hp).toBe(100);skills.activate();expect(b.buildBlocks).toBe(16);expect(b.skillCooldown).toBe(8);expect(b.deployables).toHaveLength(0);}finally{s.dispose();}});
 it('turret kills are credited to its owning player, matching the original damageEnemy path',async()=>{const s=await fixture('tdm','engineer');try{const {b,skills,enemy,arena}=s;b.buildBlocks=20;b.pitch=-.4;enemy.hp=9;skills.activate();skills.release();skills.update(.4);expect(enemy.alive).toBe(false);expect(arena.match.playerStats().kills).toBe(1);}finally{s.dispose();}});
 it('turret respects walls, 38m range, bullet damage/destruction and ammunition exhaustion without leaked physics bodies',async()=>{const s=await fixture('tdm','engineer');try{const {b,skills,arena,enemy}=s;b.buildBlocks=20;b.pitch=-.4;skills.activate();skills.release();const t=b.deployables[0],p=t.position;for(let x=25;x<36;x++)for(let y=1;y<6;y++)b.map.set(x,y,22,4);skills.update(1);expect(enemy.hp).toBe(100);for(let x=25;x<36;x++)for(let y=1;y<6;y++)b.map.set(x,y,22,0);b.physics.teleport(enemy.entity,[p[0],p[1]+.9,p[2]-39]);skills.update(1);expect(enemy.hp).toBe(100);b.physics.teleport(enemy.entity,[p[0],p[1]+.9,p[2]-10]);t.ammo=1;skills.update(1);expect(enemy.hp).toBe(91);expect(b.deployables).toHaveLength(0);b.skillCooldown=0;b.buildBlocks=20;skills.activate();skills.release();arena.damage(b.deployables[0],120,enemy,'ar');expect(b.deployables).toHaveLength(0);}finally{s.dispose();}});
 it('EMP has a 480-block budget, protects friendly base and terrain; no damage is applied to troops, vehicles or cores',async()=>{const s=await fixture('core','raider');try{const {b,skills,arena,enemy}=s;b.physics.teleport(b.playerBody,[40,2,48]);s.world.set(b.camera,Transform,{pos:[40,3,48]}).unwrap();b.yaw=0;b.pitch=0;b.map.hits[6]=5;for(let x=34;x<47;x++)for(let z=25;z<40;z++)for(let y=1;y<15;y++)b.map.set(x,y,z,6);const score=arena.match.score.enemy;skills.activate();expect(b.broken).toBeGreaterThan(0);expect(b.broken).toBeLessThanOrEqual(480);expect(enemy.hp).toBe(100);expect(arena.match.score.enemy).toBe(score);expect(b.map.get(40,0,35)).toBe(1);expect(arena.drops.some(d=>d.ammo===9)).toBe(true);const r=empCarve(b.map,[40,3,48],[0,0,-1],[40,0,35]);expect(r.broken).toBe(0);}finally{s.dispose();}});
 it('raider gets 39 rounds on core-mode hostile kill; arena modes do not add kill loot',async()=>{for(const mode of ['core','tdm'] as const){const s=await fixture(mode,'raider');try{s.arena.damage(s.enemy,150,s.arena.player,'ar');expect(s.arena.drops.filter(d=>d.ammo).map(d=>d.ammo)).toEqual(mode==='core'?[39]:[]);}finally{s.dispose();}}});
 it('engineer-built cover requires two hits; ordinary cover requires one',async()=>{for(const id of ['engineer','vanguard']){const s=await fixture('core',id);try{const {b}=s;b.pitch=-.7;b.buildBlocks=20;const building=createBuilding(b);building.select('cover');building.place();const indices=[...b.map.durability.keys()];expect(indices.length).toBe(24);const index=indices[0],x=index%b.map.width,y=Math.floor(index/(b.map.width*b.map.width)),z=Math.floor(index/b.map.width)%b.map.width;expect(b.map.breakBlock(x,y,z)).toBe(id!=='engineer');if(id==='engineer')expect(b.map.breakBlock(x,y,z)).toBe(true);}finally{s.dispose();}}});
 it('Q marks real enemies for 5s on recon and 1s on assault, and refuses obstructed targets',async()=>{for(const id of ['recon','assault']){const s=await fixture('conquest',id);try{expect(s.skills.mark()).toBe(true);expect(s.skills.marks[0].life).toBe(id==='recon'?5:1);s.skills.update(id==='recon'?5:1);expect(s.skills.marks).toHaveLength(0);s.b.elapsed+=1;for(let y=1;y<5;y++)s.b.map.set(30,y,24,7);expect(s.skills.mark()).toBe(false);}finally{s.dispose();}}});
 it('V dash covers 30m through Rapier and is stopped by solid walls; cooldown prevents repeat',async()=>{for(const wall of [false,true]){const s=await fixture('tdm','vanguard');try{const {b,skills}=s;b.physics.teleport(b.playerBody,[30,1.94,45]);s.enemy.alive=false;b.physics.teleport(s.enemy.entity,[5,1.94,5]);if(wall)for(let x=25;x<36;x++)for(let y=1;y<10;y++)b.map.set(x,y,35,7);s.advance(.3);expect(skills.dash()).toBe(true);s.step(.3);const p=b.physics.position(b.playerBody);if(wall){expect(p[2]).toBeGreaterThan(35);expect(skills.snapshot().dashTravel).toBeLessThan(10);}else{expect(skills.snapshot().dashTravel).toBeCloseTo(30,0);expect(p[2]).toBeCloseTo(15,0);}expect(skills.dash()).toBe(false);}finally{s.dispose();}}});
 it('dash cannot carry a player beyond the world boundary',async()=>{const s=await fixture('tdm','ghost');try{s.b.physics.teleport(s.b.playerBody,[2,1.94,30]);s.advance(.2);s.b.yaw=Math.PI/2;expect(s.skills.dash()).toBe(true);s.step(.3);expect(s.b.physics.position(s.b.playerBody)[0]).toBeGreaterThanOrEqual(1);}finally{s.dispose();}});
 it('cancel, death and respawn clean only skill entities, preserving the independent equipment owner',async()=>{const s=await fixture('tdm','engineer');try{const {b,skills}=s;b.buildBlocks=20;b.pitch=-.7;skills.activate();skills.cancel();skills.release();expect(b.buildBlocks).toBe(20);expect(b.deployables).toHaveLength(0);skills.activate();skills.release();const other={id:'crate-owner',alive:true};b.deployables.push(other);b.dead=true;skills.update(.1);expect(b.deployables).toEqual([other]);expect(b.skillCooldown).toBe(0);b.dead=false;skills.spawnLife();expect(b.buildBlocks).toBe(20);expect(skills.snapshot().pending).toBe(false);}finally{s.dispose();}});
});
