import {describe,it,expect,vi} from 'vitest';
import {Transform} from '@forgeax/engine/scene';
import {setup} from './equipment-fixture.ts';
import {arenaFixture} from './gunfire-fixture.ts';
import {createVehicles} from '../native-vehicles.ts';
import {RPG_RULES,rpgInfantryDamage} from '../launcher-rules.ts';
const kit={primary:'ak74',secondary:'usp',gadget1:'rpg',gadget2:'ammo',grenade:'frag',melee:'knife'};
describe('EQ-04 native RPG flight and original damage semantics',()=>{
 it('retains original anti-armor and infantry splash values',()=>{expect(RPG_RULES).toMatchObject({projectileSpeed:38,gravity:1.5,projectileLife:7,damage:150,blastRadius:3.2,breakRadius:1.45});expect(rpgInfantryDamage(0)).toBe(60);expect(rpgInfantryDamage(1.6)).toBe(30);expect(rpgInfantryDamage(3.2)).toBe(12);expect(rpgInfantryDamage(3.21)).toBe(0);});
 it('flies through Rapier at the original speed and falls under native gravity, then expires without exploding',async()=>{const s=await setup(kit);try{const {b,gear,world}=s;b.arena.units=[];b.ordnance={burst:vi.fn()};world.set(b.camera,Transform,{pos:[30,20,30]}).unwrap();gear.select('gadget1');s.advance(.2);gear.press();const part=gear.projectile.parts[0],start=[...part.previous];expect(b.mag).toBe(0);s.advance(.8);const p=b.physics.position(part.entity);expect(start[2]-p[2]).toBeCloseTo(38*part.age,0);expect(start[1]-p[1]).toBeCloseTo(.75*part.age**2,1);expect(p[0]).toBeCloseTo(30,4);s.advance(7);expect(gear.projectile.parts).toHaveLength(0);expect(gear.projectile.lastRocket?.phase).toBe('expired');expect(b.ordnance.burst).not.toHaveBeenCalled();}finally{s.dispose();}});
 it('hits an infantry target only after flight and uses splash instead of a 150-point hitscan',async()=>{const s=await arenaFixture('conquest');try{const {b,gear,target}=s;b.ordnance={burst:vi.fn()};gear.select('gadget1');s.advance(.2);gear.press();expect(target.hp).toBe(1000);s.advance(.5);expect(target.hp).toBeLessThan(1000);expect(target.hp).toBeGreaterThanOrEqual(940);expect(gear.projectile.lastRocket?.hit).toBe('unit');expect(b.ordnance.burst).toHaveBeenCalledTimes(1);expect(b.health).toBe(50);}finally{s.dispose();}});
 it('directly hits a rotated vehicle for 150 once, without damaging a nearby unhit vehicle',async()=>{const s=await arenaFixture('conquest');try{const {b,gear,physics}=s;for(const u of s.arena.units)u.alive=false;b.vehicles=await createVehicles(s.world,s.host,b,()=>false);const vehicles=b.vehicles.vehicles.filter((v:any)=>v.team==='enemy'),[hit,near]=vehicles;for(const v of b.vehicles.vehicles)v.hp=0;hit.hp=360;near.hp=600;hit.yaw=Math.PI/2;physics.teleport(hit.entity,[30,2.1,23]);physics.teleport(near.entity,[34,2.1,23]);gear.select('gadget1');s.advance(.2);gear.press();expect(hit.hp).toBe(360);s.advance(.5);expect(hit.hp).toBe(210);expect(near.hp).toBe(600);expect(gear.projectile.lastRocket?.hit).toBe('vehicle');s.advance(1);expect(hit.hp).toBe(210);}finally{s.dispose();}});
 it('sweeps a thin wall before a target and restores the authored voxel blast radius',async()=>{const s=await arenaFixture('conquest');try{const {b,gear}=s;for(let x=27;x<=33;x++)for(let y=1;y<=5;y++)b.map.set(x,y,26,4);b.ordnance={burst:vi.fn()};gear.select('gadget1');s.advance(.2);gear.press();s.advance(.4);expect(gear.projectile.lastRocket?.hit).toBe('world');expect(b.ordnance.burst).toHaveBeenCalledTimes(1);expect(b.broken).toBeGreaterThan(0);expect(b.map.get(33,2,26)).toBe(4);expect(s.target.hp).toBe(1000);expect(gear.projectile.parts).toHaveLength(0);}finally{s.dispose();}});
 it('launches on the near side of a wall within the muzzle offset instead of through it',async()=>{const s=await setup(kit);try{const {b,gear,world}=s;b.arena.units=[];world.set(b.camera,Transform,{pos:[30.5,2.84,30.4]}).unwrap();for(let x=29;x<33;x++)for(let y=1;y<6;y++)b.map.set(x,y,29,4);gear.select('gadget1');s.advance(.2);gear.press();expect(gear.projectile.parts[0].previous[2]).toBeGreaterThan(30);s.advance(.2);expect(gear.projectile.lastRocket?.hit).toBe('world');}finally{s.dispose();}});
 it('keeps one rocket per press, respects cooldown/reload and does not consume empty reserves',async()=>{const s=await setup(kit);try{const {b,gear}=s;gear.select('gadget1');s.advance(.2);b.reload=1;gear.press();expect(b.mag).toBe(1);b.reload=0;gear.press();expect(b.mag).toBe(0);expect(b.cooldown).toBeCloseTo(60/19);gear.press();gear.release();expect(b.shots).toBe(1);expect(b.reserve).toBe(2);s.advance(3.3);gear.press();expect(b.shots).toBe(1);expect(gear.snapshot().ammo.rpg).toEqual({mag:0,reserve:2});}finally{s.dispose();}});
});
