import {describe,it,expect} from 'vitest';
import {readFileSync} from 'node:fs';
import vm from 'node:vm';
import {createMatchInspect,inspectPose,INSPECT_DURATION} from '../match-inspect.ts';
import {setup} from './equipment-fixture.ts';
import {type ModeId} from '../catalog.ts';
const kit={primary:'ar',secondary:'usp',gadget1:'medkit',gadget2:'ammo',grenade:'frag',melee:'knife'};
describe('EQ-05 actual original post-match inspection',()=>{
 it.each([false,true])('matches the original player pose for melee=%s',melee=>{const code=readFileSync(new URL('../../../../modes/small-battle/js/player.js',import.meta.url),'utf8'),start=code.indexOf('Player.prototype.updateWeaponInspect = function (dt)'),end=code.indexOf('Player.prototype.endWeaponInspect',start),env:any={Player:function(){},THREE:{MathUtils:{lerp:(a:number,b:number,t:number)=>a+(b-a)*t}}};vm.createContext(env);vm.runInContext(code.slice(start,end),env);for(const t of [0,.05,.2,.42,.8,1.83,2.4]){const pos:number[]=[],rot:number[]=[],left:any={rotation:{x:.95,z:.48},position:{y:-.14,z:-.18}},player:any={_inspecting:true,_inspectT:0,_resetCrouchStance(){},camera:{fov:70,quaternion:{setFromEuler(){}},position:{set(){}},updateProjectionMatrix(){}},_inspectHip:{x:.3,y:-.34,z:-.52},_inspectStartFov:70,_weaponDef:()=>({melee}),viewModel:{position:{set:(...v:number[])=>pos.push(...v)},rotation:{set:(...v:number[])=>rot.push(...v)}},leftArm:left,_leftArmRest:{rx:.95,rz:.48,y:-.14,z:-.18},pitch:0,yaw:0,euler:{set(){}},getEyePosition:()=>({x:0,y:0,z:0})};env.Player.prototype.updateWeaponInspect.call(player,t);const actual=inspectPose(t,melee);expect(actual.pos).toEqual(pos);expect(actual.fov).toBeCloseTo(player.camera.fov,10);expect(actual.left.rx).toBeCloseTo(left.rotation.x-.95,10);expect(actual.pitch).toBe(player._inspectPitch);expect(actual.yaw).toBe(player._inspectYaw);expect(actual.roll).toBe(player._inspectRoll);}});
 it.each(['core','tdm','ffa','gungame','demo'] as const)('%s waits for the FINAL result, then plays all 2.4 seconds before results',async mode=>{const s=await setup(kit,mode);try{let presented=0,restored=0;const b=s.b,owner=createMatchInspect(b,()=>presented++,()=>restored++,()=>70);b.inspect=owner;b.arena.match.ended=false;expect(owner.update(1)).toBe(false);b.arena.match.phase='round-end';expect(owner.update(1)).toBe(false);b.arena.match.ended=true;b.arena.match.scoringLive=()=>false;b.firing=b.ads=true;b.reload=2;b.keys.add('KeyW');expect(owner.blocksSimulation).toBe(true);expect(owner.resultsReady).toBe(false);owner.update(.01);expect(owner.active).toBe(true);expect(b.firing||b.ads).toBe(false);expect(b.reload).toBe(0);expect(b.keys.size).toBe(0);s.gear.press();s.gear.release();owner.update(2.38);expect(owner.resultsReady).toBe(false);owner.update(.01);expect(owner.resultsReady).toBe(true);expect(owner.active).toBe(false);expect(owner.snapshot().elapsed).toBe(INSPECT_DURATION);expect(restored).toBe(1);expect(presented).toBeGreaterThan(2);expect(owner.update(10)).toBe(false);owner.dispose();owner.dispose();expect(owner.update(1)).toBe(false);}finally{s.dispose();}});
 it('held knife is inspected even when dead, input cannot switch it or spend ammo',async()=>{const s=await setup(kit,'tdm');try{s.gear.select('melee');s.advance(.2);const b=s.b;const poses:boolean[]=[];b.inspect=createMatchInspect(b,(_,melee)=>poses.push(melee),()=>{},()=>48);b.dead=true;b.arena.match.ended=true;b.arena.match.scoringLive=()=>false;b.inspect.update(.5);expect(b.inspect.snapshot()).toMatchObject({weapon:'knife',melee:true,state:'playing'});expect(poses.every(Boolean)).toBe(true);expect(s.gear.select('primary')).toBe(false);s.gear.press();s.gear.release();expect(b.shots).toBe(0);b.inspect.update(1.9);expect(b.inspect.resultsReady).toBe(true);}finally{s.dispose();}});
 it('large conquest keeps its original direct results without adding inspection',async()=>{const s=await setup({...kit,primary:'ak74'},'conquest');try{const b=s.b;b.arena.match.ended=true;b.inspect=createMatchInspect(b,()=>{throw Error('unexpected inspection');},()=>{},()=>70);expect(b.inspect.update(4)).toBe(false);expect(b.inspect.resultsReady).toBe(true);expect(b.inspect.blocksSimulation).toBe(false);}finally{s.dispose();}});
 it('canceling a finale restores the camera once, and owner disposal is idempotent',async()=>{const s=await setup(kit,'tdm');try{let restored=0;const b=s.b;b.arena.match.ended=true;b.inspect=createMatchInspect(b,()=>{},()=>restored++,()=>70);b.inspect.update(.5);b.inspect.dispose();b.inspect.dispose();expect(restored).toBe(1);expect(b.inspect.active).toBe(false);expect(b.inspect.update(100)).toBe(false);}finally{s.dispose();}});
});
