import {describe,it,expect} from 'vitest';
import {readFileSync} from 'node:fs';
import vm from 'node:vm';
import {backstab,slashPose,type MeleePhase} from '../melee-rules.ts';
import {weaponsFor,type ModeId} from '../catalog.ts';
import {setup} from './equipment-fixture.ts';
import {arenaFixture} from './gunfire-fixture.ts';
import {Transform} from '@forgeax/engine/scene';
function oldMelee(mode:ModeId){const env:any={THREE:{Vector3:class{}},VF:{}};env.window=env;vm.createContext(env);const source=readFileSync(new URL(mode==='conquest'?'../../../../js/melee.js':'../../../../modes/small-battle/js/melee.js',import.meta.url),'utf8').replace('global.VF.Melee = {','global.VF.Melee = {applySlashPose,');vm.runInContext(source,env);return env.VF.Melee;}
const kit={primary:'ar',secondary:'usp',gadget1:'medkit',gadget2:'ammo',grenade:'frag',melee:'knife'};
async function duel(mode:ModeId='conquest',range=1.5){const s=await setup({...kit,primary:mode==='conquest'?'ak74':'ar'},mode);s.physics.teleport(s.enemy.entity,[30,1.98,30-range]);s.enemy.yaw=Math.PI;s.gear.select('melee');s.advance(.2);return s;}
describe('EQ-05 original knife rules and poses',()=>{
 it.each(['conquest','tdm'] as const)('uses original %s damage, timing, cone, lunge and movement parameters',mode=>{const d=weaponsFor(mode).knife;expect([d.damage,d.backstabDamage,d.attackRange,d.attackAngle,d.fireRate,d.windupTime,d.activeTime,d.recoveryTime,d.lungeRange,d.lungeCooldown,d.moveSpeedMul,d.sprintSpeedMul]).toEqual([90,999,2,Math.PI/3,.45,.05,.15,.25,2.6,.3,1.12,1.18]);});
 it.each(['conquest','tdm'] as const)('matches original %s shoulder pose at every phase',mode=>{const old=oldMelee(mode),rest={x:.45,y:-.51,z:.77,rx:.1,ry:.2,rz:.3},def=weaponsFor(mode).knife;for(const phase of ['idle','windup','active','recovery'] as MeleePhase[])for(const t of [0,.01,.025,.05,.1,.2,.3]){const slash={position:{x:0,y:0,z:0},rotation:{x:0,y:0,z:0}},player={_knifeNode:{visible:true,userData:{slash,rest}}};old.applySlashPose(player,{phase,t},def);const p=slashPose(mode,phase,t,def as any,rest);expect([p.x,p.y,p.z,p.rx,p.ry,p.rz]).toEqual([slash.position.x,slash.position.y,slash.position.z,slash.rotation.x,slash.rotation.y,slash.rotation.z]);}});
 it('matches the original horizontal backstab boundary, regardless of elevation',()=>{const old=oldMelee('tdm');for(let i=0;i<36;i++)for(const y of [-10,0,5]){const a:[number,number,number]=[Math.sin(i)*2,y,Math.cos(i)*2],q:[number,number,number]=[0,0,0],yaw=i*.3;expect(backstab(a,q,yaw)).toBe(old.isBackstab({x:a[0],y,z:a[2]},{x:0,y:0,z:0},yaw));}expect(backstab([0,9,0],[0,0,0],0)).toBe(false);});
});
describe('EQ-05 knife in the native battle',()=>{
 it('windup does not damage; a frontal swing hits once for 90 and leaves gun ammunition untouched',async()=>{const s=await duel();try{const {b,gear,enemy}=s,ammo={...b.ammoState.ak74};b.spawnProtection=5;b.stealthUntil=100;gear.press();expect(b.spawnProtection).toBe(0);expect(b.stealthUntil).toBe(0);s.advance(.02);expect(enemy.hp).toBe(100);s.advance(.06);expect(enemy.hp).toBe(10);gear.release();s.advance(.3);expect(enemy.hp).toBe(10);expect(b.ammoState.ak74).toEqual(ammo);expect(b.shots).toBe(0);}finally{s.dispose();}});
 it('a rear hit executes and emits the kill feedback',async()=>{const s=await duel('tdm');try{s.enemy.yaw=0;s.gear.press();s.advance(.1);expect(s.enemy.hp).toBe(-899);expect(s.gear.melee.snapshot().lastHit).toMatchObject({backstab:true,damage:999,killed:true});expect(s.b.notice).toBe('背刺处决');expect(s.gear.melee.flash).toBe('kill');}finally{s.dispose();}});
 it('accepts the original 60 degree half cone, but rejects targets outside it',async()=>{for(const a of [50,70]){const s=await duel();try{const angle=a*Math.PI/180;s.physics.teleport(s.enemy.entity,[30+Math.sin(angle)*1.7,1.98,30-Math.cos(angle)*1.7]);s.b.pitch=-.3;s.advance(.1);s.gear.press();s.advance(.1);expect(s.enemy.hp<100).toBe(a===50);}finally{s.dispose();}}});
 it('prefers the closest enemy, not array order, and never cleaves two targets',async()=>{const s=await duel();try{const farther={...s.enemy,id:'far',hp:100,entity:s.b.playerBody};s.b.arena.units=[farther,s.enemy];const position=s.b.arena.position;s.b.arena.position=(u:any)=>u===farther?[30,1.08,28.1]:position(u);s.gear.press();s.advance(.12);expect(s.enemy.hp).toBe(10);expect(farther.hp).toBe(100);}finally{s.dispose();}});
 it('uses the look direction to break distance ties',async()=>{const s=await duel();try{const off={...s.enemy,id:'off-axis',hp:100},position=s.b.arena.position;s.b.arena.units=[off,s.enemy];s.b.arena.position=(u:any)=>u===off?[30.6,1.08,28.62]:position(u);s.gear.press();s.advance(.1);expect(s.enemy.hp).toBe(10);expect(off.hp).toBe(100);}finally{s.dispose();}});
 it('a missed opening can hit a target entering the active window',async()=>{const s=await duel('tdm',3);try{s.gear.press();s.advance(.06);expect(s.enemy.hp).toBe(100);s.physics.teleport(s.enemy.entity,[30,1.98,28.5]);s.advance(.06);expect(s.enemy.hp).toBe(10);}finally{s.dispose();}});
 it('wall and smoke occlusion both block knife damage',async()=>{for(const blocker of ['wall','smoke']){const s=await duel();try{if(blocker==='wall')for(let x=29;x<32;x++)for(let y=1;y<5;y++)s.b.map.set(x,y,29,4);else s.gear.zones.push({id:44,kind:'smoke',position:[30,1,29.3],age:2,life:12,tick:0});s.gear.press();s.advance(.25);expect(s.enemy.hp).toBe(100);}finally{s.dispose();}}});
 it('held attack repeats, mouse release prevents further swings',async()=>{const s=await duel('tdm');try{s.enemy.hp=1000;s.gear.press();s.advance(1.1);expect(s.gear.melee.snapshot().swings).toBe(3);expect(s.enemy.hp).toBe(730);s.gear.release();s.advance(.5);expect(s.gear.melee.snapshot().swings).toBe(3);}finally{s.dispose();}});
 it('switching, death, seating and warmup cancel a pending attack',async()=>{for(const action of ['switch','death','seat','warmup']){const s=await duel();try{s.gear.press();if(action==='switch')s.gear.select('primary');if(action==='death')s.b.dead=true;if(action==='seat')s.b.vehicles={seated:{}};if(action==='warmup')s.b.arena.match.scoringLive=()=>false;s.advance(.3);expect(s.enemy.hp).toBe(100);expect(s.gear.melee.snapshot().phase).toBe('idle');expect(s.gear.melee.snapshot().held).toBe(false);}finally{s.dispose();}}});
 it('preserves knife movement bonuses and excludes core and gun-game selection',async()=>{const s=await duel();try{expect(s.gear.movementScale).toBe(1.12);s.b.keys.add('ShiftLeft');expect(s.gear.movementScale).toBe(1.18);s.gear.select('primary');expect(s.gear.movementScale).toBe(1);}finally{s.dispose();}for(const mode of ['core','gungame'] as const){const s=await setup(kit,mode);try{expect(s.gear.select('melee')).toBe(false);}finally{s.dispose();}}});
 it('lunges no farther than 0.6 m through the actual Rapier controller',async()=>{const s=await duel('tdm',2.5);try{s.b.grounded=true;const before=s.physics.position(s.b.playerBody);s.gear.press();expect(s.gear.melee.snapshot().lungeTarget).toBe('enemy');s.advance(.15);const after=s.physics.position(s.b.playerBody);expect(before[2]-after[2]).toBeGreaterThan(.45);expect(before[2]-after[2]).toBeLessThanOrEqual(.61);expect(s.enemy.hp).toBe(10);}finally{s.dispose();}});
 it('Rapier prevents an initiated lunge from passing a newly closed wall',async()=>{const s=await duel('tdm',2.5);try{s.b.grounded=true;s.gear.press();for(let x=28;x<33;x++)for(let y=1;y<6;y++)s.b.map.set(x,y,29,4);s.advance(.25);expect(s.physics.position(s.b.playerBody)[2]).toBeGreaterThan(29.99);expect(s.enemy.hp).toBe(100);}finally{s.dispose();}});
 it('airborne players cannot initiate or continue a lunge',async()=>{const s=await duel('tdm',2.5);try{s.b.grounded=false;s.gear.press();expect(s.gear.melee.snapshot().lungeTarget).toBeNull();s.gear.cancel();s.advance(.5);s.b.grounded=true;s.gear.press();s.b.grounded=false;s.advance(.1);expect(s.gear.melee.snapshot().lungeTarget).toBeNull();expect(s.physics.position(s.b.playerBody)[2]).toBeCloseTo(30);}finally{s.dispose();}});
 it('low frame rates cannot skip the active hit window',async()=>{const s=await duel();try{s.gear.press();s.b.elapsed+=.3;s.gear.update(.3);expect(s.enemy.hp).toBe(10);expect(s.gear.melee.snapshot().phase).toBe('recovery');}finally{s.dispose();}});
 it('real arena damage records a knife kill without breaking blocks or damaging objectives',async()=>{const s=await arenaFixture('tdm');try{s.target.hp=100;s.target.yaw=0;s.physics.teleport(s.target.entity,[30,1.94,28.5]);s.gear.select('melee');s.advance(.2);s.gear.press();s.advance(.1);expect(s.target.alive).toBe(false);expect(s.arena.match.stats.player.kills).toBe(1);expect(s.b.broken).toBe(0);expect(s.b.shots).toBe(0);}finally{s.dispose();}});
});
