import {aiHitChance} from '../tactical-aim.ts';
import {CoreSpawnRules} from '../core-spawn-rules.ts';
import {describe,it,expect} from 'vitest';
import {World} from '@forgeax/engine/ecs';
import {Transform,GlobalTransform,Name} from '@forgeax/engine/scene';
import {registerPhysicsComponents} from '@forgeax/engine/physics';
import {createRapier3DPhysicsWorld,loadRapier3D,registerPhysicsSystems} from '@forgeax/engine/physics-rapier3d';
import {NativePhysics} from '../native-physics.ts';
import {VoxelMap} from '../voxel-map.ts';
import {ObjectiveRules} from '../objective-rules.ts';
import {TacticalNavigation} from '../tactical-navigation.ts';
import {installSdBomb} from '../../original/sd-bomb.ts';
import {installSdMatch} from '../../original/sd-match.ts';
function map(){const width=32,height=12,ground=new Int8Array(width*width);ground.fill(0);const m=new VoxelMap(width,height,new Uint8Array(width*width*height),ground,new Float32Array(width*width),{});for(let x=0;x<width;x++)for(let z=0;z<width;z++)m.set(x,0,z,1);return m;}
describe('native gameplay systems',()=>{
 it('Rapier voxel collision blocks motion and a committed opening permits passage',async()=>{const w=new World();for(const c of [Transform,GlobalTransform,Name])w.components.register(c).unwrap();registerPhysicsComponents(w);const rapier=await loadRapier3D();if('code' in rapier)throw Error('Real Rapier WASM required: '+rapier.code);const backend=createRapier3DPhysicsWorld(rapier);w.insertResource('PhysicsWorld',backend);const unregister=registerPhysicsSystems(w),m=map();for(let y=1;y<5;y++)for(let z=0;z<32;z++)m.set(12,y,z,4);const p=new NativePhysics(w,m),actor=p.character([9,1.04,10.5],'test');
  const tick=()=>{p.around(p.position(actor));p.flush();w.update(1/60).unwrap();};try{for(let i=0;i<30;i++)tick();expect(p.ready(p.position(actor))).toBe(true);for(let i=0;i<60;i++){p.move(actor,[.1,-.05,0]);tick();}expect(p.position(actor)[0]).toBeLessThan(11.8);expect(p.position(actor)[1]).toBeGreaterThan(1.5);for(let y=1;y<5;y++)for(let z=8;z<13;z++)m.set(12,y,z,0);for(let i=0;i<10;i++)tick();for(let i=0;i<50;i++){p.move(actor,[.1,-.05,0]);tick();}expect(p.position(actor)[0]).toBeGreaterThan(14);p.dispose();w.despawn(actor).unwrap();w.update(1/60).unwrap();expect(backend.getBodyCount()).toBe(0);}finally{unregister();backend.dispose();}},30000);
 it('navigation routes around walls and does not walk through sealed obstacles',()=>{const m=map();for(let z=2;z<20;z++)for(let y=1;y<5;y++)m.set(12,y,z,4);const nav=new TacticalNavigation(m),path=nav.path([8.5,1.04,10.5],[17.5,1.04,10.5],2000);expect(path.length).toBeGreaterThan(15);for(const p of path)expect(m.overlaps(p,.3,1.75)).toBe(false);expect(path.at(-1)![0]).toBeGreaterThan(15);});
 it('bounded distant routing leaves a walled base through its gate',()=>{const width=320,height=24,ground=new Int8Array(width*width),m=new VoxelMap(width,height,new Uint8Array(width*width*height),ground,new Float32Array(width*width),{});for(let x=0;x<width;x++)for(let z=0;z<width;z++)m.set(x,0,z,1);for(let x=37;x<=77;x++)for(let z=50;z<=90;z++)if(x<40||x>74||z<53||z>87)if(!(z>87&&x>=54&&x<=61))for(let y=1;y<11;y++)m.set(x,y,z,4);const route=new TacticalNavigation(m).path([52.5,1.04,80.5],[262.5,1.04,249.5]);expect(route.length).toBeGreaterThan(10);expect(route.at(-1)![2]).toBeGreaterThan(95);for(const p of route)expect(m.overlaps(p,.3,1.75)).toBe(false);});
 it('conquest contests, captures, bleeds tickets and ends on exhaustion',()=>{const flag={id:'A',position:[10,1,10] as [number,number,number],owner:null,capture:0,contested:false,hp:0},m=new ObjectiveRules('conquest',[flag]);m.start();m.update(5);const ally={team:'ally' as const,position:[10,1,10] as [number,number,number],alive:true};m.occupy(12,[ally,{...ally,team:'enemy'}]);expect(flag.capture).toBe(0);for(let i=0;i<11;i++)m.occupy(1,[ally]);expect(flag.owner).toBe('ally');m.score.enemy=1;m.occupy(3,[ally]);expect(m.winner).toBe('ally');expect(m.ended).toBe(true);});
 it('conquest recovers abandoned progress, drains each opposing held flag and resets sweep on contest',()=>{const flags=[{id:'A',position:[8,1,8] as [number,number,number],owner:'ally' as const,capture:1,contested:false,hp:0},{id:'B',position:[80,1,80] as [number,number,number],owner:'enemy' as const,capture:-1,contested:false,hp:0}],m=new ObjectiveRules('conquest',flags);m.start();m.update(5);m.occupy(3,[]);expect(m.score).toEqual({ally:999,enemy:999});flags[0].capture=.5;m.occupy(5,[]);expect(flags[0].capture).toBeGreaterThan(.5);const actors=flags.map((f,i)=>({id:'a'+i,team:'ally' as const,alive:true,position:f.position}));for(let i=0;i<40;i++)m.occupy(1,actors);expect(flags.every(f=>f.owner==='ally')).toBe(true);m.occupy(1,[...actors,{...actors[0],team:'enemy'}]);expect(m.sweep.ally).toBe(0);for(let i=0;i<60;i++)m.occupy(1,actors);expect(m.winner).toBe('ally');expect(m.endReason).toContain('60');});
 it('core rejects friendly damage and finishes exactly once',()=>{const m=new ObjectiveRules('core',[]);m.start();m.update(5);expect(m.damageCore('ally',500,'ally')).toBe(false);m.damageCore('enemy',1000,'ally');expect(m.winner).toBe('ally');m.registerKill({victim:{id:'p',team:'ally'},killer:{id:'q',team:'enemy'}});expect(m.score.ally).toBe(1000);});
 it('demolition preserves hold cancellation, dropped pickup, detonation, defuse, halftime and seven-round victory',()=>{const env:any={VF:{GameModes:{getParams:()=>({buyTime:0,roundTime:110,resultTime:0,roundsToWin:7,halfSwapAfter:6,bombTimer:45,plantTime:4,defuseTime:7})}}};const bomb=installSdBomb(env),m=installSdMatch(env);m.hooks={aliveCount:()=>5,setupRound:()=>{},pickCarrier:()=> 'p'};m.start();m.update(.01);bomb.beginPlant('p','A',{pos:{x:0,y:1,z:0}});m.update(2);bomb.cancelPlant('release');expect(bomb.plantProgress).toBe(0);bomb.drop({x:0,y:1,z:0});expect(bomb.pickup('q')).toBe(false);m.update(.5);expect(bomb.pickup('q')).toBe(true);bomb.beginPlant('q','B',{pos:{x:0,y:1,z:0}});m.update(4);bomb.beginDefuse('d',false);m.update(7);expect(m.wins.enemy).toBe(1);for(let i=0;i<6;i++){m.update(.01);m.update(.01);m._endRound('enemy','test round');}expect(m.matchOver).toBe(true);expect(m.winner).toBe('enemy');expect(m.attackerTeam).toBe('enemy');});
});

it('core forward spawns reset on contest or departure, change owner at 20 seconds and never capture a home',()=>{const m=new CoreSpawnRules([{id:'home',x:10,y:1,z:10,team:'ally',fixed:true},{id:'pad',x:40,y:1,z:40,team:'enemy',fixed:false}]),a={team:'ally' as const,position:[40,1,40] as [number,number,number],alive:true};m.update(19,[a]);expect(m.points[1].owner).toBe('enemy');m.update(1,[a,{...a,team:'enemy'}]);expect(m.points[1].capture).toBe(0);m.update(10,[a]);m.update(1,[]);expect(m.points[1].capture).toBe(0);m.update(20,[a]);expect(m.points[1].owner).toBe('ally');m.update(30,[{team:'enemy',position:[10,1,10],alive:true}]);expect(m.points[0].owner).toBe('ally');});

it('navigation detours around a parked native vehicle',()=>{const m=map(),nav=new TacticalNavigation(m);nav.obstacles=[{min:[11,1,7],max:[16,4,14]}];const route=nav.path([8.5,1.04,10.5],[20.5,1.04,10.5]);expect(route.at(-1)![0]).toBeGreaterThan(18);expect(route.some(p=>p[2]<7||p[2]>14)).toBe(true);expect(route.some(p=>p[0]>11&&p[0]<16&&p[2]>7&&p[2]<14)).toBe(false);nav.obstacles=[];expect(nav.path([8.5,1.04,10.5],[20.5,1.04,10.5]).length).toBeLessThan(route.length);});

it('AI accuracy accounts for distance, moving fire and weapon role',()=>{expect(aiHitChance(60,true)).toBeLessThan(aiHitChance(15,true));expect(aiHitChance(30,true)).toBeLessThan(aiHitChance(30,false));expect(aiHitChance(60,false,'sniper')).toBeGreaterThan(aiHitChance(60,false,'shotgun'));for(const d of [0,20,100,1000])expect(aiHitChance(d,true)).toBeGreaterThan(0);});

it('core infantry can plan a physically clear jump across a narrow gap while ground vehicles cannot',()=>{const m=map();for(let x=12;x<=13;x++)for(let z=0;z<32;z++)m.set(x,0,z,0);const nav=new TacticalNavigation(m);expect(nav.path([10.5,1.04,10.5],[18.5,1.04,10.5]).at(-1)?.[0]||0).toBeLessThan(12);nav.allowJumps=true;const route=nav.path([10.5,1.04,10.5],[18.5,1.04,10.5]);expect(route.at(-1)![0]).toBeGreaterThan(16);expect(route.some(p=>p.jump)).toBe(true);});
