import {describe,it,expect} from 'vitest';
import {World,FixedUpdate} from '@forgeax/engine/ecs';
import {Transform,GlobalTransform,Name,ChildOf} from '@forgeax/engine/scene';
import {MeshFilter,MeshRenderer,Visibility} from '@forgeax/engine/render';
import {registerPhysicsComponents} from '@forgeax/engine/physics';
import {createRapier3DPhysicsWorld,loadRapier3D,registerPhysicsSystems,PhysicsStepSimulation} from '@forgeax/engine/physics-rapier3d';
import {NativePhysics} from '../native-physics.ts';
import {createSkills} from '../native-skills.ts';
import {createBuilding,constructionCells} from '../native-building.ts';
import {createOrdnance} from '../native-ordnance.ts';
import {smallTerrainMaterialGuid} from '../../identity.ts';
import {TacticalNavigation} from '../tactical-navigation.ts';
import {VoxelMap,type Vec3} from '../voxel-map.ts';
function flat(){const width=64,height=32,ground=new Int8Array(width*width);ground.fill(0);const m=new VoxelMap(width,height,new Uint8Array(width*width*height),ground,new Float32Array(width*width),{});for(let x=0;x<width;x++)for(let z=0;z<width;z++)m.set(x,0,z,1);return m;}
async function setup(){const world=new World();for(const c of [Transform,GlobalTransform,Name,ChildOf,MeshFilter,MeshRenderer,Visibility])world.components.register(c).unwrap();registerPhysicsComponents(world);const rapier=await loadRapier3D();if('code' in rapier)throw Error(rapier.code);const backend=createRapier3DPhysicsWorld(rapier);world.insertResource('PhysicsWorld',backend);const unregister=registerPhysicsSystems(world),map=flat(),physics=new NativePhysics(world,map),body=physics.character([30,1.04,30],'player'),camera=world.spawn({component:Transform,data:{pos:[30,2.84,30]}}).unwrap();const blasts:any[]=[];
 const b:any={mode:'core',classId:'engineer',map,physics,playerBody:body,camera,material:smallTerrainMaterialGuid,dead:false,health:50,armor:0,buildBlocks:20,buildCores:1,deployables:[],elapsed:0,skillCooldown:0,keys:new Set(),yaw:0,pitch:-.7,notice:'',noticeLeft:0,shieldUntil:0,shieldHealth:0,stealthUntil:0,grenades:2,speedBoostUntil:0};const player={alive:true,team:'ally',entity:body},enemyBody=physics.character([30,1.04,20],'enemy'),enemy={id:'enemy',alive:true,hp:100,team:'enemy',entity:enemyBody};b.arena={nav:new TacticalNavigation(map),match:{scoringLive:()=>true},objectives:[],player,units:[enemy],position:(u:any)=>{const p=physics.position(u.entity);return [p[0],p[1]-.9,p[2]];},damage:(u:any,n:number)=>{u.hp-=n;},blast:(...args:any[])=>blasts.push(args)};
 const tick=(dt=1/60)=>{b.elapsed+=dt;physics.around(physics.position(body));physics.around(physics.position(enemyBody));physics.flush();world.update(dt).unwrap();};for(let i=0;i<30;i++)tick();return {world,backend,b,enemy,blasts,tick,dispose(){physics.dispose();world.despawn(body).unwrap();world.despawn(camera).unwrap();world.despawn(enemyBody).unwrap();world.update(1/60).unwrap();expect(backend.getBodyCount()).toBe(0);unregister();backend.dispose();}};
}
describe('native interactive systems',()=>{
 it('construction commits atomically, spends real inventory, rotates and rejects occupied footprints',async()=>{const s=await setup();try{const {b}=s,building=createBuilding(b);building.select('cover');const pos=b.physics.position(b.playerBody),hit=b.map.raycast([pos[0],pos[1]+.9,pos[2]],[0,Math.sin(b.pitch),-Math.cos(b.pitch)],12)!;const blocked=[Math.floor(hit.point[0])-2,1,Math.floor(hit.point[2])] as Vec3;b.map.set(...blocked,4);const blockedState=b.map.blocks.slice();building.place();expect(b.buildBlocks).toBe(20);expect(b.map.blocks).toEqual(blockedState);b.map.set(...blocked,0);const before=b.map.blocks.slice();building.place();expect(b.buildBlocks).toBe(18);expect(b.map.blocks.reduce((n:number,id:number,i:number)=>n+(id!==before[i]?1:0),0)).toBe(24);const after=b.map.blocks.slice();b.buildBlocks=1;building.place();expect(b.buildBlocks).toBe(1);expect(b.map.blocks).toEqual(after);expect(constructionCells('cover',[20,1,20],1)).not.toEqual(constructionCells('cover',[20,1,20],0));building.select('tower');b.physics.teleport(b.playerBody,[48,1.94,48]);b.pitch=-.12;building.place();expect(b.buildCores,b.notice).toBe(0);expect(b.notice).toContain('防御塔');}finally{s.dispose();}},30000);
 it('non-equipment class abilities create useful state, turret damages enemies and recalled entities are released',async()=>{const s=await setup();try{const {b,enemy}=s;const skills=createSkills(s.world,b),ordnance=createOrdnance(s.world,b);b.ordnance=ordnance;
  b.classId='ghost';skills.activate();expect(b.stealthUntil).toBeGreaterThan(b.elapsed);expect(b.bonusShot).toBe(0);skills.breakStealth();expect(b.bonusShot).toBe(40);
  b.classId='juggernaut';b.skillCooldown=0;skills.activate();expect(b.shieldHealth).toBe(280);b.shieldUntil=0;skills.update(.1);
  b.classId='medic';b.skillCooldown=0;skills.activate();skills.release();skills.update(1);expect(b.health).toBeGreaterThan(50);
  b.classId='engineer';b.skillCooldown=0;skills.activate();skills.release();expect(b.deployables).toHaveLength(1);expect(b.buildBlocks).toBe(8);for(let i=0;i<30;i++){s.tick();skills.update(1/60);}expect(enemy.hp).toBeLessThan(100);skills.activate();expect(b.deployables).toHaveLength(0);expect(b.buildBlocks).toBe(16);
  b.classId='raider';b.skillCooldown=0;for(let y=1;y<5;y++)b.map.set(30,y,25,4);skills.activate();expect(b.map.get(30,2,25)).toBe(0);
  // Vanguard now belongs to the held-equipment owner; covered with real Rapier in remote-explosives.test.ts.
  skills.dispose();ordnance.dispose();
 }finally{s.dispose();}},30000);
 it('pausing gates native dynamic motion and fuse time, then resumes without resetting velocity',async()=>{const s=await setup();try{const ordnance=createOrdnance(s.world,s.b);s.b.ordnance=ordnance;let paused=false;s.world.replaceSystem(FixedUpdate,PhysicsStepSimulation.name,{...PhysicsStepSimulation,runIf:()=>!paused}).unwrap();ordnance.throwGrenade();for(let i=0;i<15;i++){ordnance.update(1/60);s.tick();}const snapshot=s.backend.captureDerivedPhysicsState!(),dynamic=snapshot.bodies.find(x=>x.bodyType==='dynamic')!;expect(dynamic).toBeDefined();const initial=s.backend.getDerivedMotion!(dynamic.entity)!;paused=true;for(let i=0;i<180;i++)s.tick();expect(s.backend.getDerivedMotion!(dynamic.entity)).toEqual(initial);expect(s.blasts).toHaveLength(0);paused=false;for(let i=0;i<180;i++){ordnance.update(1/60);s.tick();}expect(s.blasts.length).toBe(1);ordnance.dispose();}finally{s.dispose();}},30000);
});
