import {describe,it,expect,vi} from 'vitest';
import {Transform} from '@forgeax/engine/scene';
import {setup} from './equipment-fixture.ts';
import {createSkills} from '../native-skills.ts';
import {vanguardDamage,rayBox,rotateYaw,surfaceQuat} from '../remote-explosives.ts';
const large={primary:'ak74',secondary:'usp',gadget1:'charge',gadget2:'ammo',grenade:'frag',melee:'knife'};
const small={primary:'ar',secondary:'sg',gadget1:'',gadget2:'',grenade:'semtex',melee:'knife'};
function wall(s:Awaited<ReturnType<typeof setup>>,z=25){for(let x=27;x<34;x++)for(let y=1;y<7;y++)s.b.map.set(x,y,z,4);}
describe('EQ-03 remote explosives — native runtime contract',()=>{
 it('left press throws once, release does not duplicate; slot selection and empty left click cannot detonate',async()=>{const s=await setup(large);try{wall(s);s.gear.select('gadget1');s.advance(.2);s.gear.press();s.advance(.05);expect(s.gear.projectile.parts).toHaveLength(1);s.gear.release();s.advance(.5);expect(s.gear.inventory.charges).toBe(1);s.gear.press();s.advance(.5);expect(s.gear.inventory.charges).toBe(0);expect(s.gear.projectile.charges).toHaveLength(2);s.gear.select('gadget1');s.advance(.2);s.gear.press();s.advance(.2);expect(s.gear.projectile.charges).toHaveLength(2);expect(s.b.notice).toContain('已用完');expect(s.gear.secondary()).toBe(true);expect(s.gear.projectile.charges).toHaveLength(0);expect(s.gear.canAds).toBe(false);}finally{s.dispose();}});
 it('right click detonates mixed remote types, including airborne charges, while leaving other grenades',async()=>{const s=await setup(large);try{for(const kind of ['charge','semtex','frag','flash','smoke','molotov','stun'] as const)s.gear.projectile.launch(kind);s.gear.select('gadget1');s.gear.secondary();expect(s.gear.projectile.parts.map(p=>p.kind)).toEqual(['frag','flash','smoke','molotov','stun']);s.gear.secondary();expect(s.gear.projectile.parts).toHaveLength(5);s.gear.select('primary');expect(s.gear.secondary()).toBe(false);}finally{s.dispose();}});
 it('remote detonation does not wait for a throw cooldown or old automatic fuse',async()=>{const s=await setup(small,'tdm');try{wall(s);s.gear.select('grenade');s.advance(.2);s.gear.press();s.advance(.05);expect(s.gear.snapshot().remoteCount).toBe(1);expect(s.gear.snapshot().ready).toBe(false);s.gear.secondary();expect(s.gear.snapshot().remoteCount).toBe(0);s.gear.inventory.grenades=1;s.advance(.5);s.gear.press();s.advance(8);expect(s.gear.projectile.parts).toHaveLength(1);expect(s.gear.projectile.parts[0].landed).toBe(true);s.gear.secondary();expect(s.gear.projectile.parts).toHaveLength(0);}finally{s.dispose();}});
 it('small vanguard G selects C4, left spends the 24s cooldown, right remains usable at zero charges',async()=>{const s=await setup(small,'tdm'),skills=createSkills(s.world,s.b);try{skills.activate();expect(s.gear.inventory.id).toBe('charge');expect(s.gear.inventory.gun).toBe(false);skills.release();s.advance(.2);expect(s.gear.projectile.parts).toHaveLength(0);s.gear.press();s.advance(.05);expect(s.b.skillCooldown).toBe(24);expect(s.gear.availableCharges).toBe(0);expect(s.gear.inventory.grenades).toBe(1);s.gear.select('primary');skills.activate();expect(s.gear.inventory.id).toBe('charge');s.gear.secondary();expect(s.gear.projectile.charges).toHaveLength(0);expect(s.b.speedBoostUntil).toBeCloseTo(s.b.elapsed+3);s.advance(.6);s.gear.press();s.advance(.1);expect(s.gear.projectile.parts).toHaveLength(0);s.b.skillCooldown=0;s.gear.press();s.advance(.1);expect(s.gear.projectile.parts).toHaveLength(1);}finally{skills.dispose();s.dispose();}});
 it('Q reselects an empty semtex detonator after switching to a gun without spending a grenade',async()=>{const s=await setup(small,'tdm');try{s.gear.key('KeyQ');expect(s.gear.inventory.id).toBe('semtex');expect(s.gear.projectile.parts).toHaveLength(0);s.advance(.2);s.gear.press();s.advance(.6);expect(s.gear.inventory.grenades).toBe(0);s.gear.select('primary');s.advance(.2);s.gear.key('KeyQ');expect(s.gear.inventory.id).toBe('semtex');expect(s.gear.projectile.charges).toHaveLength(1);s.gear.secondary();expect(s.gear.projectile.charges).toHaveLength(0);}finally{s.dispose();}});
 it('active-device cap never spends stock or overwrites existing deployed charges',async()=>{const s=await setup(large);try{for(let i=0;i<32;i++)expect(s.gear.projectile.launch('charge')).toBe(true);s.gear.select('gadget1');s.advance(.2);s.gear.press();s.advance(.1);expect(s.gear.inventory.charges).toBe(2);expect(s.gear.projectile.charges).toHaveLength(32);expect(s.b.notice).toContain('上限');}finally{s.dispose();}});
 it('construction mode does not remotely detonate a stowed C4',async()=>{const s=await setup(small,'core');try{s.gear.selectSkillCharge();s.gear.projectile.launch('charge');s.b.building={active:true};expect(s.gear.secondary()).toBe(false);expect(s.gear.projectile.charges).toHaveLength(1);}finally{s.dispose();}});
 it('other small classes and gun game cannot equip the vanguard charge',async()=>{for(const mode of ['tdm','gungame'] as const){const s=await setup(small,mode);try{if(mode==='tdm')s.b.classId='medic';expect(s.gear.selectSkillCharge()).toBe(false);expect(s.gear.inventory.id).toBe('ar');}finally{s.dispose();}}});
 it('remotes adhere flush to walls and resume native gravity when support is destroyed',async()=>{const s=await setup(large);try{wall(s);s.gear.select('gadget1');s.advance(.2);s.gear.press();s.advance(.7);const part=s.gear.projectile.parts[0];expect(part.landed).toBe(true);expect(part.support).toBeDefined();const q=s.world.get(part.entity,Transform).unwrap();Array.from(q.quat).forEach((v,i)=>expect(v).toBeCloseTo(surfaceQuat([0,0,1])[i]));const before=s.physics.position(part.entity);s.b.map.set(...part.support!,0);s.advance(.3);expect(s.physics.position(part.entity)[1]).toBeLessThan(before[1]);expect(part.admitted).toBe(true);}finally{s.dispose();}});
 it.each(['charge','semtex'] as const)('%s follows an allied vehicle translation and rotation; destruction detaches it',async kind=>{const s=await setup(large);try{const entity=s.world.spawn({component:Transform,data:{pos:[30,2.6,25]}}).unwrap(),vehicle:any={entity,hp:100,type:'jeep',team:'ally',yaw:0};s.b.vehicles={vehicles:[vehicle],damageArea:vi.fn()};s.gear.projectile.launch(kind);s.advance(.7);const part=s.gear.projectile.parts[0];expect(part.attachment?.actor).toBe(vehicle);const local=[...part.attachment!.offset] as [number,number,number];s.world.set(entity,Transform,{pos:[33,2.6,26]}).unwrap();vehicle.yaw=Math.PI/2;s.advance(.1);const expected=rotateYaw(local,vehicle.yaw).map((v,i)=>v+[33,2.6,26][i]);s.physics.position(part.entity).forEach((v,i)=>expect(v).toBeCloseTo(expected[i]));vehicle.hp=0;s.advance(.1);expect(part.attachment).toBeUndefined();s.world.despawn(entity).unwrap();}finally{s.dispose();}});
 it('bullet damage destroys a charge once; nearby devices chain react and wall occlusion protects devices',async()=>{const s=await setup(large);try{wall(s);s.gear.projectile.launch('charge');s.gear.projectile.launch('semtex');s.advance(.7);const part=s.gear.projectile.parts[0],p=s.physics.position(part.entity);const hit=s.gear.projectile.raycast([p[0],p[1],p[2]+2],[0,0,-1],3);expect(hit).not.toBeNull();s.gear.projectile.damageCharge(hit!.part,30);expect(s.gear.projectile.parts).toHaveLength(2);s.gear.projectile.damageCharge(hit!.part,40);expect(s.gear.projectile.parts).toHaveLength(0);const broken=s.b.broken;s.gear.projectile.damageCharge(hit!.part,500);expect(s.b.broken).toBe(broken);expect(broken).toBeGreaterThan(0);s.gear.projectile.launch('charge');const device=s.gear.projectile.parts[0],q=s.physics.position(device.entity);for(let x=28;x<33;x++)for(let y=1;y<6;y++)s.b.map.set(x,y,27,4);s.gear.projectile.damageArea([q[0],q[1],25],7,200);expect(s.gear.projectile.parts).toHaveLength(1);}finally{s.dispose();}});
 it('batch explosions finish even if the first blast causes reset; repeated detonation never applies twice',async()=>{const s=await setup(large);try{const burst=vi.fn(()=>s.gear.reset());s.b.ordnance={burst};s.gear.projectile.launch('charge');s.gear.projectile.launch('charge');expect(s.gear.projectile.detonateCharges()).toBe(2);expect(burst).toHaveBeenCalledTimes(2);expect(s.gear.projectile.detonateCharges()).toBe(0);}finally{s.dispose();}});
 it('death and respawn remove both remote types, preserve ordinary in-flight grenades, and restore inventory',async()=>{const s=await setup(large);try{s.gear.projectile.launch('charge');s.gear.projectile.launch('semtex');s.gear.projectile.launch('frag');s.b.dead=true;s.advance(.1);expect(s.gear.projectile.parts.map(p=>p.kind)).toEqual(['frag']);expect(s.gear.secondary()).toBe(false);s.b.dead=false;s.gear.reset();expect(s.gear.inventory.charges).toBe(2);expect(s.gear.inventory.slot).toBe('primary');}finally{s.dispose();}});
 it('keeps mode-specific C4 damage falloff and uses yaw-aware vehicle contact queries',()=>{expect([0,3.5,4.5,5.5,6.5,7.5,7.6].map(vanguardDamage)).toEqual([120,120,100,80,70,60,0]);expect(rayBox([0,0,5],[0,0,-1],[0,0,0],[1,1,3],0,10)?.distance).toBe(2);expect(rayBox([0,0,5],[0,0,-1],[0,0,0],[1,1,3],Math.PI/2,10)?.distance).toBeCloseTo(4);});
});
