import {describe,it,expect,vi} from 'vitest';
import {THROWABLE_RULES as R,blastDamage,flashDuration,stunDuration,smokeState,smokeOccludes,aiThrowableStatus} from '../throwable-rules.ts';
import {createThrowableEffects} from '../throwable-effects.ts';
import {VoxelMap,type Vec3} from '../voxel-map.ts';
import {setup} from './equipment-fixture.ts';
import {itemsFor} from '../catalog.ts';
function fixture(mode='tdm'){
 const map=new VoxelMap(64,20,new Uint8Array(64*64*20),new Int8Array(64*64),new Float32Array(64*64),{4:3});for(let x=0;x<64;x++)for(let z=0;z<64;z++)map.set(x,0,z,1);
 const player:any={id:'player',team:'ally',isPlayer:true,alive:true,p:[30,1,30]},enemy:any={id:'enemy',team:'enemy',alive:true,p:[30,1,26],yaw:Math.PI},ally:any={id:'ally',team:'ally',alive:true,p:[30,1,26]},hits:any[]=[],sounds:string[]=[];
 const b:any={map,mode,elapsed:0,broken:0,pitch:0,yaw:0,audio:{play:(id:string)=>sounds.push(id)},arena:{player,units:[enemy,ally],position:(u:any)=>u.p,objectives:[],match:{damageCore:vi.fn()},damage:(u:any,n:number,a:any,id:string)=>hits.push({target:u.id,amount:n,id})}};
 const visuals={spawn:vi.fn(),update:vi.fn(),remove:vi.fn(),dispose:vi.fn()},fx=createThrowableEffects(b,visuals,()=>1),advance=(dt:number)=>{b.elapsed+=dt;fx.update(dt);};
 return {b,map,player,enemy,ally,hits,sounds,visuals,fx,advance};
}
describe('EQ-02 original throwable gameplay contract',()=>{
 it('exposes the three large and six small choices, keeping gun game disabled in inventory',()=>{expect(itemsFor('conquest','grenade').map(i=>i.id).sort()).toEqual(['flash','frag','smoke']);expect(itemsFor('tdm','grenade').map(i=>i.id).sort()).toEqual(['flash','frag','molotov','semtex','smoke','stun']);});
 it('matches explosion inner / outer damage and rounding',()=>{expect(blastDamage('frag',0)).toBe(130);expect(blastDamage('frag',2.5)).toBe(130);expect(blastDamage('frag',4.25)).toBe(75);expect(blastDamage('frag',6)).toBe(20);expect(blastDamage('frag',6.01)).toBe(0);expect(blastDamage('semtex',2.2)).toBe(130);expect(blastDamage('semtex',5.5)).toBe(20);});
 it('keeps the original 40–100 degree flash curve and distance floor, including back-facing exposure',()=>{expect(flashDuration(0,1)).toBe(3);expect(flashDuration(8,1)).toBeCloseTo(1.2);expect(flashDuration(8,-1)).toBeCloseTo(.66);expect(flashDuration(4,Math.cos(70*Math.PI/180))).toBeCloseTo(1.6275);expect(flashDuration(8.1,1)).toBe(0);});
 it('keeps seven-second stun, original player multipliers and AI half-speed without freezing',()=>{expect(stunDuration(0)).toBe(7);expect(stunDuration(6)).toBeCloseTo(3.85);expect(stunDuration(6.01)).toBe(0);expect(R.stun.move).toBe(.4);expect(R.stun.turn).toBe(.28);expect(aiThrowableStatus(1,2,0)).toEqual({canShoot:false,move:1});expect(aiThrowableStatus(1,0,2)).toEqual({canShoot:false,move:.5});expect(aiThrowableStatus(3,2,2)).toEqual({canShoot:true,move:1});});
 it('smoke expands 1.5 seconds, holds for 12, fades for 2, and blocks a 3.4 metre column',()=>{expect(smokeState(1.5).radius).toBe(5);expect(smokeState(13.49).density).toBe(1);expect(smokeState(14.5)).toMatchObject({phase:'fade',radius:2.5,density:.5,life:1});expect(smokeState(15.5).density).toBe(0);expect(smokeOccludes([0,1,0],2,[-6,2,0],[6,2,0])).toBe(true);expect(smokeOccludes([0,1,0],2,[-6,5,0],[6,5,0])).toBe(false);expect(smokeOccludes([0,1,0],15.5,[-6,2,0],[6,2,0])).toBe(false);});
 it('blast hurts the owner and enemy, protects teammates; free-for-all removes team protection',()=>{for(const mode of ['tdm','ffa']){const f=fixture(mode);f.fx.detonate('frag',[30,2.1,27]);expect(f.hits.some(h=>h.target==='player')).toBe(true);expect(f.hits.some(h=>h.target==='enemy')).toBe(true);expect(f.hits.some(h=>h.target==='ally')).toBe(mode==='ffa');f.fx.dispose();}});
 it('solid walls stop blast damage; smoke does not provide ballistic cover',()=>{const f=fixture();for(let x=28;x<=32;x++)for(let y=1;y<5;y++)f.map.set(x,y,28,4);f.fx.detonate('frag',[30,2,30]);expect(f.hits.some(h=>h.target==='enemy')).toBe(false);for(let x=28;x<=32;x++)for(let y=1;y<5;y++)f.map.set(x,y,28,0);f.fx.detonate('smoke',[30,1.2,28]);f.advance(2);f.fx.detonate('frag',[30,2,30]);expect(f.hits.some(h=>h.target==='enemy')).toBe(true);});
 it('flash is blocked by walls, causes ringing for the exposed player, and writes AI status',()=>{const f=fixture();f.fx.detonate('flash',[30,2,28]);expect(f.fx.flashLeft).toBeGreaterThan(0);expect(f.enemy.blindUntil).toBeGreaterThan(0);expect(f.ally.blindUntil).toBeUndefined();expect(f.sounds).toContain('throwable.flash.ring');f.fx.clearPlayerStatus();expect(f.fx.flash).toBe(0);for(let x=28;x<33;x++)for(let y=1;y<5;y++)f.map.set(x,y,29,4);f.fx.detonate('flash',[30,2,28]);expect(f.fx.flashLeft).toBe(0);});
 it('fire ticks every half second at low FPS, stops after seven seconds and respects walls and water',()=>{const f=fixture();f.enemy.p=[30,1,28];f.fx.detonate('molotov',[30,1.2,27]);f.advance(1.2);expect(f.hits.filter(h=>h.target==='enemy')).toHaveLength(2);f.advance(10);expect(f.hits.filter(h=>h.target==='enemy')).toHaveLength(14);expect(f.fx.zones).toHaveLength(0);expect(f.visuals.remove).toHaveBeenCalledTimes(1);const g=fixture();g.enemy.p=[30,1,28];for(let x=28;x<=32;x++)for(let y=1;y<4;y++)g.map.set(x,y,27,4);g.fx.detonate('molotov',[30,1.2,26]);g.advance(1);expect(g.hits).toHaveLength(0);g.map.set(20,1,20,8);g.fx.detonate('molotov',[20,1.2,20]);expect(g.fx.zones).toHaveLength(1);expect(g.b.notice).toContain('入水熄灭');});
 it('fire and smoke remain on the lower floor under a bridge',()=>{const f=fixture();for(let x=25;x<35;x++)for(let z=25;z<35;z++)f.map.set(x,6,z,4);f.fx.detonate('smoke',[30,1.2,30]);f.fx.detonate('molotov',[30,1.2,30]);for(const z of f.fx.zones)expect(z.position[1]).toBeCloseTo(1.04);});
 it('smoke fades inside-camera opacity and clears occlusion on expiry and dispose',()=>{const f=fixture();f.fx.detonate('smoke',[30,1.1,30]);f.advance(2);expect(f.fx.smokeOpacity([30,2,30])).toBeCloseTo(.96);expect(f.fx.blocksLine([20,2,30],[40,2,30])).toBe(true);f.advance(12.5);expect(f.fx.smokeOpacity([30,2,30])).toBeCloseTo(.48);f.advance(1);expect(f.fx.smokeOpacity([30,2,30])).toBe(0);expect(f.fx.blocksLine([20,2,30],[40,2,30])).toBe(false);f.fx.dispose();f.fx.dispose();expect(f.visuals.dispose).toHaveBeenCalledTimes(1);});
 it('explosive and fire core damage require range and solid line of sight',()=>{const f=fixture('core');f.b.arena.objectives=[{owner:'enemy',position:[30,1,28]}];f.fx.detonate('semtex',[30,2.5,28]);expect(f.b.arena.match.damageCore).toHaveBeenCalledWith('enemy',70,'ally');f.fx.detonate('molotov',[30,1.1,28]);f.advance(.5);expect(f.b.arena.match.damageCore).toHaveBeenCalledWith('enemy',10,'ally');f.b.arena.match.damageCore.mockClear();f.fx.detonate('frag',[50,2,50]);expect(f.b.arena.match.damageCore).not.toHaveBeenCalled();});
});
describe('EQ-02 real Rapier throwable transport',()=>{
 const kit={primary:'ar',secondary:'sg',gadget1:'',gadget2:'',grenade:'semtex',melee:'knife'};
 it.each(['frag','flash','stun'] as const)('%s fuse starts on release, not while held',async kind=>{const s=await setup({...kit,grenade:kind},'tdm');try{s.gear.key('KeyQ');s.advance(4);expect(s.gear.projectile.parts).toHaveLength(0);s.gear.releaseQuick();s.advance(.5);expect(s.gear.projectile.parts[0].kind).toBe(kind);s.advance(R[kind].fuse+.2);expect(s.gear.projectile.parts).toHaveLength(0);expect(s.gear.inventory.grenades).toBe(0);}finally{s.dispose();}});
 it('semtex sticks to a moving actor and remains armed until remote detonation',async()=>{const s=await setup(kit,'tdm');try{s.physics.teleport(s.enemy.entity,[30,1.94,26]);s.b.pitch=-.08;s.gear.key('KeyQ');s.advance(.2);s.gear.press();s.advance(.7);const part=s.gear.projectile.parts[0];expect(part.kind).toBe('semtex');expect(part.landed).toBe(true);expect(part.attachment?.actor).toBe(s.enemy);const p=s.physics.position(part.entity);s.physics.teleport(s.enemy.entity,[32,1.94,26]);s.advance(.1);expect(s.physics.position(part.entity)[0]-p[0]).toBeCloseTo(2);s.advance(1);expect(s.gear.projectile.parts).toHaveLength(1);s.advance(3);expect(s.gear.projectile.parts).toHaveLength(1);expect(s.gear.secondary()).toBe(true);expect(s.gear.projectile.parts).toHaveLength(0);}finally{s.dispose();}});
 it('wall contact arms remote semtex and molotov shatters; destruction never occurs through wall spawn',async()=>{for(const kind of ['semtex','molotov']){const s=await setup({...kit,grenade:kind},'tdm');try{for(let x=28;x<33;x++)for(let y=1;y<6;y++)s.b.map.set(x,y,27,4);s.gear.key('KeyQ');if(kind==='semtex'){s.advance(.2);s.gear.press();}else s.gear.releaseQuick();s.advance(.8);if(kind==='semtex'){expect(s.gear.projectile.parts[0].landed).toBe(true);expect(s.physics.position(s.gear.projectile.parts[0].entity)[2]).toBeGreaterThan(27);}else{expect(s.gear.projectile.parts).toHaveLength(0);expect(s.gear.zones[0].kind).toBe('molotov');}}finally{s.dispose();}}});
});
