import {arenaFixture} from './gunfire-fixture.ts';
import {describe,it,expect,vi} from 'vitest';
import {readFileSync} from 'node:fs';
import {runInNewContext} from 'node:vm';
import {Transform} from '@forgeax/engine/scene';
import {weaponsFor,type ModeId} from '../catalog.ts';
import {shotSpread,pelletDirections,fireInterval} from '../weapon-shot-rules.ts';
import {fireGun} from '../native-gunfire.ts';
import {createVehicles} from '../native-vehicles.ts';
const rng=()=>{let n=47;return()=>{n=(Math.imul(n,1664525)+1013904223)>>>0;return n/4294967296;};};
class Vector{constructor(public x:number,public y:number,public z:number){}clone(){return new Vector(this.x,this.y,this.z);}normalize(){const n=Math.hypot(this.x,this.y,this.z);this.x/=n;this.y/=n;this.z/=n;return this;}}
function originalRays(mode:ModeId,def:any,ads:number){
 const file=mode==='conquest'?'../js/weapons.js':'../modes/small-battle/js/weapons.js',source=readFileSync(file,'utf8');
 const start=source.indexOf('Weapons.prototype._fireRays = function'),code=source.slice(start,source.indexOf('\n  };',start)+6);
 const helpers=mode==='conquest'?['spreadFromAccuracy','adsSpreadMul'].map(name=>{const p=source.indexOf('function '+name+'(');return source.slice(p,source.indexOf('\n  }',p)+4);}).join('\n'):'';
 const context:any={Math:Object.assign(Object.create(Math),{random:rng()}),result:[],def,base:new Vector(.12,.08,-.989545)};
 runInNewContext('const ACCURACY_SPREAD_MAX=.12;function Weapons(){};'+helpers+';'+code+';const w=new Weapons();w._tmpMuzzle={copy:()=>({addScaledVector(){}})};w.player={aiming:'+!!ads+',_adsBlend:'+ads+'};w._trace=(o,d)=>result.push([d.x,d.y,d.z]);w._fireRays(def,{},base);',context);
 return context.result;
}
describe('EQ-04 original pellet rules and native hit resolution',()=>{
 for(const mode of ['conquest','tdm'] as const)it(mode+' reproduces the executed original fireRays for every imported gun and ADS endpoint',()=>{for(const def of Object.values(weaponsFor(mode)))for(const ads of [0,1]){expect(pelletDirections([.12,.08,-.989545],def,mode,ads,rng())).toEqual(originalRays(mode,def,ads));}});
 it('retains explicit small ADS interpolation, zero spread and RPM/legacy intervals',()=>{const small=weaponsFor('tdm'),large=weaponsFor('conquest');expect(shotSpread(small.sg,'tdm',.5)).toBeCloseTo(.08);expect(shotSpread(large.m200,'conquest')).toBe(0);expect(fireInterval(large.ak74)).toBeCloseTo(60/670);expect(fireInterval(small.sg)).toBe(.8);expect(fireInterval(large.rpg)).toBeCloseTo(60/19);});
 it('one shotgun cartridge produces eight independent damaging pellets and one gun sound',async()=>{const s=await arenaFixture();try{s.b.audio={gun:vi.fn()};const before=s.b.mag;expect(fireGun(s.b,()=>.5)).toBe(true);expect(s.target.hp).toBe(888);expect(s.b.mag).toBe(before-1);expect(s.b.shots).toBe(1);expect(s.b.audio.gun).toHaveBeenCalledTimes(1);expect(s.b.lastGunshot.rays).toHaveLength(8);expect(s.b.lastGunshot.rays.every((r:any)=>r.target==='unit')).toBe(true);expect(s.b.firing).toBe(false);}finally{s.dispose();}});
 it('pellet spread creates partial hits and narrows when aiming, with no damage outside weapon range',async()=>{const s=await arenaFixture();try{const {b,target,physics}=s;physics.teleport(target.entity,[30,1.94,10]);fireGun(b,rng());const hip=1000-target.hp;target.hp=1000;b.ads=true;b.cooldown=0;b.firing=true;fireGun(b,rng());const ads=1000-target.hp;expect(hip).toBeLessThan(ads);expect(ads).toBeLessThanOrEqual(112);target.hp=1000;physics.teleport(target.entity,[30,1.94,-10]);b.cooldown=0;b.firing=true;fireGun(b,()=>.5);expect(target.hp).toBe(1000);}finally{s.dispose();}});
 it('each ray respects solid occlusion before units and preserves the native damage owner',async()=>{const s=await arenaFixture();try{for(let x=27;x<34;x++)for(let y=1;y<7;y++)for(let z=25;z<29;z++)s.b.map.set(x,y,z,15);const q=s.arena.raycast([30,2.1,30],[0,0,-1],20);expect(q?.kind).toBe('unit');expect(s.target.hp).toBe(1000);fireGun(s.b,()=>.5);expect(s.target.hp).toBe(1000);expect(s.b.lastGunshot.rays.every((r:any)=>r.target==='world')).toBe(true);}finally{s.dispose();}});
 it('chooses the nearer infantry or rotated vehicle before committing damage',async()=>{const s=await arenaFixture('conquest');try{const {b,physics,target}=s;b.vehicles=await createVehicles(s.world,s.host,b,()=>false);const v=b.vehicles.vehicles.find((v:any)=>v.team==='enemy'&&v.type==='jeep');for(const other of b.vehicles.vehicles)if(other!==v)other.hp=0;v.hp=360;v.yaw=Math.PI/2;physics.teleport(v.entity,[30,2.1,15]);b.weapon=weaponsFor('conquest').usp;b.weaponId='usp';b.firing=true;fireGun(b,()=>.5);expect(target.hp).toBe(970);expect(v.hp).toBe(360);target.hp=1000;physics.teleport(v.entity,[30,2.1,26]);b.cooldown=0;b.firing=true;fireGun(b,()=>.5);expect(target.hp).toBe(1000);expect(v.hp).toBe(330);expect(b.lastGunshot.rays[0].target).toBe('vehicle');}finally{s.dispose();}});
 it('semi-auto needs a new trigger while automatic repeats after its interval',async()=>{const s=await arenaFixture();try{const {b}=s;fireGun(b,()=>.5);b.cooldown=0;expect(fireGun(b)).toBe(false);b.firing=true;expect(fireGun(b)).toBe(true);b.weapon=weaponsFor('tdm').ar;b.weaponId='ar';b.cooldown=0;b.firing=true;expect(fireGun(b)).toBe(true);expect(fireGun(b)).toBe(false);s.advance(.11);expect(fireGun(b)).toBe(true);}finally{s.dispose();}});
 it('warmup, reload, empty ammunition, held gadgets, death and interaction never consume ammunition',async()=>{const s=await arenaFixture();try{const {b}=s;for(const [key,value]of [['dead',true],['reload',1],['interacting',true],['cooldown',1]] as const){const old=b[key],mag=b.mag;b[key]=value;expect(fireGun(b)).toBe(false);expect(b.mag).toBe(mag);b[key]=old;}b.mag=0;expect(fireGun(b)).toBe(false);b.mag=7;s.arena.match.phase='prep';expect(fireGun(b)).toBe(false);s.arena.match.phase='battle';s.gear.select('grenade');b.firing=true;expect(fireGun(b)).toBe(false);}finally{s.dispose();}});
 it('all pellets keep the original shot definition if a kill upgrades the gun mid-shot',async()=>{const s=await arenaFixture();try{const {b}=s;let calls=0;b.arena.raycast=()=>({distance:5,kind:'unit',apply:(amount:number,id:string)=>{expect(amount).toBe(14);expect(id).toBe('sg');calls++;b.weapon=weaponsFor('tdm').m200;b.weaponId='m200';}});fireGun(b,()=>.5);expect(calls).toBe(8);expect(b.lastGunshot.weaponId).toBe('sg');expect(b.lastGunshot.rays).toHaveLength(8);}finally{s.dispose();}});
 it('multi-pellet fire damages the nearer hostile core instead of the infantry behind it',async()=>{const s=await arenaFixture('core');try{const o=s.arena.objectives.find(o=>o.owner==='enemy')!;o.position=[30,.6,26];expect(s.arena.raycast([30,2.1,30],[0,0,-1],30)?.kind).toBe('core');fireGun(s.b,()=>.5);expect(o.hp).toBe(888);expect(s.target.hp).toBe(1000);expect(s.b.lastGunshot.rays.every((r:any)=>r.target==='core')).toBe(true);}finally{s.dispose();}});
 it('shoots the nearer remote device without harming the infantry behind it, and vice versa',async()=>{const s=await arenaFixture('conquest');try{const {b,gear,world,target}=s;gear.select('secondary');s.advance(.2);gear.projectile.launch('charge');const charge=gear.projectile.parts[0];world.set(charge.entity,Transform,{pos:[30,2.1,26]}).unwrap();b.firing=true;fireGun(b,()=>.5);expect(charge.hp).toBe(30);expect(target.hp).toBe(1000);expect(b.lastGunshot.rays[0].target).toBe('device');world.set(charge.entity,Transform,{pos:[30,2.1,18]}).unwrap();b.cooldown=0;b.firing=true;fireGun(b,()=>.5);expect(target.hp).toBe(970);expect(charge.hp).toBe(30);expect(b.lastGunshot.rays[0].target).toBe('unit');}finally{s.dispose();}});
});

