#!/usr/bin/env bash
# scripts/codemod/verify-ac.sh — 14 automated AC oracle for
# feat-20260511-engine-package-family-rename.
#
# Covers AC-01, AC-02, AC-03, AC-04, AC-05, AC-06, AC-08, AC-09, AC-10,
# AC-11, AC-12, AC-13, AC-14, AC-16, AC-17.
# Skipped (human-read): AC-07 (AGENTS.md §Packages walkthrough),
# AC-15 (requirements-decisions.md D-NN narrative).
#
# Each AC is encapsulated in a `verify_ac_NN` function that returns 0 on pass
# and prints `[AC-NN] FAIL: <reason>` to stderr on failure. Main loop runs all
# checks, accumulates pass / fail counts, and exits non-zero if any failed.
#
# Charter command-4: explicit failure. `set -euo pipefail` would exit on the
# first failure; we instead want to run all checks and aggregate, so the
# script uses `|| true` per check and tracks a fail counter.
set -uo pipefail

REPO_ROOT="$(git rev-parse --show-toplevel)"
cd "$REPO_ROOT"

# rg is required only by this script (rename-engine-family.sh and its
# subscripts use node + jq + jscodeshift, no rg). Fail fast with a hint
# rather than letting the first `rg` invocation crash with command-not-found.
if ! command -v rg >/dev/null 2>&1; then
  echo "[fatal] 'rg' (ripgrep) not installed. Install via:" >&2
  echo "  macOS: 'brew install ripgrep'  ·  Ubuntu: 'sudo apt-get install -y ripgrep'" >&2
  exit 1
fi

PASS=0
FAIL=0
FAIL_NAMES=()

pass() { echo "[AC-$1] PASS" ; PASS=$((PASS+1)) ; }
fail() { echo "[AC-$1] FAIL: $2" >&2 ; FAIL=$((FAIL+1)) ; FAIL_NAMES+=("AC-$1") ; }

# AC-01: 14 workspace packages have correct new names (+ console + template + engine placeholder).
verify_ac_01() {
  local expected_names=(
    "@forgeax/engine"
    "@forgeax/engine-runtime"
    "@forgeax/engine-math"
    "@forgeax/engine-ecs"
    "@forgeax/engine-types"
    "@forgeax/engine-rhi"
    "@forgeax/engine-rhi-webgpu"
    "@forgeax/engine-rhi-wgpu"
    "@forgeax/engine-wgpu-wasm"
    "@forgeax/engine-naga"
    "@forgeax/engine-shader"
    "@forgeax/engine-shader-compiler"
    "@forgeax/engine-vite-plugin-shader"
    "@forgeax/engine-console"
    "@forgeax/engine-template-threejs-mvp"
  )
  local actual
  actual=$(jq -r '.name' packages/*/package.json templates/*/package.json 2>/dev/null | sort -u)
  local missing=()
  for n in "${expected_names[@]}"; do
    if ! echo "$actual" | grep -qx "$n"; then
      missing+=("$n")
    fi
  done
  if [ ${#missing[@]} -eq 0 ]; then
    pass 01
  else
    fail 01 "missing names: ${missing[*]}"
  fi
}

# AC-02: @forgeax/core is gone from source / docs / configs. Carve out:
# - bun.lock / pnpm-lock.yaml: regenerated by package manager, no source-of-truth
# - scripts/codemod/**: dictionary of old→new entries (intentional)
# - scripts/__tests__/fixtures/grep-gates/**: canonical fixtures pre/post rewrite
verify_ac_02() {
  local hits
  hits=$(rg -n --no-heading "@forgeax/core" \
    --glob '!**/*-progress.jsonl' \
    --glob '!**/history*' \
    --glob '!.forgeax-harness/forgeax-loop/**' \
    --glob '!.changeset/**' \
    --glob '!**/node_modules/**' \
    --glob '!**/dist/**' \
    --glob '!**/.git/**' \
    --glob '!.knowledge-base/log.md' \
    --glob '!.knowledge-base/sources/**' \
    --glob '!CHANGELOG.md' \
    --glob '!bun.lock' \
    --glob '!pnpm-lock.yaml' \
    --glob '!scripts/codemod/**' \
    --glob '!scripts/__tests__/fixtures/grep-gates/**' \
    || true)
  if [ -z "$hits" ]; then
    pass 02
  else
    fail 02 "remaining @forgeax/core hits: $(echo "$hits" | head -5 | tr '\n' ';')"
  fi
}

# AC-03: All bare-name imports rewritten to @forgeax/engine-*.
verify_ac_03() {
  local pattern="from ['\"]@forgeax/(math|ecs|core|types|rhi|rhi-webgpu|rhi-wgpu|wgpu-wasm|naga|shader|shader-compiler|vite-plugin-shader|engine|console)['\"]"
  local hits
  hits=$(rg -n --no-heading "$pattern" \
    --glob '!**/node_modules/**' \
    --glob '!**/dist/**' \
    --glob '!**/.git/**' \
    --glob '!**/*-progress.jsonl' \
    --glob '!.forgeax-harness/forgeax-loop/**' \
    --glob '!.knowledge-base/sources/**' \
    --glob '!scripts/codemod/**' \
    --glob '!scripts/__tests__/fixtures/grep-gates/**' \
    || true)
  if [ -z "$hits" ]; then
    pass 03
  else
    fail 03 "remaining legacy imports:\n$hits"
  fi
}

# AC-04: pnpm install + pnpm -r build exit 0 (lockfile up to date already gated by sync:check).
verify_ac_04() {
  if pnpm install --frozen-lockfile >/tmp/ac-04.log 2>&1 && \
     pnpm -r build >>/tmp/ac-04.log 2>&1; then
    pass 04
  else
    fail 04 "pnpm install --frozen-lockfile || pnpm -r build failed; see /tmp/ac-04.log"
  fi
}

# AC-05: smoke gate three commands. These are expensive (Dawn + browser + GPU);
# allow the caller to set SKIP_AC05=1 to skip in dev iteration.
verify_ac_05() {
  if [ "${SKIP_AC05:-0}" = "1" ]; then
    echo "[AC-05] SKIP (SKIP_AC05=1)"
    return 0
  fi
  if pnpm --filter @forgeax/hello-triangle smoke >/tmp/ac-05-smoke.log 2>&1 && \
     pnpm test:browser >/tmp/ac-05-browser.log 2>&1 && \
     pnpm test:dawn >/tmp/ac-05-dawn.log 2>&1; then
    pass 05
  else
    fail 05 "smoke gate failed; logs at /tmp/ac-05-{smoke,browser,dawn}.log"
  fi
}

# AC-06: metrics:check exit 0.
verify_ac_06() {
  if pnpm metrics:check >/tmp/ac-06.log 2>&1; then
    pass 06
  else
    fail 06 "pnpm metrics:check failed; see /tmp/ac-06.log"
  fi
}

# AC-08: @forgeax/engine-console bin is { forgeax-engine-console: ... }, top-level forgeax key absent.
verify_ac_08() {
  local bin_json
  bin_json=$(jq -c '.bin' packages/console/package.json)
  if echo "$bin_json" | jq -e 'has("forgeax-engine-console")' >/dev/null && \
     ! echo "$bin_json" | jq -e 'has("forgeax")' >/dev/null; then
    pass 08
  else
    fail 08 "packages/console/package.json bin = $bin_json (expected forgeax-engine-console, no bare forgeax)"
  fi
}

# AC-09: packages/engine/ placeholder: private:true, README exists, 0 source .ts files.
verify_ac_09() {
  local private
  private=$(jq -r '.private' packages/engine/package.json)
  local name
  name=$(jq -r '.name' packages/engine/package.json)
  local readme
  readme=$(test -f packages/engine/README.md && echo yes || echo no)
  local ts_count
  ts_count=$(find packages/engine/src -name '*.ts' 2>/dev/null | wc -l | tr -d ' ')
  if [ "$private" = "true" ] && [ "$name" = "@forgeax/engine" ] && [ "$readme" = "yes" ] && [ "$ts_count" = "0" ]; then
    pass 09
  else
    fail 09 "placeholder shape mismatch: private=$private name=$name readme=$readme ts_count=$ts_count"
  fi
}

# AC-10: KB wiki has no bare legacy names.
verify_ac_10() {
  local pattern='@forgeax/(math|ecs|core|types|rhi|rhi-webgpu|rhi-wgpu|wgpu-wasm|naga|shader|shader-compiler|vite-plugin-shader|console)([^-a-zA-Z0-9_]|$)'
  local hits
  hits=$(rg -n --no-heading "$pattern" .knowledge-base/wiki || true)
  if [ -z "$hits" ]; then
    pass 10
  else
    fail 10 "legacy names in KB wiki:\n$hits"
  fi
}

# AC-11: .forgeax-harness/forgeax-loop/todos.json title/description renamed; history not modified.
verify_ac_11() {
  local title_hits
  title_hits=$(jq -r '.todos[].title' .forgeax-harness/forgeax-loop/todos.json 2>/dev/null | \
    rg '@forgeax/(math|ecs|core|types|rhi|rhi-webgpu|rhi-wgpu|wgpu-wasm|naga|shader|shader-compiler|vite-plugin-shader|console)([^-a-zA-Z0-9_]|$)' || true)
  local desc_hits
  desc_hits=$(jq -r '.todos[].description // ""' .forgeax-harness/forgeax-loop/todos.json 2>/dev/null | \
    rg '@forgeax/(math|ecs|core|types|rhi|rhi-webgpu|rhi-wgpu|wgpu-wasm|naga|shader|shader-compiler|vite-plugin-shader|console)([^-a-zA-Z0-9_]|$)' || true)
  # history field untouched: not directly diff-able after merge; verify it parses + at
  # least one history entry references legacy name as evidence of preservation.
  local hist_count
  hist_count=$(jq -r '[.todos[] | select(.history != null) | .history | length] | add // 0' .forgeax-harness/forgeax-loop/todos.json)
  if [ -z "$title_hits" ] && [ -z "$desc_hits" ] && [ "$hist_count" -ge 0 ]; then
    pass 11
  else
    fail 11 ".forgeax-harness/forgeax-loop/todos.json residue: title_hits=[${title_hits//$'\n'/ }] desc_hits=[${desc_hits//$'\n'/ }]"
  fi
}

# AC-12: apps/*/package.json + templates/threejs-mvp/package.json deps use new names.
verify_ac_12() {
  local files=(apps/*/package.json templates/threejs-mvp/package.json)
  local bad=()
  for f in "${files[@]}"; do
    [ -f "$f" ] || continue
    local hits
    hits=$(jq -r '(.dependencies // {}) + (.devDependencies // {}) | keys[]' "$f" 2>/dev/null | \
      rg '^@forgeax/(math|ecs|core|types|rhi|rhi-webgpu|rhi-wgpu|wgpu-wasm|naga|shader|shader-compiler|vite-plugin-shader|console|engine)$' || true)
    if [ -n "$hits" ]; then
      bad+=("$f: $hits")
    fi
  done
  local tpl_name
  tpl_name=$(jq -r '.name' templates/threejs-mvp/package.json 2>/dev/null)
  if [ ${#bad[@]} -eq 0 ] && [ "$tpl_name" = "@forgeax/engine-template-threejs-mvp" ]; then
    pass 12
  else
    fail 12 "deps still legacy: ${bad[*]}; tpl_name=$tpl_name"
  fi
}

# AC-13: .github/workflows/*.yml use new names.
verify_ac_13() {
  local hits
  hits=$(rg -n --no-heading '@forgeax/(math|ecs|core|types|rhi|rhi-webgpu|rhi-wgpu|wgpu-wasm|naga|shader|shader-compiler|vite-plugin-shader|console)([^-a-zA-Z0-9_]|$)' .github/workflows || true)
  if [ -z "$hits" ]; then
    pass 13
  else
    fail 13 "legacy names in workflows:\n$hits"
  fi
}

# AC-14: scripts/check-*.mjs banned[] arrays + fixtures consistent — verified by unit tests.
verify_ac_14() {
  if pnpm test:unit >/tmp/ac-14.log 2>&1; then
    pass 14
  else
    fail 14 "pnpm test:unit failed; see /tmp/ac-14.log"
  fi
}

# AC-17: dual-lockfile parity — `bun install --frozen-lockfile --ignore-scripts` exits 0.
# Charter convention (AGENTS.md §Conventions): "Dual lockfile: pnpm-lock.yaml + bun.lock
# both committed; pnpm run sync if drift". If bun.lock drifts, the CI bun matrix job
# (ci.yml `bun: Install (frozen)` step) fails with `lockfile had changes, but lockfile is frozen`.
# Codemod orchestrator Phase H now regenerates bun.lock; this AC pins the parity.
# Skipped automatically if `bun` is not on PATH (env-dependent).
verify_ac_17() {
  if ! command -v bun >/dev/null 2>&1; then
    echo "[AC-17] SKIP (bun not on PATH)"
    return 0
  fi
  if bun install --frozen-lockfile --ignore-scripts >/tmp/ac-17.log 2>&1; then
    pass 17
  else
    fail 17 "bun install --frozen-lockfile --ignore-scripts failed; see /tmp/ac-17.log"
  fi
}

# AC-16: codemod idempotency — re-run produces zero diff.
# Pre-check ignores changes under .forgeax-harness/forgeax-loop/<feat>/ since
# those are append-only closed-loop SSOT artifacts (jsonl logs, decisions
# markdown) maintained orthogonally to the codemod surface.
verify_ac_16() {
  local dirty
  dirty=$(git status --porcelain | rg -v '^\?\? \.forgeax-harness/forgeax-loop/' | rg -v '^.. \.forgeax-harness/forgeax-loop/' || true)
  if [ -n "$dirty" ]; then
    fail 16 "working tree dirty (codemod surface); cannot verify idempotency: $dirty"
    return
  fi
  bash scripts/codemod/rename-engine-family.sh >/tmp/ac-16.log 2>&1
  # Diff ignores loop-state artifacts on the same grounds.
  if git diff --quiet -- ':!.forgeax-harness/forgeax-loop'; then
    pass 16
  else
    fail 16 "re-running codemod produced a non-empty diff (see git diff -- ':!.forgeax-harness/forgeax-loop'); /tmp/ac-16.log for codemod stdout"
  fi
}

main() {
  echo "[verify-ac] verifying 14 automated ACs in $REPO_ROOT"
  echo ""
  verify_ac_01
  verify_ac_02
  verify_ac_03
  verify_ac_06
  verify_ac_08
  verify_ac_09
  verify_ac_10
  verify_ac_11
  verify_ac_12
  verify_ac_13
  verify_ac_17
  # Heavy / build-dependent ACs at the end so failure shows quickly above.
  verify_ac_04
  verify_ac_14
  verify_ac_05
  verify_ac_16

  echo ""
  echo "[verify-ac] PASS=$PASS FAIL=$FAIL"
  if [ "$FAIL" -gt 0 ]; then
    echo "[verify-ac] failing ACs: ${FAIL_NAMES[*]}" >&2
    exit 1
  fi
}

main "$@"
