const fs=require('fs'),assert=require('node:assert/strict'),{chromium}=require('playwright');
const gunOnly=process.env.EQ05_GUN_ONLY==='1',out=gunOnly?'artifacts/eq-05-gun':'artifacts/eq-05';fs.mkdirSync(out,{recursive:true});
(async()=>{const browser=await chromium.launch({executablePath:'E:/Program Files/Tencent/QQBrowser/QQBrowser.exe',headless:true});const p=await browser.newPage({viewport:{width:1805,height:1083},deviceScaleFactor:1.5});const result={date:new Date().toISOString(),browser:'QQ headless, default GPU, isolated save; actual production inputs',steps:[],errors:[]};p.on('pageerror',e=>result.errors.push(e.message));p.on('console',m=>{if(m.type()==='error')result.errors.push(m.text().slice(0,1000));});
const read=()=>p.evaluate(()=>{const h=document.querySelector('#game-ui')?.firstElementChild,r=h?.shadowRoot;return {screen:document.documentElement.dataset.frontlineScreen,frame:document.documentElement.dataset.forgeaxFrameSubmitted,equipment:JSON.parse(h?.dataset.equipment||'null'),inspect:JSON.parse(h?.dataset.inspect||'null'),health:Number(h?.dataset.health),shots:Number(h?.dataset.shots),phase:h?.dataset.matchPhase,score:h?.dataset.teamScore,yaw:Number(h?.dataset.yaw),pitch:Number(h?.dataset.pitch),locked:!!document.pointerLockElement,position:JSON.parse(h?.dataset.playerPosition||'null'),targets:JSON.parse(h?.dataset.aiPositions||'[]'),message:r?.querySelector('#native-battle-message')?.textContent,resultVisible:!!r?.querySelector('#victory-overlay')&&!r.querySelector('#victory-overlay').classList.contains('hidden')&&getComputedStyle(r.querySelector('#victory-overlay')).display!=='none'};});
async function capture(name){const s=await read();result.steps.push({name,...s});fs.writeFileSync(out+'/qq-melee.json',JSON.stringify(result,null,2));await p.screenshot({path:out+'/'+name+'.png'});console.log(name,JSON.stringify({phase:s.phase,melee:s.equipment?.melee,inspect:s.inspect,position:s.position}));return s;}
async function lock(){for(let i=0;i<6;i++){await p.bringToFront();await p.waitForTimeout(150);if((await read()).locked)return;await p.mouse.click(900,400);await p.waitForTimeout(450);if((await read()).locked)return;}throw Error('pointer lock unavailable');}
async function key(k){await lock();await p.keyboard.down(k);await p.waitForTimeout(180);await p.keyboard.up(k);await p.waitForTimeout(250);}
async function start(){await p.locator('#class-confirm-btn').click();await p.locator('#squad-intro-skip').click();await p.waitForFunction(()=>document.documentElement.dataset.frontlineScreen==='battle'&&document.querySelector('#game-ui')?.firstElementChild?.dataset.matchPhase==='battle',null,{timeout:120000});await lock();}
async function aim(yaw,pitch){const s=await read();await p.evaluate(({x,y})=>document.dispatchEvent(new MouseEvent('mousemove',{movementX:x,movementY:y,bubbles:true})),{x:(s.yaw-yaw)/.0022,y:(s.pitch-pitch)/.0022});}
async function leave(){await p.mouse.up();await p.keyboard.up('KeyW');await p.keyboard.press('Escape');await p.locator('#pause-leave').click();await p.waitForTimeout(650);}
async function knifeChecks(label,code){await key(code);let s=await capture(label+'-knife-rest');assert.equal(s.equipment.slot,'melee');const shots=s.shots,ammo=s.equipment.ammo,swings=s.equipment.melee.swings;await p.mouse.down();await p.waitForTimeout(85);await capture(label+'-knife-swing');await p.waitForTimeout(1100);await p.mouse.up();await p.waitForTimeout(450);s=await capture(label+'-repeat-release');assert(s.equipment.melee.swings>=swings+2);assert.equal(s.shots,shots);assert.deepEqual(s.equipment.ammo,ammo);assert.equal(s.equipment.melee.phase,'idle');const stopped=s.equipment.melee.swings;await p.waitForTimeout(700);assert.equal((await read()).equipment.melee.swings,stopped);await key('Digit1');await p.mouse.down();await p.waitForTimeout(300);await p.mouse.up();s=await capture(label+'-switch-back-fire');assert(s.shots>shots);}
try{await p.goto('http://localhost:8766/');await p.waitForFunction(()=>document.documentElement.dataset.frontlineScreen==='home',null,{timeout:60000});result.ua=await p.evaluate(()=>navigator.userAgent);result.firstFrame=Number((await read()).frame);await p.locator('#enter-hub-btn').click();await p.waitForTimeout(650);if(!gunOnly){await p.locator('[data-mode-action="conquest32"]').click();await start();await knifeChecks('01-large','Digit6');await leave();}
 await p.locator('[data-quick-mode="tdm"]').click();await start();if(!gunOnly){await knifeChecks('02-small','Digit3');await key('Digit3');
 // Approach the closest opponent using only actual mouse/keyboard. No game-state writes.
 let hit=false;for(let i=0;i<85;i++){let s=await read();if(s.inspect?.state==='playing'||s.inspect?.state==='complete')break;if(s.health<=0){await p.mouse.up();await p.keyboard.up('KeyW');await p.waitForTimeout(1000);continue;}await lock();if(s.equipment.slot!=='melee')await key('Digit3');const p0=s.position,target=s.targets.filter(u=>u.hp>0&&u.team==='enemy').sort((a,b)=>Math.hypot(a.position[0]-p0[0],a.position[2]-p0[2])-Math.hypot(b.position[0]-p0[0],b.position[2]-p0[2]))[0];if(!target)break;const dx=target.position[0]-p0[0],dz=target.position[2]-p0[2],range=Math.hypot(dx,dz);await aim(Math.atan2(-dx,-dz),Math.atan2(target.position[1]+1.2-(p0[1]+.9),range));if(range>1.6)await p.keyboard.down('KeyW');else await p.keyboard.up('KeyW');if(range<3.5)await p.mouse.down();else await p.mouse.up();if(i%9===8){await p.keyboard.down('Space');await p.waitForTimeout(200);await p.keyboard.up('Space');}await p.waitForTimeout(250);s=await read();if(s.equipment.melee.lastHit){hit=true;await capture('03-small-native-knife-hit');break;}}
 await p.keyboard.up('KeyW');await p.mouse.up();result.liveMeleeHit=hit;}else{await lock();await p.mouse.down();await p.waitForTimeout(300);await p.mouse.up();await capture('01-held-gun-before-final');}
 // Let the authored match finish. Re-select the knife after respawn, then observe the finale.
 const deadline=Date.now()+720000;let lastLog=0,inspection=false,prior=null;
 while(Date.now()<deadline){const s=await read();if(s.inspect?.state==='playing'){inspection=true;assert.equal(s.resultVisible,false);await p.waitForTimeout(550);await capture(gunOnly?'04-final-gun-inspection':'04-final-knife-inspection');await p.mouse.click(900,400);await p.keyboard.press('Digit1');await p.keyboard.press('KeyR');await p.keyboard.down('KeyW');await p.waitForTimeout(180);await p.keyboard.up('KeyW');const during=await read();assert.equal(during.equipment.id,s.equipment.id);assert.equal(during.shots,s.shots);await p.waitForFunction(()=>JSON.parse(document.querySelector('#game-ui').firstElementChild.dataset.inspect).state==='complete',null,{timeout:7000});const end=await capture('05-results-after-full-inspection');assert.equal(end.inspect.elapsed,2.4);assert.equal(end.resultVisible,true);break;}
  if(s.inspect?.state==='complete')throw Error('Missed inspection observation');if(s.health>0&&s.equipment.slot!==(gunOnly?'primary':'melee'))await key(gunOnly?'Digit1':'Digit3');if(Date.now()-lastLog>45000){console.log('Awaiting actual match result',JSON.stringify({score:s.score,phase:s.phase,health:s.health}));lastLog=Date.now();fs.writeFileSync(out+'/qq-melee-progress.json',JSON.stringify(s,null,2));}prior=s;await p.waitForTimeout(150);}
 assert(inspection,'Authored match did not finish within QA window');await leave();await p.locator('[data-quick-mode="tdm"]').click();await start();const fresh=await capture('06-reentry-clean');assert.equal(fresh.inspect.state,'idle');assert.equal(fresh.equipment.melee.swings,0);assert.equal(fresh.equipment.melee.lastHit,null);assert.equal(fresh.resultVisible,false);await leave();result.lastFrame=Number((await read()).frame);assert.equal(result.errors.length,0,JSON.stringify(result.errors));result.passed=true;
}catch(e){result.failure=String(e);result.last=await read().catch(()=>null);console.error(e);await p.screenshot({path:out+'/failure.png'}).catch(()=>{});process.exitCode=1;}finally{fs.writeFileSync(out+'/qq-melee.json',JSON.stringify(result,null,2));await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1});
