import {aiThrowableStatus} from './throwable-rules.ts';
import {aiHitChance} from './tactical-aim.ts';
import {CoreSpawnRules} from './core-spawn-rules.ts';
import type {World,EntityHandle} from '@forgeax/engine/ecs';
import type {GameHost} from '@forgeax/engine/app';
import {Transform,ChildOf,Name} from '@forgeax/engine/scene';
import {MeshFilter,MeshRenderer,Visibility,VisibilityStateValue} from '@forgeax/engine/render';
import {createBoxGeometry} from '@forgeax/engine/geometry';
import type {MeshAsset,Handle} from '@forgeax/engine/types';
import {modelGuid,smallTerrainMaterialGuid} from '../identity.ts';
import {paramsFor,original,teamless,weaponsFor,type ModeId} from './catalog.ts';
import {installTdmMatch} from '../original/tdm-match.ts';
import {installFfaMatch} from '../original/ffa-match.ts';
import {installGgMatch} from '../original/gg-match.ts';
import {installSdMatch} from '../original/sd-match.ts';
import {installSdBomb} from '../original/sd-bomb.ts';
import {ObjectiveRules,type Objective,type Team} from './objective-rules.ts';
import {TacticalNavigation,type Waypoint} from './tactical-navigation.ts';
import type {NativePhysics} from './native-physics.ts';
import type {AssetGuid} from '@forgeax/engine/pack/guid';
import {Collider,RigidBody,RigidBodyTypeValue,ColliderShapeValue} from '@forgeax/engine/physics';
import type {Vec3} from './voxel-map.ts';
import type {CombatPort} from './arena.ts';
export type NativeCombatPort=CombatPort&{gear?:import('./battle.plugin.ts').BattleState['gear'];lastHurt?:number;keys:Set<string>;interacting:boolean;playerBody:EntityHandle;buildBlocks:number;buildCores:number;deployables:any[];yaw:number;classId:string;stealthUntil:number;shieldUntil:number;shieldHealth:number;onDeath?:(p:Vec3)=>void;sound?:(id:string,p:Vec3)=>void;explosionSound?:(p:Vec3)=>void;material:(id:number)=>AssetGuid};
type Unit={yaw?:number;lastHurt?:number;blindUntil?:number;stunUntil?:number;id:string;name:string;team:Team;isPlayer?:boolean;entity:EntityHandle;visual?:EntityHandle;hp:number;alive:boolean;cooldown:number;protection:number;respawn:number;vy:number;think:number;path:Waypoint[];goal?:Vec3;stuck?:number;mission:string;target:any;weaponId:string;type:string;mesh:any};
export async function createNativeArena(world:World,host:GameHost,mode:ModeId,source:any,combat:NativeCombatPort,physics:NativePhysics,cancelled:()=>boolean){
 const owned=new Set<EntityHandle>(),handles:Handle<'MeshAsset','shared'>[]=[],units:Unit[]=[],nav=new TacticalNavigation(combat.map),models=new Map<string,Handle<'MeshAsset','shared'>>();let playerRide:Waypoint[]|null=null;let closed=false,rng=(source.seed||14291)>>>0,playerRespawn=0;const timers:{at:number;fn:()=>void}[]=[];
 const random=()=>{rng=(Math.imul(rng,1664525)+1013904223)>>>0;return rng/4294967296;};
 function dispose(){if(closed)return;closed=true;for(const e of owned)world.despawn(e).unwrap();owned.clear();for(const h of handles)world.sharedRefs.release(h).unwrap();handles.length=0;timers.length=0;}
 try {
 for(const team of ['ally','enemy']){const asset=await host.assets.loadByGuid<MeshAsset>(modelGuid('soldier/small/ai/'+team));if(!asset.ok)throw asset.error;if(cancelled())throw Error('战场载入已取消');const h=world.allocSharedRef('MeshAsset',asset.value);handles.push(h);models.set(team,h);}
 nav.addZiplines(source.ziplines||[]);nav.allowJumps=mode==='core';
 const params=paramsFor(mode),basePositions:Vec3[]=source.bases.map((b:any)=>nav.safe([b.x,b.y??(combat.map.ground[Math.floor(b.z)*combat.map.width+Math.floor(b.x)]+1),b.z]));
 const player:any={id:'player',name:'你',isPlayer:true,team:'ally',entity:combat.playerBody};Object.defineProperties(player,{alive:{get:()=>!combat.dead},hp:{get:()=>combat.health},health:{get:()=>combat.health},weaponId:{get:()=>combat.weaponId}});
 const pos=(u:any):Vec3=>{const p=physics.position(u.entity);return [p[0],p[1]-.9,p[2]];};
 const ai:any={blue:[],red:[],aliveCount:(team:string)=>units.filter(u=>u.alive&&u.team===team).length,all:()=>units};
 const game:any={player,ai,mode:'pve',running:true,returnFromMatch:()=>combat.leave(),weapons:{get current(){return combat.weaponId;},forceEquip:(id:string)=>combat.setWeapon(id,true)}};
 const env:any={setTimeout:(fn:()=>void,ms:number)=>{timers.push({at:combat.elapsed+ms/1000,fn});},VF:{game,WEAPONS:weaponsFor(mode),GameModes:{getParams:paramsFor,param:(key:string,fallback:any)=>params[key]??fallback,isTeamless:()=>teamless(mode)},UI:{toast:(s:string)=>combat.notice(s)}}};
 const coreSpawns=new CoreSpawnRules(mode==='core'?source.spawnPoints||[]:[]);const objectives:Objective[]=[];
 if(mode==='conquest'){for(let i=0;i<6;i++){const t=(i+1)/7,x=basePositions[0][0]*(1-t)+basePositions[1][0]*t+(i%2?65:-65),z=basePositions[0][2]*(1-t)+basePositions[1][2]*t;objectives.push({id:'ABCDEF'[i],position:nav.safe([x,combat.map.ground[Math.floor(z)*combat.map.width+Math.floor(x)]+1,z]),owner:null,capture:0,contested:false,hp:0});}}
 if(mode==='core')basePositions.forEach((p,i)=>objectives.push({id:i?'敌方核心':'我方核心',position:source.cores?.[i]?[source.cores[i].x,source.cores[i].y,source.cores[i].z]:nav.safe([p[0]+8,p[1],p[2]]),owner:i?'enemy':'ally',capture:0,contested:false,hp:1000}));
 const sites=(source.sites||[]).map((s:any)=>({...s,position:nav.safe([s.x,s.y,s.z])}));
 const bomb=mode==='demo'?installSdBomb(env):null;
 const match:any=mode==='tdm'?installTdmMatch(env):mode==='ffa'?installFfaMatch(env):mode==='gungame'?installGgMatch(env):mode==='demo'?installSdMatch(env):new ObjectiveRules(mode as 'conquest'|'core',objectives);
 const demoStats=mode==='demo'?installTdmMatch(env):null;if(demoStats){demoStats.start();demoStats.scoreLimit=Infinity;demoStats.scoringLive=()=>match.scoringLive();Object.defineProperties(match,{score:{get:()=>match.wins},timeLeft:{get:()=>match.displayClock()},phaseLeft:{get:()=>match.roundClock},stats:{get:()=>demoStats.stats},feed:{get:()=>demoStats.feed},endReason:{get:()=>match.lastResult?.reason||''}});for(const key of ['register','registerDamage','registerKill','ranking','playerStats'])match[key]=(...args:any[])=>key==='playerStats'?demoStats.stats.player:demoStats[key](...args);}
 const markers:{entity:EntityHandle;objective:Objective}[]=[];const drops:{entity:EntityHandle;position:Vec3;core:boolean}[]=[];
 function box(p:Vec3,size:Vec3,materialId:number,label:string){const asset={...createBoxGeometry(...size).unwrap(),materialSlots:[{slotName:'body',defaultMaterial:combat.material(materialId)}]},h=world.allocSharedRef('MeshAsset',asset);handles.push(h);const e=world.spawn({component:Transform,data:{pos:p}},{component:Name,data:{value:label}},{component:MeshFilter,data:{assetHandle:h}},{component:MeshRenderer,data:{materials:[]}}).unwrap();owned.add(e);return e;}

 for(const [i,link] of nav.links.entries()){if(i%2)continue;const points=[link.from,...link.route];for(let j=1;j<points.length;j++){const a=points[j-1],b=points[j],d=b.map((v,k)=>v-a[k]),length=Math.hypot(...d);if(length<.01)continue;const dir=d.map(v=>v/length),q=[dir[2],0,-dir[0],1+dir[1]],norm=Math.hypot(...q);const e=box(a.map((v,k)=>(v+b[k])/2+(k===1?1.5:0)) as Vec3,[.09,length,.09],7,'滑索 '+i);world.set(e,Transform,{quat:norm>.0001?q.map(v=>v/norm) as [number,number,number,number]:[1,0,0,0]}).unwrap();}}
 function useZipline(){if(playerRide){playerRide=null;combat.notice('已脱离滑索');return true;}if(combat.dead||!match.scoringLive())return false;const p=pos(player),link=nav.links.find(l=>Math.hypot(...l.from.map((v,i)=>v-p[i]))<3.5);if(!link)return false;playerRide=[link.from,...link.route];combat.notice('滑索通行 · F 脱离');return true;}
 function updatePlayerRide(dt:number){if(!playerRide)return;if(combat.dead){playerRide=null;return;}const p=pos(player),goal=playerRide[0],d=goal.map((v,i)=>v-p[i]),distance=Math.hypot(...d);if(distance<.35){playerRide.shift();if(!playerRide.length)playerRide=null;}else physics.move(player.entity,d.map(v=>v/distance*Math.min(distance,9*dt)) as Vec3);combat.interacting=true;}
 for(const o of objectives){const p=o.position;markers.push({entity:box([p[0],p[1]+(mode==='core'?1.5:4),p[2]],mode==='core'?[3,3,3]:[.3,8,.3],o.owner==='enemy'?7:5,o.id),objective:o});}
 if(mode==='core')for(const marker of markers){world.addComponent(marker.entity,{component:RigidBody,data:{type:RigidBodyTypeValue.static}}).unwrap();world.addComponent(marker.entity,{component:Collider,data:{shape:ColliderShapeValue.cuboid,halfExtents:[1.5,1.5,1.5]}}).unwrap();}
 const spawnMarkers=coreSpawns.points.filter(p=>!p.fixed).map(point=>({point,owner:point.owner,entity:box([point.position[0],point.position[1]+1,point.position[2]],[.8,2,.8],point.owner==='ally'?5:7,point.id)}));
 for(const site of sites)box([site.position[0],site.position[1]+.08,site.position[2]],[10,.15,10],7,'包点 '+site.id);
 let bombMarker:EntityHandle|undefined;if(bomb){bombMarker=box([0,-50,0],[.45,.3,.55],7,'C4 炸弹');}
 function spawnPoint(team:Team,slot=0):Vec3 {let center=basePositions[team==='ally'?0:1];if(mode==='core'){const pads=coreSpawns.points.filter(p=>p.owner===team&&!p.contested);if(pads.length)center=pads[slot%pads.length].position;slot=Math.floor(slot/Math.max(1,pads.length));}if(mode==='demo')center=basePositions[team===match.attackerTeam?0:1];
  let candidates=(source.zones||[]).filter((z:any)=>teamless(mode)||z.team===team||!z.team).map((z:any)=>[z.x,z.y,z.z] as Vec3);
  if(mode==='conquest'){const flags=objectives.filter(o=>o.owner===team&&!o.contested);if(flags.length)center=flags[(slot+Math.floor(random()*flags.length))%flags.length].position;}
  if((mode==='tdm'||teamless(mode))&&candidates.length){const enemies=[player,...units].filter(u=>u.alive&&(teamless(mode)||u.team!==team));candidates=candidates.sort((a:Vec3,b:Vec3)=>{const safety=(p:Vec3)=>Math.min(120,...enemies.map(u=>Math.hypot(pos(u)[0]-p[0],pos(u)[2]-p[2])));return safety(b)-safety(a);});center=candidates[Math.floor(random()*Math.min(3,candidates.length))];}
  return nav.safe([center[0]+(slot%5-2)*2.5,center[1],center[2]+Math.floor(slot/5)*2.5],15);
 }
 function respawn(u:Unit,slot:number){const p=spawnPoint(u.team,slot);physics.teleport(u.entity,[p[0],p[1]+.9,p[2]]);u.hp=100;u.alive=true;world.set(u.entity,Collider,{isSensor:false}).unwrap();u.respawn=0;u.vy=0;u.path=[];u.think=random()*.3;u.protection=Number(params.spawnProtection)||1;world.set(u.visual!,Visibility,{state:VisibilityStateValue.visible}).unwrap();match.register(u);}
 const count=Number(params.teamSize)||32,number=teamless(mode)?Number(params.combatants)-1:count*2-1;
 for(let i=0;i<number;i++){const team:Team=i<count-1?'ally':'enemy',p=spawnPoint(team,i),entity=physics.character(p,'战术 AI '+i,4);owned.add(entity);const visual=world.spawn({component:ChildOf,data:{parent:entity}},{component:Transform,data:{pos:[0,-.9,0]}},{component:Visibility,data:{state:VisibilityStateValue.visible}},{component:MeshFilter,data:{assetHandle:models.get(team)!}},{component:MeshRenderer,data:{materials:[]}}).unwrap();owned.add(visual);
  const u:Unit={id:'bot-'+i,name:(team==='ally'?'阿尔法':'红方')+'-'+String(i+1).padStart(2,'0'),team,entity,visual,hp:100,alive:true,cooldown:0,protection:1,respawn:0,vy:0,think:random(),path:[],mission:'部署',target:null,weaponId:mode==='conquest'?'ak74':'ar',type:'infantry',mesh:{}};Object.defineProperty(u.mesh,'position',{get:()=>{const p=pos(u);return {x:p[0],y:p[1],z:p[2]};}});units.push(u);(team==='ally'?ai.blue:ai.red).push(u);}
 if(mode==='demo'){match.hooks={aliveCount:(team:Team)=>ai.aliveCount(team)+(team==='ally'&&!combat.dead?1:0),setupRound:()=>{units.forEach(respawn);const p=spawnPoint('ally');combat.respawn(p);physics.teleport(player.entity,[p[0],p[1]+.9,p[2]]);playerRespawn=0;},pickCarrier:(team:Team)=>team==='ally'?'player':units.find(u=>u.team===team)?.id};}
 match.start();for(const u of units)match.register(u);const p=spawnPoint('ally');combat.respawn(p);physics.teleport(player.entity,[p[0],p[1]+.9,p[2]]);
 if(mode==='core')for(const [i,o] of objectives.entries()){const p=nav.safe([o.position[0]-5,o.position[1],o.position[2]+8]);drops.push({entity:box([p[0],p[1]+.45,p[2]],[.5,.5,.5],7,'部署核'),position:p,core:true});}
 const friends=(a:any,b:any)=>!teamless(mode)&&a.team===b.team;
 function damage(target:any,amount:number,attacker:any,weaponId:string,headshot=false){if(!target.alive||!match.scoringLive()||friends(target,attacker)&&target!==attacker||target.protection>0||target.isPlayer&&combat.spawnProtection>0)return;
  if(target.isEquipment){combat.gear?.damage(target,amount);return;}target.lastHurt=combat.elapsed;if(target.isPlayer)combat.lastHurt=combat.elapsed;
   if(target.isPlayer){if(combat.classId==='juggernaut')amount*=.94;if(combat.shieldUntil>combat.elapsed&&combat.shieldHealth>0&&weaponId!=='explosive'&&attacker?.entity!==undefined&&(()=>{const a=physics.position(attacker.entity),p=physics.position(combat.playerBody);return (a[0]-p[0])*-Math.sin(combat.yaw)+(a[2]-p[2])*-Math.cos(combat.yaw)>0;})()){const absorbed=Math.min(combat.shieldHealth,amount);combat.shieldHealth-=absorbed;amount-=absorbed;}const absorb=Math.min(combat.armor,amount*.55);combat.armor-=absorb;amount-=absorb;match.registerDamage(player,Math.min(amount,combat.health),attacker);combat.health=Math.max(0,combat.health-amount);if(combat.health>0)return;combat.dead=true;playerRespawn=Number(params.respawnDelay)||5;}else{match.registerDamage(target,Math.min(amount,target.hp),attacker);target.hp=Math.max(0,target.hp-amount);if(target.hp>0)return;target.alive=false;world.set(target.entity,Collider,{isSensor:true}).unwrap();target.respawn=Number(params.respawnDelay)||5;world.set(target.visual,Visibility,{state:VisibilityStateValue.hidden}).unwrap();}
  if(bomb?.carrierId===target.id)bomb.drop({x:pos(target)[0],y:pos(target)[1],z:pos(target)[2]});if(bomb?.defuserId===target.id)bomb.cancelDefuse('阵亡');combat.onDeath?.(pos(target));match.registerKill({victim:target,killer:attacker,headshot,weaponId,maxHp:100});if(mode==='core'&&!target.isPlayer){const p=pos(target),core=random()<.3;drops.push({entity:box([p[0],p[1]+.45,p[2]],[.5,.5,.5],core?7:5,core?'部署核':'建材'),position:p,core});}
 }
 function interact(actor:any,held:boolean){if(!bomb||!match.scoringLive()||!actor.alive)return false;const p=pos(actor),id=actor.id;
  if(bomb.state==='dropped'&&actor.team===match.attackerTeam&&bomb.dropPos&&Math.hypot(p[0]-bomb.dropPos.x,p[1]-bomb.dropPos.y,p[2]-bomb.dropPos.z)<1.8)bomb.pickup(id);
  const site=sites.find((s:any)=>Math.hypot(p[0]-s.position[0],p[2]-s.position[2])<s.r&&Math.abs(p[1]-s.position[1])<3);
  if(bomb.carrierId===id){if(held&&site&&bomb.state==='carried')bomb.beginPlant(id,site.id,{pos:{x:p[0],y:p[1],z:p[2]}});if(bomb.state==='planting'&&(!held||!site))bomb.cancelPlant('离开包点');return bomb.state==='planting';}
  if(actor.team===match.defenderTeam&&bomb.plantPos){const range=Math.hypot(p[0]-bomb.plantPos.x,p[1]-bomb.plantPos.y,p[2]-bomb.plantPos.z);if(held&&range<=1.5&&bomb.state==='planted')bomb.beginDefuse(id,false);if(bomb.defuserId===id&&(!held||range>1.5))bomb.cancelDefuse('离开炸弹');return bomb.state==='defusing'&&bomb.defuserId===id;}return false;
 }
 function objectiveTarget(u:Unit):Vec3 {if(mode==='conquest'){const options=objectives.filter(o=>o.owner!==u.team||o.contested);const o=(options.length?options:objectives)[Number(u.id.slice(4))%(options.length||objectives.length)];u.mission='夺取 '+o.id;return o.position;}
  if(mode==='core'){const pads=coreSpawns.points.filter(p=>p.owner!==u.team&&!p.fixed);if(Number(u.id.slice(4))%3===0&&pads.length){u.mission='夺取前哨';return pads[Number(u.id.slice(4))%pads.length].position;}u.mission='攻击核心';return objectives.find(o=>o.owner!==u.team)!.position;}
  if(mode==='demo'){if(bomb.plantPos&&['planted','defusing'].includes(bomb.state)){u.mission=u.team===match.defenderTeam?'拆除炸弹':'防守炸弹';return [bomb.plantPos.x,bomb.plantPos.y,bomb.plantPos.z];}if(bomb.dropPos&&u.team===match.attackerTeam){u.mission='拾取炸弹';return [bomb.dropPos.x,bomb.dropPos.y,bomb.dropPos.z];}const site=sites[Number(u.id.slice(4))%Math.max(1,sites.length)];u.mission=bomb.carrierId===u.id?'安装炸弹':u.team===match.attackerTeam?'掩护进攻':'守卫包点';return site?.position||basePositions[1];}
  const foes=[player,...units,...(combat.deployables||[])].filter(x=>x!==u&&x.alive&&(!x.isPlayer||combat.stealthUntil<=combat.elapsed)&&!friends(x,u));foes.sort((a,b)=>Math.hypot(pos(a)[0]-pos(u)[0],pos(a)[2]-pos(u)[2])-Math.hypot(pos(b)[0]-pos(u)[0],pos(b)[2]-pos(u)[2]));u.mission='搜索敌人';return foes.length?pos(foes[0]):basePositions[1];
 }
 function visible(a:Vec3,b:Vec3){const d:Vec3=[b[0]-a[0],b[1]-a[1],b[2]-a[2]],distance=Math.hypot(...d);return !combat.gear?.blocksLine(a,b)&&!combat.map.raycast(a,d,Math.max(0,distance-.5));}
 function tickAI(u:Unit,dt:number){if(!u.alive){physics.around(physics.position(u.entity));if(mode!=='demo'){u.respawn-=dt;if(u.respawn<=0)respawn(u,Number(u.id.slice(4)));}return;}
  const status=aiThrowableStatus(combat.elapsed,u.blindUntil,u.stunUntil);
   if(u.target?.isPlayer&&combat.stealthUntil>combat.elapsed)u.target=null;u.protection=Math.max(0,u.protection-dt);u.cooldown=Math.max(0,u.cooldown-dt);const p=pos(u);u.think-=dt;
  if(u.think<=0){u.think=.45+random()*.35;const foes=[player,...units,...(combat.deployables||[])].filter(x=>x!==u&&x.alive&&!friends(x,u)&&(!x.isPlayer||combat.stealthUntil<=combat.elapsed));u.target=null;let closest=mode==='conquest'?110:65;for(const foe of foes){const q=pos(foe),d=Math.hypot(p[0]-q[0],p[2]-q[2]);if(d<closest&&visible([p[0],p[1]+1.5,p[2]],[q[0],q[1]+1.3,q[2]])){closest=d;u.target=foe;}}
   const objectiveAdvance=mode==='core'&&Number(u.id.slice(4))%3!==1;const goal=u.target&&!objectiveAdvance?pos(u.target):objectiveTarget(u);if(u.target&&!objectiveAdvance){u.mission=u.hp<30?'撤入掩体':'压制敌人';if(u.hp<30){goal[0]=p[0]+(p[0]-goal[0])*.7;goal[2]=p[2]+(p[2]-goal[2])*.7;}}
   if(!u.path.some(p=>p.transit)&&(!u.path.length||!u.goal||Math.hypot(u.goal[0]-goal[0],u.goal[2]-goal[2])>6)){u.path=nav.path(p,goal);u.goal=[...goal];}
  }
  const interacting=interact(u,true);if(interacting)u.mission=bomb.state==='planting'?'正在安装':'正在拆除';
  if(mode==='core'&&!interacting&&status.canShoot){const core=objectives.find(o=>o.owner!==u.team)!;if(Math.hypot(p[0]-core.position[0],p[2]-core.position[2])<24&&u.cooldown===0&&visible([p[0],p[1]+1.5,p[2]],[core.position[0],core.position[1]+1.5,core.position[2]])){match.damageCore(core.owner,18,u.team);u.cooldown=.8;}}
  if(!interacting&&status.canShoot&&u.target?.alive&&u.cooldown===0){const q=pos(u.target);if(visible([p[0],p[1]+1.5,p[2]],[q[0],q[1]+1.3,q[2]])){const wid=mode==='gungame'?match.weaponAt(match.register(u).level):u.weaponId,w=weaponsFor(mode)[wid];u.cooldown=Math.max(.24,Number(w?.fireRate)||.5);combat.sound?.(wid,[p[0],p[1]+1.5,p[2]]);if(random()<aiHitChance(Math.hypot(p[0]-q[0],p[1]-q[1],p[2]-q[2]),u.path.length>0,w?.category))damage(u.target,Number(w?.damage)||22,u,wid);}}

  let dx=0,dz=0;const waypoint=u.path[0];
  if(waypoint?.transit&&!interacting){const delta=waypoint.map((v,i)=>v-p[i]),distance=Math.hypot(...delta);if(distance<.35)u.path.shift();else{const moved=physics.move(u.entity,delta.map(v=>v/distance*Math.min(distance,9*dt*status.move)) as Vec3);u.stuck=Math.hypot(...moved)<.005?(u.stuck||0)+dt:0;if(u.stuck>1.5){u.path=[];u.goal=undefined;u.think=0;u.stuck=0;}}u.vy=0;u.mission='使用滑索';return;}if(waypoint&&!interacting&&!(u.mission==='夺取前哨'&&u.goal&&Math.hypot(p[0]-u.goal[0],p[2]-u.goal[2])<8&&Math.abs(p[1]-u.goal[1])<3)){const d=Math.hypot(waypoint[0]-p[0],waypoint[2]-p[2]);if(d<.45)u.path.shift();else if(!u.target||u.hp<30||d>0){const speed=(mode==='conquest'?6:4.5)*status.move;dx=(waypoint[0]-p[0])/d*speed*dt;dz=(waypoint[2]-p[2])/d*speed*dt;}}
  u.vy=physics.grounded(u.entity)?(waypoint&&(waypoint.jump||waypoint[1]>p[1]+.4)?7:-1):Math.max(-25,u.vy-18*dt);const moved=physics.move(u.entity,[dx,u.vy*dt,dz]);u.stuck=Math.hypot(dx,dz)>.005&&Math.hypot(moved[0],moved[2])<.005?(u.stuck||0)+dt:0;if(u.stuck>1.5){u.path=[];u.goal=undefined;u.think=0;u.stuck=0;}if(dx||dz){const yaw=Math.atan2(-dx,-dz);u.yaw=yaw;world.set(u.visual!,Transform,{quat:[0,Math.sin(yaw/2),0,Math.cos(yaw/2)]}).unwrap();}
 }
 function update(dt:number){if(closed)return;for(let i=timers.length-1;i>=0;i--)if(timers[i].at<=combat.elapsed){const t=timers.splice(i,1)[0];t.fn();}combat.spawnProtection=Math.max(0,combat.spawnProtection-dt);match.update(dt);if(closed)return;
  for(const u of units)physics.around(physics.position(u.entity));if(!match.scoringLive())return;if(mode==='core'&&combat.keys.has('KeyE')){const p=pos(player);for(let i=drops.length-1;i>=0;i--)if(Math.hypot(...drops[i].position.map((n,j)=>n-p[j]))<2.5){const d=drops.splice(i,1)[0];if(d.core)combat.buildCores++;else combat.buildBlocks+=2;world.despawn(d.entity).unwrap();owned.delete(d.entity);combat.notice(d.core?'+1 部署核':'+2 掩体建材');break;}}combat.interacting=interact(player,combat.keys.has('KeyE'));if(bomb&&combat.keys.has('KeyZ')&&bomb.carrierId==='player'){const p=pos(player);bomb.drop({x:p[0],y:p[1],z:p[2]});combat.keys.delete('KeyZ');}
  if(combat.dead&&mode!=='demo'){playerRespawn=Math.max(0,playerRespawn-dt);if(!playerRespawn){const p=spawnPoint('ally');combat.respawn(p);physics.teleport(player.entity,[p[0],p[1]+.9,p[2]]);combat.spawnProtection=1.5;}}
  nav.obstacles=((combat as any).vehicles?.vehicles||[]).filter((v:any)=>v.hp>0).map((v:any)=>{const p=physics.position(v.entity),h=world.get(v.entity,Collider).unwrap().halfExtents;return {min:p.map((n,i)=>n-h[i]) as Vec3,max:p.map((n,i)=>n+h[i]) as Vec3};});updatePlayerRide(dt);for(const u of units)tickAI(u,dt);if(mode==='core'){coreSpawns.update(dt,[player,...units].map(u=>({team:u.team,position:pos(u),alive:u.alive})));for(const marker of spawnMarkers)if(marker.owner!==marker.point.owner){world.despawn(marker.entity).unwrap();owned.delete(marker.entity);marker.owner=marker.point.owner;const p=marker.point.position;marker.entity=box([p[0],p[1]+1,p[2]],[.8,2,.8],marker.owner==='ally'?5:7,marker.point.id);}}if(mode==='conquest')match.occupy(dt,[player,...units].map(u=>({id:u.id,name:u.name,isPlayer:u.isPlayer,team:u.team,position:pos(u),alive:u.alive})));
  if(bombMarker!==undefined){const b=bomb.dropPos||bomb.plantPos;world.set(bombMarker,Transform,{pos:b?[b.x,b.y+.3,b.z]:[0,-50,0]}).unwrap();}
 }
 function hit(origin:Vec3,direction:Vec3,range:number,amount:number,weaponId:string){let nearest=range,target:Unit|undefined,headshot=false;for(const u of units){if(!u.alive||friends(player,u))continue;const p=pos(u),center:Vec3=[p[0],p[1]+1,p[2]],v=center.map((n,i)=>n-origin[i]),t=v.reduce((sum,n,i)=>sum+n*direction[i],0);if(t<0||t>=nearest)continue;const q=origin.map((n,i)=>n+direction[i]*t);if(Math.hypot(q[0]-p[0],q[2]-p[2])<.55&&q[1]>p[1]&&q[1]<p[1]+1.9){nearest=t;target=u;headshot=q[1]>p[1]+1.5;}}
  if(target){damage(target,amount*(headshot?1.6:1),player,weaponId,headshot);return nearest;}if(mode==='core'){for(const o of objectives){const p=o.position,t=(p[0]-origin[0])*direction[0]+(p[1]+1.5-origin[1])*direction[1]+(p[2]-origin[2])*direction[2];if(t>0&&t<range&&Math.hypot(origin[0]+direction[0]*t-p[0],origin[1]+direction[1]*t-p[1]-1.5,origin[2]+direction[2]*t-p[2])<2.2){match.damageCore(o.owner,amount,'ally');return t;}}}return null;
 }
 function blast(p:Vec3,radius:number,damageAmount:number,team:Team='ally'){combat.gear?.damageArea(p,radius,damageAmount);combat.explosionSound?.(p);for(const u of [player,...units]){const q=pos(u),d=Math.hypot(q[0]-p[0],q[1]-p[1],q[2]-p[2]);if(d<radius&&!combat.map.raycast(p,[q[0]-p[0],q[1]+1-p[1],q[2]-p[2]],Math.max(0,Math.hypot(q[0]-p[0],q[1]+1-p[1],q[2]-p[2])-.5)))damage(u,damageAmount*(1-d/radius),team==='ally'?player:{id:'vehicle-enemy',name:'敌方载具',team},'explosive');}for(let x=Math.floor(p[0]-radius);x<=p[0]+radius;x++)for(let z=Math.floor(p[2]-radius);z<=p[2]+radius;z++)for(let y=Math.floor(p[1]-radius);y<=p[1]+radius;y++)if(Math.hypot(x-p[0],y-p[1],z-p[2])<radius*.6)combat.map.breakBlock(x,y,z,true);}
 function hint(){const p=pos(player);if(playerRide)return '滑索通行 · F 脱离';const pad=coreSpawns.points.find(point=>point.capture>0&&Math.hypot(point.position[0]-p[0],point.position[2]-p[2])<12);if(pad)return '占领前哨 '+pad.id+' · '+Math.floor(pad.capture)+' / 20 秒';if(nav.links.some(l=>Math.hypot(...l.from.map((v,i)=>v-p[i]))<3.5))return 'F 使用滑索';if(mode==='demo'){const nearest=sites.map((s:any)=>s.id+' '+Math.round(Math.hypot(p[0]-s.position[0],p[2]-s.position[2]))+'m').join(' / ');return '回合 '+match.round+' · '+(match.attackerTeam==='ally'?'进攻':'防守')+' · '+nearest+' · '+(bomb.carrierId==='player'?'携带 C4：包点按住 E 安装，Z 丢弃':bomb.state==='planted'||bomb.state==='defusing'?'C4 '+Math.ceil(bomb.remaining)+' 秒 · 靠近按住 E 拆除':bomb.state==='planting'?'安装 '+Math.round(bomb.plantProgress/Number(params.plantTime||4)*100)+'%':'炸弹 '+bomb.state);}
  return objectives.map(o=>o.id+' '+(mode==='core'?Math.ceil(o.hp):o.contested?'争夺':o.owner==='ally'?'我方':o.owner==='enemy'?'敌方':'中立')+' · '+Math.round(Math.hypot(p[0]-o.position[0],p[2]-o.position[2]))+'m').join('  |  ');
 }
 return {bases:source.bases.map((p:any)=>nav.safe([p.x,p.y??combat.map.walkHeight(p.x,p.z),p.z],12)),update,hit,blast,match,ai,env,physics,objectives,bomb,nav,coreSpawns,player,units,damage,position:pos,hint,dispose,useZipline,get traversingPlayer(){return !!playerRide;},spawn:{respawnLeft:()=>playerRespawn},get counts(){return [ai.aliveCount('ally')+(!combat.dead?1:0),ai.aliveCount('enemy')];},get squadCounts(){return [ai.aliveCount('ally'),ai.aliveCount('enemy')];}};
 }catch(e){dispose();throw e;}
}
