import type {World,EntityHandle} from '@forgeax/engine/ecs';
import {Transform,ChildOf} from '@forgeax/engine/scene';
import {MeshFilter,MeshRenderer,Visibility,VisibilityStateValue} from '@forgeax/engine/render';
import {Collider,RigidBody,RigidBodyTypeValue,ColliderShapeValue} from '@forgeax/engine/physics';
import {createBoxGeometry} from '@forgeax/engine/geometry';
import type {Handle} from '@forgeax/engine/types';
import type {BattleState} from './battle.plugin.ts';
import type {Vec3} from './voxel-map.ts';
export function createSkills(world:World,b:BattleState){const owned=new Set<EntityHandle>(),handles:Handle<'MeshAsset','shared'>[]=[],zones:{p:Vec3;left:number;entity:EntityHandle}[]=[];let pending=false,turret:any=null,sequence=0,shield:EntityHandle|undefined;
 function box(p:Vec3,size:Vec3,parent?:EntityHandle){const mesh={...createBoxGeometry(...size).unwrap(),materialSlots:[{slotName:'body',defaultMaterial:b.material(5)}]},h=world.allocSharedRef('MeshAsset',mesh);handles.push(h);const components:any[]=[{component:Transform,data:{pos:p}},{component:Visibility,data:{state:VisibilityStateValue.visible}},{component:MeshFilter,data:{assetHandle:h}},{component:MeshRenderer,data:{materials:[]}}];if(parent!==undefined)components.push({component:ChildOf,data:{parent}});const entity=world.spawn(...components).unwrap();owned.add(entity);return entity;}
 function remove(entity:EntityHandle){if(owned.delete(entity))world.despawn(entity).unwrap();}
 function ground(distance=5):Vec3{const p=b.physics.position(b.playerBody);return b.arena!.nav.safe([p[0]-Math.sin(b.yaw)*distance,p[1]-.9,p[2]-Math.cos(b.yaw)*distance],8);}
 function summonTurret(){if(b.buildBlocks<12){b.notice='需要 12 份物料部署炮塔';b.noticeLeft=3;return;}const p=ground(),entity=box([p[0],p[1]+.6,p[2]],[.8,1.2,.8]);world.addComponent(entity,{component:RigidBody,data:{type:RigidBodyTypeValue.static}}).unwrap();world.addComponent(entity,{component:Collider,data:{shape:ColliderShapeValue.cuboid,halfExtents:[.4,.6,.4]}}).unwrap();turret={id:'turret-'+(++sequence),name:'友方加特林',team:'ally',entity,visual:entity,hp:120,alive:true,ammo:120,cooldown:0};b.deployables.push(turret);b.buildBlocks-=12;b.skillCooldown=40;}
 function activate(){if(b.dead||!b.arena?.match.scoringLive())return;if(b.classId==='engineer'&&turret){turret.alive=false;remove(turret.entity);b.deployables=b.deployables.filter(x=>x!==turret);turret=null;b.buildBlocks+=6;b.notice='炮塔已收回 · 返还 6 份物料';b.noticeLeft=3;return;}if(b.mode!=='conquest'&&b.classId==='vanguard'){b.gear?.selectSkillCharge();return;}if(b.skillCooldown>0)return;if(b.mode==='conquest'){if(b.grenades>0){b.grenades--;b.ordnance?.throwGrenade();}return;}
  if(['medic','engineer'].includes(b.classId)){pending=true;b.notice='松开 G 部署 '+(b.classId==='medic'?'修复装置':'加特林炮塔');b.noticeLeft=10;return;}
  if(b.classId==='ghost'){b.stealthUntil=b.elapsed+6;b.bonusShot=40;b.skillCooldown=28;}
  else if(b.classId==='juggernaut'){b.shieldUntil=b.elapsed+8;b.shieldHealth=280;b.skillCooldown=24;if(shield!==undefined)remove(shield);shield=world.spawn({component:ChildOf,data:{parent:b.camera}},{component:Transform,data:{pos:[0,-.2,-1.5]}}).unwrap();owned.add(shield);box([-.5,0,0],[.28,1.5,.12],shield);box([.5,0,0],[.28,1.5,.12],shield);box([0,-.5,0],[.8,.6,.12],shield);box([0,.65,0],[.8,.2,.12],shield);}
  else if(b.classId==='raider'){const p=b.physics.position(b.playerBody),forward=[-Math.sin(b.yaw),-Math.cos(b.yaw)];for(let x=Math.floor(p[0]-28);x<=p[0]+28;x++)for(let z=Math.floor(p[2]-28);z<=p[2]+28;z++){const dx=x-p[0],dz=z-p[2],distance=Math.hypot(dx,dz);if(distance<1||distance>28||(dx*forward[0]+dz*forward[1])/distance<.866)continue;for(let y=Math.floor(p[1]-2);y<p[1]+5;y++)b.map.breakBlock(x,y,z,true);}for(const o of b.arena.objectives){const dx=o.position[0]-p[0],dz=o.position[2]-p[2],distance=Math.hypot(dx,dz);if(o.owner==='enemy'&&distance<28&&(dx*forward[0]+dz*forward[1])/distance>.866)b.arena.match.damageCore?.('enemy',180,'ally');}b.vehicles?.hit([p[0],p[1]+.8,p[2]],[-Math.sin(b.yaw),0,-Math.cos(b.yaw)],28,150);b.skillCooldown=30;}
  b.notice='技能已启动';b.noticeLeft=2;
 }
 function release(){if(!pending)return;pending=false;if(b.dead||!b.arena?.match.scoringLive())return;if(b.classId==='medic'){const p=ground();zones.push({p,left:8,entity:box([p[0],p[1]+.2,p[2]],[.8,.4,.8])});b.skillCooldown=15;}else if(b.classId==='engineer')summonTurret();b.noticeLeft=0;}
 function update(dt:number){if(pending&&!b.keys.has('KeyG'))release();if(shield!==undefined&&(b.shieldUntil<=b.elapsed||b.shieldHealth<=0||b.dead)){for(const e of [...owned]){const r=world.get(e,ChildOf);if(r.ok&&r.value.parent===shield)remove(e);}remove(shield);shield=undefined;}
  for(let i=zones.length-1;i>=0;i--){const z=zones[i];z.left-=dt;if(z.left<=0){remove(z.entity);zones.splice(i,1);continue;}const p=b.physics.position(b.playerBody);if(!b.dead&&Math.hypot(p[0]-z.p[0],p[2]-z.p[2])<8){b.health=Math.min(100,b.health+12*dt);b.armor=Math.min(100,b.armor+8*dt);}for(const u of b.arena!.units)if(u.alive&&u.team==='ally'){const p=b.arena!.position(u);if(Math.hypot(p[0]-z.p[0],p[2]-z.p[2])<8)u.hp=Math.min(100,u.hp+12*dt);}}
  if(turret){if(!turret.alive){remove(turret.entity);b.deployables=b.deployables.filter(x=>x!==turret);turret=null;return;}turret.cooldown=Math.max(0,turret.cooldown-dt);if(!turret.cooldown&&turret.ammo>0){const p=b.physics.position(turret.entity);for(const u of b.arena!.units){if(!u.alive||u.team==='ally')continue;const q=b.arena!.position(u),d:Vec3=[q[0]-p[0],q[1]+1.2-p[1],q[2]-p[2]],len=Math.hypot(...d);if(len>45||b.map.raycast(p,d,len-.6))continue;b.arena!.damage(u,9,turret,'gatling');turret.ammo--;turret.cooldown=1;break;}}}
 }
 return {activate,release,update,hint:()=>b.skillCooldown>0?'技能冷却 '+Math.ceil(b.skillCooldown)+'s':pending?'松开 G 部署':'G 兵种技能',dispose(){pending=false;for(const e of [...owned])remove(e);for(const h of handles)world.sharedRefs.release(h).unwrap();handles.length=0;b.deployables.length=0;}};
}
