import type {World,EntityHandle} from '@forgeax/engine/ecs';
import {Transform,ChildOf,Name} from '@forgeax/engine/scene';
import {MeshFilter,MeshRenderer,Visibility,VisibilityStateValue} from '@forgeax/engine/render';
import {Collider,RigidBody,RigidBodyTypeValue,ColliderShapeValue} from '@forgeax/engine/physics';
import {createBoxGeometry} from '@forgeax/engine/geometry';
import type {Handle} from '@forgeax/engine/types';
import type {BattleState} from './battle.plugin.ts';
import type {EquipmentAssets} from './native-equipment.ts';
import type {Vec3} from './voxel-map.ts';
import {vehicleDefs} from '../original/vehicle-rules.ts';
import {CLASS_SKILLS as R,classArmor,distance,empCarve,rearShot,skillPlacement,weaponClassSpeed} from './class-skill-rules.ts';
import {teamless} from './catalog.ts';
import {quatXYZ} from './melee-rules.ts';

type Turret={id:string;name:string;team:'ally';entity:EntityHandle;visual:EntityHandle;hp:number;alive:boolean;ammo:number;cooldown:number;isSkill:true;position:Vec3;head:EntityHandle;barrels:EntityHandle;yaw:number;roll:number};
type HealZone={position:Vec3;life:number;entity:EntityHandle;ring:EntityHandle};
export function createSkills(world:World,b:BattleState,assets:EquipmentAssets=new Map()){
 const owned=new Set<EntityHandle>(),handles:Handle<'MeshAsset','shared'>[]=[],zones:HealZone[]=[],fx:{entity:EntityHandle;life:number;duration:number;expand:boolean}[]=[],marks:{id:string;position:Vec3;life:number}[]=[];
 let pending=false,preview:EntityHandle|undefined,turret:Turret|null=null,shield:EntityHandle|undefined,sequence=0,closed=false,wasDead=b.dead,stim=0,stealthed=false;
 let held=false,channel:'revive'|'repair'|null=null,channelTarget:any=null,progress=0,repairFx=0,lastMark=-Infinity,dashLeft=0,dashCooldown=0,dashDir:Vec3=[0,0,0],dashTravel=0,dashFrames=0,kick=0,dashMoved=false,carry:Vec3=[0,0,0];
 const tally={healedSelf:0,healedAllies:0,repaired:0,revives:0,turretShots:0,empBroken:0,shieldAbsorbed:0,ambushHits:0,rearHits:0};
 const notice=(s:string)=>{b.notice=s;b.noticeLeft=3;};
 const feet=():Vec3=>{const p=b.physics.position(b.playerBody);return [p[0],p[1]-.9,p[2]];};
 const look=():Vec3=>[-Math.sin(b.yaw)*Math.cos(b.pitch),Math.sin(b.pitch),-Math.cos(b.yaw)*Math.cos(b.pitch)];
 const live=()=>!closed&&!b.dead&&!b.vehicles?.seated&&!b.inspect?.blocksInput&&!!b.arena?.match.scoringLive();
 const cube=world.allocSharedRef('MeshAsset',{...createBoxGeometry(1,1,1).unwrap(),materialSlots:[{slotName:'skill',defaultMaterial:b.material(5)}]});handles.push(cube);
 function node(p:Vec3,key?:string,parent?:EntityHandle,size?:Vec3){const components:any[]=[{component:Transform,data:{pos:p,...(size?{scale:size}:{})}},{component:Name,data:{value:key||'技能表现'}},{component:Visibility,data:{state:VisibilityStateValue.visible}}];if(key)components.push({component:MeshFilter,data:{assetHandle:assets.get(key)||cube}},{component:MeshRenderer,data:{materials:[]}});if(parent!==undefined)components.push({component:ChildOf,data:{parent}});const e=world.spawn(...components).unwrap();owned.add(e);return e;}
 function remove(e:EntityHandle|undefined){if(e===undefined||!owned.has(e))return;for(const child of [...owned]){const p=world.get(child,ChildOf);if(p.ok&&p.value.parent===e)remove(child);}owned.delete(e);world.despawn(e).unwrap();}
 function ring(p:Vec3,radius:number){const root=node(p);for(let i=0;i<32;i++){const a=i/32*Math.PI*2,e=node([Math.cos(a)*radius,0,Math.sin(a)*radius],'skill/fx',root,[.07,.045,radius*.2]);world.set(e,Transform,{quat:quatXYZ(0,-a,0)}).unwrap();}return root;}
 function pulse(p:Vec3,radius=1,life=.4){const e=ring(p,radius);fx.push({entity:e,life,duration:life,expand:true});}
 function beam(a:Vec3,c:Vec3,life=.075){const d=c.map((v,i)=>v-a[i]) as Vec3,len=Math.hypot(...d);if(len<.01)return;const e=node(a.map((v,i)=>(v+c[i])/2) as Vec3,'skill/fx',undefined,[.025,len,.025]),n=d.map(v=>v/len),q=[n[2],0,-n[0],1+n[1]],mag=Math.hypot(...q);world.set(e,Transform,{quat:mag>.001?q.map(v=>v/mag) as [number,number,number,number]:[1,0,0,0]}).unwrap();fx.push({entity:e,life,duration:life,expand:false});}
 function dropTurret(){if(!turret)return;turret.alive=false;remove(turret.entity);b.deployables=b.deployables.filter(x=>x!==turret);turret=null;}
 function clearShield(){remove(shield);shield=undefined;b.shieldUntil=0;b.shieldHealth=0;}
 function cancel(){pending=false;remove(preview);preview=undefined;held=false;channel=null;channelTarget=null;progress=0;dashLeft=0;carry=[0,0,0];}
 function breakStealth(silent=false){const was=stealthed||b.stealthUntil>b.elapsed;stealthed=false;b.stealthUntil=0;if(was&&!silent){b.bonusShot=40;b.audio?.play('stealth_off');notice('隐身结束 · 下一次命中步兵 +40');}}
 function reset(){cancel();stim=0;breakStealth(true);b.bonusShot=0;clearShield();dropTurret();for(const z of zones){remove(z.entity);remove(z.ring);}zones.length=0;for(const f of fx)remove(f.entity);fx.length=0;marks.length=0;dashCooldown=0;b.skillCooldown=0;b.speedBoostUntil=0;dashTravel=0;dashFrames=0;}
 function spawnLife(){reset();b.armor=classArmor(b.mode,b.classId);b.buildBlocks=b.classId==='engineer'?20:8;wasDead=false;}
 function beginChannel(kind:'revive'|'repair'){cancel();b.gear?.cancel();held=true;b.noticeLeft=0;channel=kind;channelTarget=findChannelTarget();if(!channelTarget){cancel();notice(kind==='revive'?'2.8 米内没有可救援队友':'5 米内没有友方载具');return;}b.firing=false;b.ads=false;b.reload=0;}
 function findChannelTarget():any{const p=feet();if(channel==='revive')return (b.arena?.downed||[]).filter(s=>s.target.team==='ally'&&s.target!==b.arena!.player&&distance(p,b.arena!.position(s.target))<R.revive.range).sort((a,c)=>distance(p,b.arena!.position(a.target))-distance(p,b.arena!.position(c.target)))[0];
 return b.vehicles?.vehicles.filter(v=>v.hp>0&&v.team==='ally'&&distance(p,vehicleFeet(v))<=R.repair.range).sort((a,c)=>distance(p,vehicleFeet(a))-distance(p,vehicleFeet(c)))[0];}
 const vehicleFeet=(v:NonNullable<BattleState['vehicles']>['vehicles'][number]):Vec3=>{const p=b.physics.position(v.entity);return [p[0],p[1]-vehicleDefs[v.type].size.y/2,p[2]];};
 function place(){return skillPlacement(b.map,feet(),look(),b.classId==='engineer');}
 function activate(){if(!live())return false;
  if(b.mode==='conquest'){
   if(b.classId==='assault'){if(b.skillCooldown>0||stim>0)return false;if(b.health>=100){notice('生命已满');return false;}stim=1;b.skillCooldown=60;b.audio?.play('build');notice('战斗兴奋剂 · 快速恢复生命');return true;}
   if(b.classId==='support'){beginChannel('revive');return held;}
   if(b.classId==='engineer'){beginChannel('repair');return held;}
   notice('对准敌人按 Q · 强化标记 5 秒');return false;
  }
  if(b.classId==='vanguard')return b.gear?.selectSkillCharge()??false;
  if(b.classId==='engineer'&&turret){dropTurret();b.buildBlocks+=8;b.skillCooldown=Math.min(b.skillCooldown>0?b.skillCooldown:8,8);b.audio?.play('build');notice('炮塔已收回 · 返还 8 份物料');return true;}
  if(b.skillCooldown>0)return false;
  if(b.classId==='medic'||b.classId==='engineer'){if(b.classId==='engineer'&&b.buildBlocks<12){notice('需要 12 份物料部署炮塔');return false;}cancel();b.gear?.cancel();b.building?.cancel();pending=true;b.noticeLeft=0;updatePreview();return true;}
  if(b.classId==='ghost'){stealthed=true;b.bonusShot=0;b.stealthUntil=b.elapsed+6;b.skillCooldown=28;b.audio?.play('stealth_on');notice('隐身 · 6 秒 / 移速提升');return true;}
  if(b.classId==='juggernaut'){clearShield();b.shieldUntil=b.elapsed+8;b.shieldHealth=280;b.skillCooldown=24;shield=node([0,0,0],'skill/shield');b.audio?.play('shield_on');notice('防暴盾 · 正面吸收伤害');return true;}
  if(b.classId==='raider'){const result=empCarve(b.map,b.physics.position(b.camera),look(),b.mode==='core'?b.arena?.bases?.[0]:undefined);b.broken+=result.broken;tally.empBroken+=result.broken;b.skillCooldown=30;beam(b.physics.position(b.camera),result.impact,.25);pulse(result.impact,2,.5);b.audio?.play('emp');if(result.broken)b.arena?.salvage?.(result.impact,result.broken);notice('电磁脉冲 · 摧毁 '+result.broken+' 方块');return true;}
  return false;
 }
 function updatePreview(){if(!pending)return;const p=place();if(!p){remove(preview);preview=undefined;notice('无有效部署位置');return;}if(preview===undefined)preview=node(p,'skill/'+(b.classId==='medic'?'healer':'turret')+'-preview');else world.set(preview,Transform,{pos:p}).unwrap();}
 function release(){if(b.mode==='conquest'){held=false;channel=null;channelTarget=null;progress=0;return;}if(!pending)return;const p=place();pending=false;remove(preview);preview=undefined;if(!live()||b.skillCooldown>0||!p)return;
  if(b.classId==='medic'){for(const z of zones){remove(z.entity);remove(z.ring);}zones.length=0;zones.push({position:p,life:8,entity:node(p,'skill/healer'),ring:ring([p[0],p[1]+.01,p[2]],5.5)});b.skillCooldown=15;notice('修复装置 · 8 秒 / 5.5 米');}
  else if(b.classId==='engineer'){if(b.buildBlocks<12)return;const entity=node([p[0],p[1]+.7,p[2]]),base=node([0,-.7,0],'skill/turret-base',entity),head=node([0,.45,0],'skill/turret-head',entity),barrels=node([0,0,.45],'skill/turret-barrels',head);world.addComponent(entity,{component:RigidBody,data:{type:RigidBodyTypeValue.static}}).unwrap();world.addComponent(entity,{component:Collider,data:{shape:ColliderShapeValue.cuboid,halfExtents:[.6,.7,.6]}}).unwrap();turret={id:'turret-'+(++sequence),name:'友方加特林',team:'ally',entity,visual:base,hp:120,alive:true,ammo:120,cooldown:.35,isSkill:true,position:p,head,barrels,yaw:0,roll:0};b.deployables.push(turret);b.buildBlocks-=12;b.skillCooldown=40;notice('加特林炮塔 · G 收回返还 8 份物料');}
  b.audio?.play('build',p);
 }
 function incoming(amount:number,from?:Vec3){if(b.mode==='conquest')return amount;if(b.classId==='ghost'&&b.stealthUntil>b.elapsed)return 0;if(b.classId!=='juggernaut')return amount;amount*=.94;
  if(b.shieldUntil<=b.elapsed||b.shieldHealth<=0)return amount;
  if(from){const p=feet(),x=from[0]-p[0],z=from[2]-p[2],len=Math.hypot(x,z);if(len>.05&&(-Math.sin(b.yaw)*x-Math.cos(b.yaw)*z)/len<.2)return amount;}
  const absorbed=Math.min(amount,b.shieldHealth);b.shieldHealth-=absorbed;tally.shieldAbsorbed+=absorbed;if(absorbed)b.audio?.play('shield_hit');if(b.shieldHealth<=0){clearShield();b.audio?.play('shield_break');notice('防暴盾破碎');}return amount-absorbed;
 }
 function outgoing(amount:number,target:any){if(b.classId!==(b.mode==='conquest'?'recon':'ghost'))return amount;let result=Math.max(0,amount|0);if(rearShot(feet(),b.arena!.position(target),target.yaw||0)){result=Math.round(result*1.3);tally.rearHits++;}if(b.bonusShot>0){result+=40;b.bonusShot=0;tally.ambushHits++;}return result;}
 function damage(target:any,amount:number){if(target!==turret||!turret?.alive)return false;turret.hp=Math.max(0,turret.hp-amount);if(!turret.hp){pulse(turret.position);dropTurret();notice('炮塔已被摧毁');}return true;}
 function mark(){if(!live()||b.mode!=='conquest'||b.building?.active||b.elapsed-lastMark<.4)return false;const origin=b.physics.position(b.camera),dir=look(),wall=b.map.raycast(origin,dir,160),limit=wall?.distance??160,unit=b.arena?.raycast(origin,dir,limit),vehicle=b.vehicles?.raycast(origin,dir,limit);let target:any=unit?.kind==='unit'?unit.target:null;if(vehicle&&(!unit||vehicle.distance<unit.distance))target=vehicle.vehicle;if(!target){notice('对准敌人后按 Q 标记');return false;}const p=target.type&&vehicle?.vehicle===target?b.physics.position(target.entity):b.arena!.position(target),life=b.classId==='recon'?5:1;target.spottedUntil=b.elapsed+life;marks.push({id:target.id,position:[...p],life});lastMark=b.elapsed;pulse([p[0],p[1]+.1,p[2]],.85,life);notice(life===5?'强化标记 · 5 秒':'已标记敌军 · 1 秒');return true;}
 function dash(){if(!live()||dashCooldown>0||dashLeft>0||b.arena?.traversingPlayer||channel)return false;cancel();b.gear?.cancel();dashDir=look();dashLeft=.2;dashCooldown=5;dashTravel=0;dashFrames=0;kick=9;b.velocityY=0;b.keys.delete('ControlLeft');const p=b.physics.position(b.playerBody);for(let t=0;t<=30;t+=8)b.physics.around(p.map((v,i)=>v+dashDir[i]*t) as Vec3);b.audio?.play('dash');return true;}
 function update(dt:number){if(closed)return;dashMoved=false;carry=carry.map(v=>v*Math.exp(-8*dt)) as Vec3;dashCooldown=Math.max(0,dashCooldown-dt);kick=Math.max(0,kick-dt*22);
  for(let i=fx.length-1;i>=0;i--){const f=fx[i];f.life-=dt;if(f.life<=0){remove(f.entity);fx.splice(i,1);}else if(f.expand){const scale=1+(1-f.life/f.duration)*.25;world.set(f.entity,Transform,{scale:[scale,1,scale]}).unwrap();}}
  for(let i=marks.length-1;i>=0;i--)if((marks[i].life-=dt)<=0)marks.splice(i,1);
  if(b.dead){if(!wasDead)reset();wasDead=true;return;}wasDead=false;if(!b.arena?.match.scoringLive())return;
  if(stealthed&&b.stealthUntil<=b.elapsed)breakStealth();if(stim>0){const n=Math.min(stim,dt);stim-=n;const before=b.health;b.health=Math.min(100,b.health+100*n);tally.healedSelf+=b.health-before;if(b.health===100)stim=0;}
  if(pending)updatePreview();
  if(held&&channel){if(!b.keys.has('KeyX')||!live()){release();}else{const target=findChannelTarget();if(target!==channelTarget){channelTarget=target;progress=0;}if(target){b.interacting=true;b.firing=false;b.ads=false;if(channel==='revive'){progress+=dt;if(progress>=3){if(b.arena!.revive(target,50)){tally.revives++;notice('队友已复活 · 50 生命');b.audio?.play('build');}release();}}else{const max=vehicleDefs[target.type as keyof typeof vehicleDefs].maxHp,before=target.hp;target.hp=Math.min(max,target.hp+10*dt);tally.repaired+=target.hp-before;repairFx-=dt;if(repairFx<=0&&target.hp<max){repairFx=.12;beam(b.physics.position(b.camera),b.physics.position(target.entity),.09);}}}}}
  if(dashLeft>0){dashMoved=true;const n=Math.min(dt,dashLeft),p=b.physics.position(b.playerBody),request=dashDir.map((v,i)=>Math.max(i===1?-1.1:1,Math.min(i===1?120.9:b.map.width-1,p[i]+v*150*n))-p[i]) as Vec3;for(let t=0;t<=30;t+=8)b.physics.around(p.map((v,i)=>v+dashDir[i]*t) as Vec3);const moved=b.physics.move(b.playerBody,request);dashTravel+=Math.hypot(...moved);dashLeft=Math.max(0,dashLeft-n);dashFrames++;b.interacting=true;if(dashFrames%2===0)pulse([p[0],p[1]-.6,p[2]],.3,.18);if(Math.hypot(...moved)<.005)dashLeft=0;if(!dashLeft){b.velocityY=dashDir[1]*4;carry=[dashDir[0]*6,0,dashDir[2]*6];}}
  if(shield!==undefined){if(b.shieldUntil<=b.elapsed||b.shieldHealth<=0)clearShield();else{const p=feet();world.set(shield,Transform,{pos:[p[0]-Math.sin(b.yaw)*1.35,p[1]+2.2*.42,p[2]-Math.cos(b.yaw)*1.35],quat:quatXYZ(0,b.yaw,0)}).unwrap();}}
  for(let i=zones.length-1;i>=0;i--){const z=zones[i],step=Math.min(dt,z.life),p=feet(),d=(p[0]-z.position[0])**2+(p[2]-z.position[2])**2+.25*(p[1]+1-z.position[1])**2;if(d<=5.5**2){const old=b.health;b.health=Math.min(100,b.health+14*step);tally.healedSelf+=b.health-old;}if(!teamless(b.mode))for(const u of b.arena.units){if(!u.alive||u.team!=='ally')continue;const p=b.arena.position(u);if(Math.hypot(p[0]-z.position[0],p[2]-z.position[2])<=5.5){const old=u.hp;u.hp=Math.min(100,u.hp+14*step);tally.healedAllies+=u.hp-old;}}z.life-=dt;if(z.life<=0){remove(z.entity);remove(z.ring);zones.splice(i,1);}}
  if(turret){if(!turret.alive||turret.ammo<=0){dropTurret();return;}turret.cooldown=Math.max(0,turret.cooldown-dt);const p:Vec3=[turret.position[0],turret.position[1]+1.2,turret.position[2]];let nearest=38,target:any=null,to:Vec3=p;for(const u of b.arena.units){if(!u.alive||u.team==='ally')continue;const v=b.arena.position(u),q:Vec3=[v[0],v[1]+1.2,v[2]],d=distance(p,q);if(d<nearest&&!b.map.raycast(p,q.map((v,i)=>v-p[i]) as Vec3,Math.max(0,d-.1))){nearest=d;target=u;to=q;}}
   if(target){const yaw=Math.atan2(to[0]-p[0],to[2]-p[2]),delta=Math.atan2(Math.sin(yaw-turret.yaw),Math.cos(yaw-turret.yaw));turret.yaw+=Math.max(-4*dt,Math.min(4*dt,delta));world.set(turret.head,Transform,{quat:quatXYZ(0,turret.yaw,0)}).unwrap();if(!turret.cooldown){b.arena.damage(target,9,b.arena.player,'gatling');turret.ammo--;turret.cooldown=1;turret.roll+=.9;world.set(turret.barrels,Transform,{quat:quatXYZ(0,0,turret.roll)}).unwrap();beam(p,to);b.audio?.gun('ar',p);tally.turretShots++;if(turret.ammo<=0){dropTurret();notice('炮塔弹药耗尽');}}}}
 }
 function hint(){const key=b.mode==='conquest'?'X':'G',labels:Record<string,string>=b.mode==='conquest'?{assault:'战斗兴奋剂',support:'按住救援',engineer:'按住维修',recon:'Q 强化标记'}:{vanguard:'C4',medic:'按住瞄准 / 松开部署治疗装置',ghost:'隐身',juggernaut:'防暴盾',raider:'电磁脉冲',engineer:'按住部署炮塔 · 12 物料'};
  const main=channel&&channelTarget?channel==='revive'?'救援 '+Math.min(100,Math.floor(progress/3*100))+'% · 松开 X 取消':'维修 '+Math.ceil(channelTarget.hp)+' / '+vehicleDefs[channelTarget.type as keyof typeof vehicleDefs].maxHp+' · 松开 X 取消':pending?'松开 G 部署 · 切换装备取消':turret?'G 收回炮塔 · '+Math.ceil(turret.hp)+' HP / '+turret.ammo+' 发':b.stealthUntil>b.elapsed?'隐身 '+Math.ceil(b.stealthUntil-b.elapsed)+' 秒':b.shieldUntil>b.elapsed?'防暴盾 '+Math.ceil(b.shieldHealth)+' HP / '+Math.ceil(b.shieldUntil-b.elapsed)+' 秒':(b.classId==='recon'?labels.recon:key+' '+(labels[b.classId]||'兵种技能'))+(b.skillCooldown>0?' · 冷却 '+Math.ceil(b.skillCooldown)+' 秒':'');const wounded=b.mode==='conquest'&&b.classId==='support'?b.arena?.downed.filter(d=>d.target.team==='ally'&&!d.target.isPlayer).sort((a,c)=>distance(feet(),b.arena!.position(a.target))-distance(feet(),b.arena!.position(c.target)))[0]:undefined;return main+(wounded?' · 队友待救援 '+Math.round(distance(feet(),b.arena!.position(wounded.target)))+'m':'')+' · V 冲刺'+(dashCooldown>0?' '+Math.ceil(dashCooldown)+'s':'');}
 return {activate,release,update,cancel,reset,spawnLife,breakStealth,incoming,outgoing,damage,mark,dash,hint,marks,get channeling(){return !!channel&&!!channelTarget;},get aiming(){return pending;},get dashing(){return dashLeft>0||dashMoved;},get impulse(){return carry;},get fovKick(){return kick;},get weaponSpeed(){return weaponClassSpeed(b.mode,b.classId);},snapshot:()=>({classId:b.classId,cooldown:b.skillCooldown,stealth:b.stealthUntil>b.elapsed,ambush:b.bonusShot,shield:b.shieldUntil>b.elapsed&&b.shieldHealth>0,shieldHp:b.shieldHealth,turrets:turret?1:0,turret:turret?{hp:turret.hp,ammo:turret.ammo,position:turret.position}:null,pending,placement:pending?place():null,healers:zones.map(z=>({position:z.position,life:z.life})),channel,target:channelTarget?.target?.id||channelTarget?.id||null,progress,dashCooldown,dashLeft,dashTravel,marks:marks.map(m=>({...m})),tally:{...tally}}),dispose(){if(closed)return;reset();closed=true;for(const e of [...owned])remove(e);for(const h of handles)world.sharedRefs.release(h).unwrap();handles.length=0;}};
}
