import {VehicleArmament} from './vehicle-armament.ts';
import {TacticalNavigation} from './tactical-navigation.ts';
import type {World,EntityHandle} from '@forgeax/engine/ecs';
import type {GameHost} from '@forgeax/engine/app';
import {Transform,ChildOf,Name} from '@forgeax/engine/scene';
import {MeshFilter,MeshRenderer,Visibility,VisibilityStateValue} from '@forgeax/engine/render';
import {Collider,ColliderShapeValue,RigidBody,RigidBodyTypeValue} from '@forgeax/engine/physics';
import {createBoxGeometry} from '@forgeax/engine/geometry';
import type {Handle,MeshAsset} from '@forgeax/engine/types';
import {vehicleGuid,smallTerrainMaterialGuid} from '../identity.ts';
import {vehicleDefs,vehicleWeapons} from '../original/vehicle-rules.ts';
import type {BattleState} from './battle.plugin.ts';
import type {Vec3} from './voxel-map.ts';
import type {Team} from './objective-rules.ts';
type Vehicle={id:string;type:keyof typeof vehicleDefs;team:Team;entity:EntityHandle;visual:EntityHandle;home:Vec3;yaw:number;speed:number;vy:number;hp:number;respawn:number;armament:VehicleArmament;ammo:Record<string,number>;pilot:boolean;path:Vec3[];think:number};
export async function createVehicles(world:World,host:GameHost,b:BattleState,cancelled:()=>boolean){
 const physics=b.physics,arena=b.arena!,navigation=new TacticalNavigation(b.map),handles:Handle<'MeshAsset','shared'>[]=[],owned=new Set<EntityHandle>(),vehicles:Vehicle[]=[],shots:{entity:EntityHandle;previous:Vec3;velocity:Vec3;damage:number;radius:number;team:Team;life:number;admitted:boolean}[]=[];let seated:Vehicle|null=null,weaponIndex=0,seatIndex=0,closed=false;const models=new Map<string,Handle<'MeshAsset','shared'>>();
 function dispose(){if(closed)return;closed=true;for(const e of owned)world.despawn(e).unwrap();owned.clear();for(const h of handles)world.sharedRefs.release(h).unwrap();handles.length=0;}
 try {
 for(const team of ['ally','enemy'] as const)for(const type of ['jeep','ifv','tank'] as const){const asset=await host.assets.loadByGuid<MeshAsset>(vehicleGuid('vehicle/'+team+'/'+type));if(!asset.ok)throw asset.error;if(cancelled())throw Error('载具载入已取消');const h=world.allocSharedRef('MeshAsset',asset.value);handles.push(h);models.set(team+'/'+type,h);}
 const shotMesh=world.allocSharedRef('MeshAsset',{...createBoxGeometry(.22,.22,.22).unwrap(),materialSlots:[{slotName:'shell',defaultMaterial:b.material(7)}]});handles.push(shotMesh);
 function vehicleSpawn(origin:Vec3,type:keyof typeof vehicleDefs):Vec3{const d=vehicleDefs[type];for(let r=0;r<24;r+=2)for(let i=0;i<Math.max(1,r*4);i++){const a=i/Math.max(1,r*4)*Math.PI*2,x=Math.floor(origin[0]+Math.cos(a)*r)+.5,z=Math.floor(origin[2]+Math.sin(a)*r)+.5;let high=-Infinity,low=Infinity;for(let xx=Math.floor(x-d.size.x/2-.4);xx<=x+d.size.x/2+.4;xx++)for(let zz=Math.floor(z-d.size.z/2-.4);zz<=z+d.size.z/2+.4;zz++){const y=b.map.walkHeight(xx,zz);high=Math.max(high,y);low=Math.min(low,b.map.waterSurface(xx,zz)>y+.5?-Infinity:y);}if(high-low<=1&&Math.abs(high-origin[1])<5&&!arena.objectives.some(o=>Math.hypot(o.position[0]-x,o.position[2]-z)<6))return [x,high+.06,z];}return arena.nav.safe(origin,24);}
 const base=arena.bases[0]||b.spawn,enemy=arena.bases[1];for(const team of ['ally','enemy'] as const)for(const [i,type] of (['jeep','ifv','tank'] as const).entries()){const origin=team==='ally'?base:enemy||[base[0]+60,base[1],base[2]+80],p=vehicleSpawn([origin[0]+8+i*10,origin[1],origin[2]-12],type),def=vehicleDefs[type],half:Vec3=[def.size.x/2,def.size.y/2,def.size.z/2],entity=physics.character(p,def.nameZh,8,half);owned.add(entity);const visual=world.spawn({component:ChildOf,data:{parent:entity}},{component:Transform,data:{pos:[0,-half[1],0]}},{component:Visibility,data:{state:VisibilityStateValue.visible}},{component:MeshFilter,data:{assetHandle:models.get(team+'/'+type)!}},{component:MeshRenderer,data:{materials:[]}}).unwrap();owned.add(visual);const armament=new VehicleArmament(def.weapons),ammo=armament.ammo;vehicles.push({id:team+'-'+type,type,team,entity,visual,home:p,yaw:team==='ally'?Math.PI:0,speed:0,vy:0,hp:def.maxHp,respawn:0,armament,ammo,pilot:team==='enemy'&&type!=='jeep',path:[],think:0});}
 function usableWeapons(v:Vehicle){const role=vehicleDefs[v.type].seats[seatIndex]?.role||'driver';return vehicleDefs[v.type].weapons.filter(id=>(vehicleWeapons as any)[id].role===role);}
 function exit(){if(!seated)return;const p=physics.position(seated.entity),d=vehicleDefs[seated.type],feet=arena.nav.safe([p[0]+Math.cos(seated.yaw)*(d.size.x/2+2),p[1]-d.size.y/2,p[2]-Math.sin(seated.yaw)*(d.size.x/2+2)],8);if(b.map.overlaps(feet))return;b.physics.teleport(b.playerBody,[feet[0],feet[1]+.9,feet[2]]);world.set(b.playerBody,Collider,{isSensor:false}).unwrap();seated.speed=0;seated=null;seatIndex=0;weaponIndex=0;}
 function nearbyVehicle(){const p=physics.position(b.playerBody),score=(v:Vehicle)=>{const q=physics.position(v.entity),dx=q[0]-p[0],dz=q[2]-p[2],dot=(-Math.sin(b.yaw)*dx-Math.cos(b.yaw)*dz)/(Math.hypot(dx,dz)||1);return distance(q,p)+(1-dot)*8;};return vehicles.filter(v=>v.hp>0&&v.team==='ally'&&distance(physics.position(v.entity),p)<7).sort((a,c)=>score(a)-score(c))[0];}
 function interact(){if(b.dead)return;if(seated){exit();return;}const p=physics.position(b.playerBody);const near=nearbyVehicle();if(near&&distance(physics.position(near.entity),p)<7){seated=near;near.pilot=false;b.yaw=near.yaw;b.pitch=-.25;seatIndex=0;weaponIndex=0;world.set(b.playerBody,Collider,{isSensor:true}).unwrap();b.notice='已登车 · WASD 驾驶 / F 下车 / Q 切换武器 / C 切换座位';b.noticeLeft=4;}}
 function damage(v:Vehicle,amount:number,team:Team){if(v.team===team||v.hp<=0)return;v.hp=Math.max(0,v.hp-amount);if(!v.hp){const p=physics.position(v.entity);if(seated===v){exit();arena.damage(arena.player,10000,{team,id:'vehicle-explosion',name:'载具爆炸'},'explosive');}v.respawn=vehicleDefs[v.type].respawnSec;v.speed=0;world.set(v.visual,Visibility,{state:VisibilityStateValue.hidden}).unwrap();world.set(v.entity,Collider,{isSensor:true}).unwrap();arena.blast(p,6,150,team);}}
 function hit(origin:Vec3,dir:Vec3,range:number,amount:number,team:Team='ally'){let selected:Vehicle|undefined,nearest=range;for(const v of vehicles){if(v.hp<=0||v.team===team||v===seated)continue;const p=physics.position(v.entity),size=vehicleDefs[v.type].size;let lo=0,hi=range;for(let i=0;i<3;i++){const half=[size.x,size.y,size.z][i]/2;if(Math.abs(dir[i])<1e-8){if(Math.abs(origin[i]-p[i])>half){hi=-1;break;}}else{const a=(p[i]-half-origin[i])/dir[i],c=(p[i]+half-origin[i])/dir[i];lo=Math.max(lo,Math.min(a,c));hi=Math.min(hi,Math.max(a,c));}}if(lo<=hi&&lo<nearest){nearest=lo;selected=v;}}if(selected){damage(selected,amount,team);return nearest;}return null;}
 function shoot(v:Vehicle,yaw:number,pitch:number){const ids=v===seated?usableWeapons(v):vehicleDefs[v.type].weapons.filter(id=>(vehicleWeapons as any)[id].role==='driver'),id=ids[(v===seated?weaponIndex:0)%Math.max(1,ids.length)];if(!id||!v.armament.fire(id,b.elapsed))return;const w=(vehicleWeapons as any)[id],p=physics.position(v.entity),dir:Vec3=[-Math.sin(yaw)*Math.cos(pitch),Math.sin(pitch),-Math.cos(yaw)*Math.cos(pitch)],origin:Vec3=[p[0]+dir[0]*5,p[1]+1+dir[1]*5,p[2]+dir[2]*5];b.audio?.play(w.soundId||'vehicle.weapon.'+id,p);
  if(w.mode==='hitscan'){const wall=b.map.raycast(origin,dir,w.range||150),limit=wall?.distance??w.range??150;const vehicleHit=hit(origin,dir,limit,w.damage,v.team);if(vehicleHit==null){if(v.team==='ally')arena.hit(origin,dir,limit,w.damage,id);else{const q=physics.position(b.playerBody);if(distance(origin,q)<limit&&Math.random()<.35)arena.damage(arena.player,w.damage,{team:v.team,id:v.id,name:'敌方战车'},id);}}if(w.damageType==='explosive'&&wall)arena.blast(wall.point.map((n:number,i:number)=>n+wall.normal[i]*.15) as Vec3,3,w.damage,v.team);return;}
  const entity=world.spawn({component:Transform,data:{pos:origin}},{component:RigidBody,data:{type:RigidBodyTypeValue.dynamic,gravityScale:(w.gravity||1)/9.81,ccdEnabled:true}},{component:MeshFilter,data:{assetHandle:shotMesh}},{component:MeshRenderer,data:{materials:[]}}).unwrap();owned.add(entity);shots.push({entity,previous:origin,velocity:dir.map(n=>n*(w.projectileSpeed||60)) as Vec3,damage:w.damage,radius:w.blastRadius||4,team:v.team,life:w.projectileLife||6,admitted:false});
 }
 function update(dt:number){if(closed)return;for(const v of vehicles){const p=physics.position(v.entity);physics.around(p);if(v.hp<=0){v.respawn-=dt;if(v.respawn<=0){v.hp=vehicleDefs[v.type].maxHp;v.armament.reset();physics.teleport(v.entity,[v.home[0],v.home[1]+vehicleDefs[v.type].size.y/2+.04,v.home[2]]);world.set(v.visual,Visibility,{state:VisibilityStateValue.visible}).unwrap();world.set(v.entity,Collider,{isSensor:false}).unwrap();}continue;}if(!arena.match.scoringLive())continue;v.armament.update(dt,b.elapsed,distance(p,[v.home[0],p[1],v.home[2]])<18&&Math.abs(v.speed)<2);
   const def=vehicleDefs[v.type];let throttle=0,steer=0;if(v===seated&&seatIndex===0){throttle=Number(b.keys.has('KeyW'))-Number(b.keys.has('KeyS'));steer=Number(b.keys.has('KeyA'))-Number(b.keys.has('KeyD'));}else if(v.pilot){v.think-=dt;if(v.think<=0){v.think=2;const target=arena.objectives.find(o=>o.owner!==v.team)?.position||b.spawn;v.path=navigation.path([p[0],p[1]-def.size.y/2,p[2]],target,450);}const goal=v.path[0];if(goal){const yaw=Math.atan2(p[0]-goal[0],p[2]-goal[2]),difference=Math.atan2(Math.sin(yaw-v.yaw),Math.cos(yaw-v.yaw));steer=Math.max(-1,Math.min(1,difference*2));throttle=Math.abs(difference)<1.3?.55:.12;if(Math.hypot(p[0]-goal[0],p[2]-goal[2])<2)v.path.shift();}const q=physics.position(b.playerBody);if(distance(p,q)<180){const yaw=Math.atan2(p[0]-q[0],p[2]-q[2]);shoot(v,yaw,Math.atan2(q[1]-p[1]-1,Math.hypot(q[0]-p[0],q[2]-p[2])));}}
   const targetSpeed=throttle*(throttle<0?def.reverseSpeed:def.maxSpeed),acc=throttle?def.acceleration:def.braking;v.speed+=Math.max(-acc*dt,Math.min(acc*dt,targetSpeed-v.speed));v.yaw+=steer*def.turnRate*dt*(v.speed<-.1?-1:1);v.vy=physics.grounded(v.entity)?-1:Math.max(-30,v.vy-18*dt);const dx=-Math.sin(v.yaw)*v.speed*dt,dz=-Math.cos(v.yaw)*v.speed*dt,movement=physics.move(v.entity,[dx,v.vy*dt,dz]);if(Math.hypot(dx,dz)>.03&&Math.hypot(movement[0],movement[2])<.005)v.speed*=.8;world.set(v.visual,Transform,{quat:[0,Math.sin(v.yaw/2),0,Math.cos(v.yaw/2)]}).unwrap();const c=Math.abs(Math.cos(v.yaw)),sn=Math.abs(Math.sin(v.yaw));world.set(v.entity,Collider,{halfExtents:[(def.size.x*c+def.size.z*sn)/2,def.size.y/2,(def.size.z*c+def.size.x*sn)/2]}).unwrap();
   if(distance(p,[v.home[0],p[1],v.home[2]])<18&&Math.abs(v.speed)<2){v.hp=Math.min(def.maxHp,v.hp+def.maxHp*.05*dt);}
   if(v===seated){const q=physics.position(v.entity);physics.teleport(b.playerBody,[q[0],q[1]+def.size.y+1,q[2]]);if(b.firing)shoot(v,b.yaw,b.pitch);if(b.dead)exit();}
  }
  for(let i=shots.length-1;i>=0;i--){const shot=shots[i];if(!shot.admitted){if(!physics.backend.hasBody(shot.entity))continue;const candidate=physics.backend.prepareDerivedShapeCandidate!({entity:shot.entity,sourceKey:'shell/'+shot.entity,revision:1,bodyType:'dynamic',shapes:[{id:'shell',revision:1,cells:[[0,0,0]],voxelSize:[.2,.2,.2],isSensor:true}],motion:{centerOfMass:shot.previous,linearVelocity:shot.velocity,angularVelocity:[0,0,0]}});if(!candidate.ok)throw candidate.error;const admitted=physics.backend.admitDerivedShapeCandidate!(candidate.value);if(!admitted.ok)throw admitted.error;shot.admitted=true;continue;}const p=physics.position(shot.entity),delta=p.map((n,a)=>n-shot.previous[a]) as Vec3,len=Math.hypot(...delta),dir=delta.map(n=>n/(len||1)) as Vec3,wall=len?b.map.raycast(shot.previous,dir,len):null,vehicleHit=len?hit(shot.previous,dir,wall?.distance??len,shot.damage,shot.team):null;shot.life-=dt;if(wall||vehicleHit!==null||shot.life<=0){arena.blast(wall?wall.point.map((n:number,i:number)=>n+wall.normal[i]*.15) as Vec3:p,shot.radius,shot.damage,shot.team);world.despawn(shot.entity).unwrap();owned.delete(shot.entity);shots.splice(i,1);}else shot.previous=p;}
 }
 function camera():Vec3|null{if(!seated)return null;const p=physics.position(seated.entity),pivot:Vec3=[p[0],p[1]+1.5,p[2]],back:Vec3=[Math.sin(b.yaw)*Math.cos(b.pitch),-Math.sin(b.pitch),Math.cos(b.yaw)*Math.cos(b.pitch)],wall=b.map.raycast(pivot,back,10),distance=wall?Math.max(1,wall.distance-.35):10;return pivot.map((n,i)=>n+back[i]*distance) as Vec3;}
 function hint(){if(seated){const ids=usableWeapons(seated),id=ids[weaponIndex%Math.max(1,ids.length)];return vehicleDefs[seated.type].nameZh+' · '+(seatIndex===0?'驾驶位':'炮手/乘员位')+' · 装甲 '+Math.ceil(seated.hp)+' · '+(id?(vehicleWeapons as any)[id].nameZh+' '+seated.armament.status(id):'无车载武器')+' · F 下车 / Q 换武器 / C 换座 / R 装填';}const p=physics.position(b.playerBody),near=nearbyVehicle();return near?'F 驾驶 '+vehicleDefs[near.type].nameZh:'';}
 return {update,hit,interact,camera,hint,dispose,vehicles,get seated(){return seated;},reload:()=>{if(seated){const ids=usableWeapons(seated),id=ids[weaponIndex%Math.max(1,ids.length)];if(id)seated.armament.reload(id);}},cycleWeapon:()=>{weaponIndex++;},cycleSeat:()=>{if(seated){seatIndex=(seatIndex+1)%vehicleDefs[seated.type].seats.length;weaponIndex=0;seated.speed=0;}},repair:()=>{const p=physics.position(b.playerBody),v=vehicles.find(v=>v.hp>0&&v.team==='ally'&&distance(p,physics.position(v.entity))<6);if(v)v.hp=Math.min(vehicleDefs[v.type].maxHp,v.hp+50);}};
 }catch(e){dispose();throw e;}
}
function distance(a:Vec3,b:Vec3){return Math.hypot(a[0]-b[0],a[1]-b[1],a[2]-b[2]);}
