import type {World,EntityHandle} from '@forgeax/engine/ecs';
import {Transform} from '@forgeax/engine/scene';
import {RigidBody,RigidBodyTypeValue} from '@forgeax/engine/physics';
import {MeshFilter,MeshRenderer} from '@forgeax/engine/render';
import {createBoxGeometry} from '@forgeax/engine/geometry';
import type {BattleState} from './battle.plugin.ts';
import type {Vec3} from './voxel-map.ts';
export function createOrdnance(world:World,b:BattleState){const physics=b.physics,owned=new Set<EntityHandle>(),parts:{entity:EntityHandle;velocity:Vec3;life:number;explosive:boolean;admitted:boolean;radius:number;damage:number}[]=[];const mesh=world.allocSharedRef('MeshAsset',{...createBoxGeometry(.22,.22,.22).unwrap(),materialSlots:[{slotName:'body',defaultMaterial:b.material(7)}]});let closed=false;
 function add(p:Vec3,velocity:Vec3,life:number,explosive=false,radius=0,damage=0){if(parts.length>=64)return;const entity=world.spawn({component:Transform,data:{pos:p}},{component:RigidBody,data:{type:RigidBodyTypeValue.dynamic,ccdEnabled:true,linearDamping:.2,angularDamping:.2}},{component:MeshFilter,data:{assetHandle:mesh}},{component:MeshRenderer,data:{materials:[]}}).unwrap();owned.add(entity);parts.push({entity,velocity,life,explosive,admitted:false,radius,damage});}
 function burst(p:Vec3,count=10){for(let i=0;i<count;i++)add([p[0],p[1]+.4,p[2]],[(Math.random()-.5)*9,3+Math.random()*7,(Math.random()-.5)*9],1.3+Math.random());}
 function throwGrenade(c4=false){const p=physics.position(b.playerBody),d:Vec3=[-Math.sin(b.yaw)*Math.cos(b.pitch),Math.sin(b.pitch),-Math.cos(b.yaw)*Math.cos(b.pitch)];add([p[0]+d[0]*1.4,p[1]+.7,p[2]+d[2]*1.4],[d[0]*16,d[1]*16+4,d[2]*16],c4?2.2:3,true,c4?8:6,c4?180:120);}
 function update(dt:number){if(closed)return;let admissions=0;for(let i=parts.length-1;i>=0;i--){const part=parts[i];physics.around(physics.position(part.entity));if(!part.admitted){if(admissions>=4||!physics.backend.hasBody(part.entity))continue;const p=physics.position(part.entity),candidate=physics.backend.prepareDerivedShapeCandidate!({entity:part.entity,sourceKey:'ordnance/'+part.entity,revision:1,bodyType:'dynamic',shapes:[{id:'piece',revision:1,cells:[[0,0,0]],voxelSize:[.2,.2,.2],restitution:part.explosive?.25:.1,friction:.8,collisionGroups:0x00110001}],motion:{centerOfMass:p,linearVelocity:part.velocity,angularVelocity:[4,2,1]}});if(!candidate.ok){if(candidate.error.code==='derived-candidate-budget-exceeded')continue;throw candidate.error;}const admitted=physics.backend.admitDerivedShapeCandidate!(candidate.value);if(!admitted.ok)throw admitted.error;part.admitted=true;admissions++;continue;}part.life-=dt;if(part.life<=0){const p=physics.position(part.entity);world.despawn(part.entity).unwrap();owned.delete(part.entity);parts.splice(i,1);if(part.explosive){b.arena?.blast(p,part.radius,part.damage);burst(p,12);b.speedBoostUntil=b.elapsed+3;}}}}
 return {throwGrenade,burst,update,dispose(){if(closed)return;closed=true;for(const e of owned)world.despawn(e).unwrap();owned.clear();parts.length=0;world.sharedRefs.release(mesh).unwrap();}};
}
