#!/usr/bin/env node
// sync-paths.mjs — CI paths SSOT synchroniser.
// Reads scripts/ci/paths.json (SSOT) and patches every workflow yml that
// contains a `# BEGIN ci-paths-ssot` / `# END ci-paths-ssot` marker pair.
// Idempotent: running twice produces zero diff.
// Usage (sync):  node scripts/ci/sync-paths.mjs
// Usage (check): node scripts/ci/sync-paths.mjs --check
//                exits 1 + structured stderr when any file is out of sync.
import { readdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import process from 'node:process';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const root = resolve(__dirname, '..', '..');
const checkMode = process.argv.includes('--check');

function fail(code, expected, hint) {
  process.stderr.write(
    `[reason] ${code}: ${expected}\n[rerun]  node scripts/ci/sync-paths.mjs\n[hint]   ${hint}\n`,
  );
  process.exit(1);
}

const BEGIN = '# BEGIN ci-paths-ssot';
const END = '# END ci-paths-ssot';

const paths = JSON.parse(readFileSync(`${root}/scripts/ci/paths.json`, 'utf8'));
if (!Array.isArray(paths) || paths.length === 0) {
  fail(
    'ci-paths-empty',
    'scripts/ci/paths.json must be a non-empty array',
    'add at least one path glob',
  );
}

// Build the replacement block (indented 6 spaces to fit under `paths:` inside `push:`/`pull_request:`)
const indent = '      ';
const block = [
  `${indent}${BEGIN} — generated by scripts/ci/sync-paths.mjs — DO NOT EDIT`,
  ...paths.map((p) => `${indent}- '${p}'`),
  `${indent}${END}`,
].join('\n');

const wfDir = `${root}/.github/workflows`;
const ymls = readdirSync(wfDir)
  .filter((f) => f.endsWith('.yml') || f.endsWith('.yaml'))
  .map((f) => `${wfDir}/${f}`);

const driftFiles = [];
let patchedCount = 0;

for (const fp of ymls) {
  const original = readFileSync(fp, 'utf8');
  if (original.indexOf(BEGIN) === -1) continue; // file has no marker — skip

  // A single workflow can carry multiple marker regions (e.g. ci.yml has one
  // under `push:` and one under `pull_request:`). Patch EVERY region, not just
  // the first — otherwise the pull_request paths silently drift out of sync
  // while the push paths look correct.
  let patched = '';
  let cursor = 0;
  while (true) {
    const beginIdx = original.indexOf(BEGIN, cursor);
    if (beginIdx === -1) {
      patched += original.slice(cursor);
      break;
    }
    const endIdx = original.indexOf(END, beginIdx);
    if (endIdx === -1) {
      fail(
        'ci-paths-marker-mismatch',
        `${fp} has BEGIN marker but no END marker`,
        `add '      ${END}' after the paths list`,
      );
    }
    // Slice from the start of the BEGIN line to the end of the END line
    const beginLineStart = original.lastIndexOf('\n', beginIdx) + 1;
    const endLineEnd = original.indexOf('\n', endIdx);
    patched += original.slice(cursor, beginLineStart);
    patched += `${block}\n`;
    cursor = endLineEnd === -1 ? original.length : endLineEnd + 1;
  }

  if (patched === original) continue; // already in sync

  if (checkMode) {
    driftFiles.push(fp.replace(`${root}/`, ''));
  } else {
    writeFileSync(fp, patched, 'utf8');
    patchedCount++;
    process.stdout.write(`[patched] ${fp.replace(`${root}/`, '')}\n`);
  }
}

if (checkMode) {
  if (driftFiles.length > 0) {
    fail(
      'ci-paths-ssot-drift',
      'all workflow yml files with ci-paths-ssot markers are in sync with scripts/ci/paths.json',
      `out-of-sync files:\n         ${driftFiles.join('\n         ')}\n         re-run: node scripts/ci/sync-paths.mjs`,
    );
  }
  process.stdout.write('[ok] ci-paths-ssot: all marker regions in sync\n');
} else {
  if (patchedCount === 0) {
    process.stdout.write('[ok] ci-paths-ssot: all marker regions already in sync\n');
  } else {
    process.stdout.write(`[ok] ci-paths-ssot: patched ${patchedCount} file(s)\n`);
  }
}
