import type {BattleState} from '../gameplay/battle.plugin.ts';
import largeColors from '../original/terrain-colors.ts';
import smallColors from '../original/small-terrain-colors.ts';
/** UI-only projection of the authoritative battle map and native actor positions. */
export function createTacticalMap(target:HTMLElement){const svg=document.createElementNS('http://www.w3.org/2000/svg','svg');svg.setAttribute('width','100%');svg.setAttribute('height','100%');svg.setAttribute('aria-label','战术小地图');target.replaceChildren(svg);let last=-1,key='',terrain='';
 return {update(b:BattleState){if(b.elapsed-last<.2&&last<=b.elapsed)return;last=b.elapsed;const p=b.physics.position(b.playerBody),radius=b.mode==='conquest'?140:75,step=8,cx=Math.floor(p[0]/step)*step,cz=Math.floor(p[2]/step)*step,next=b.mode+'/'+cx+'/'+cz,colors=(b.mode==='conquest'?largeColors:smallColors) as Record<string,number>;
  if(key!==next){key=next;terrain='';for(let x=cx-radius-8;x<cx+radius+8;x+=step)for(let z=cz-radius-8;z<cz+radius+8;z+=step){const xx=Math.max(0,Math.min(b.map.width-1,Math.floor(x))),zz=Math.max(0,Math.min(b.map.width-1,Math.floor(z))),y=b.map.ground[zz*b.map.width+xx],id=b.map.get(xx,y,zz),color=colors[id]??0x343b38;terrain+='<rect x="'+x+'" y="'+z+'" width="8.1" height="8.1" fill="#'+color.toString(16).padStart(6,'0')+'"/>';}}
  const a=b.arena,objectives=[...(a?.objectives||[]),...(a?.coreSpawns.points||[]).filter(p=>!p.fixed)].map(o=>'<circle cx="'+o.position[0]+'" cy="'+o.position[2]+'" r="6" fill="'+(o.owner==='ally'?'#64d1ff':o.owner==='enemy'?'#fc5b50':'#ffe1a0')+'"/><text x="'+o.position[0]+'" y="'+(o.position[2]+2)+'" font-size="5" text-anchor="middle" fill="#10191d">'+o.id+'</text>').join('');
  const units=(a?.units||[]).filter(u=>u.alive).map(u=>{const q=a!.position(u);return '<circle cx="'+q[0]+'" cy="'+q[2]+'" r="2" fill="'+(u.team==='ally'?'#64d1ff':'#e66054')+'"/>';}).join('');const cars=(b.vehicles?.vehicles||[]).filter(v=>v.hp>0).map(v=>{const q=b.physics.position(v.entity);return '<rect x="'+(q[0]-3)+'" y="'+(q[2]-3)+'" width="6" height="6" fill="'+(v.team==='ally'?'#a6e9ff':'#f29a62')+'"/>';}).join('');
  svg.setAttribute('viewBox',`${p[0]-radius} ${p[2]-radius} ${radius*2} ${radius*2}`);svg.innerHTML=terrain+objectives+units+cars+'<path d="M 0 -5 L -3 4 L 3 4 Z" transform="translate('+p[0]+' '+p[2]+') rotate('+(-b.yaw*180/Math.PI)+')" fill="white" stroke="#152b34" stroke-width=".7"/>';
 },dispose(){svg.remove();}};
}
