# generated by forgeax-harness
# from skills/forgeax-english/scripts/check_english_only.py
# DO NOT EDIT - run install_harness.py to refresh
#!/usr/bin/env python3
"""check_english_only.py - verify files contain no non-Latin natural-language characters.

Rule:
  Block any character where:
    - codepoint >= 128 (non-ASCII), AND
    - Unicode category starts with 'L' (Letter) or 'M' (Mark)
  EXCEPT Greek and Coptic (U+0370..U+03FF) which is explicitly allowed
  (math / scientific constants).

Allowed: ASCII, Greek/Coptic, emoji (So category), superscripts (No),
         math symbols (Sm), dashes (Pd), smart quotes (Pi/Pf).
Blocked: CJK ideographs, Hangul, Hiragana, Katakana, Cyrillic, Hebrew,
         Arabic, Thai, accented Latin letters.

Exit codes:
  0  all files clean
  1  at least one violation found
  2  CLI / IO error

Usage:
  python check_english_only.py <path>...                       # all files in given paths
  python check_english_only.py --code <path>...                # built-in source-code extensions
  python check_english_only.py --extensions .ts --extensions .py <path>...  # explicit (repeatable)
  python check_english_only.py --json <path>...                # machine-readable output
"""
import argparse
import json
import sys
import unicodedata
from pathlib import Path

DEFAULT_CODE_EXTENSIONS = frozenset({
    ".ts", ".tsx", ".js", ".jsx", ".mjs", ".cjs",
    ".py",
    ".rs",
    ".go",
    ".java", ".kt", ".scala",
    ".cpp", ".cxx", ".cc", ".c", ".h", ".hpp",
    ".cs",
    ".swift",
    ".m", ".mm",
    ".rb",
    ".php",
    # CI / build / config surface (English-only enforced for AI users; see
    # forgeax-engine AGENTS.md "English-only source + entry docs").
    # Covers GitHub Actions workflows, dependabot, devcontainer, etc.
    ".yml", ".yaml",
    # Build / test / bundler config files often live alongside source and
    # ship in published packages -- keep them ASCII so non-CJK contributors
    # can read them without a translator.
    ".toml", ".json5",
})

ALLOWED_LETTER_RANGES = (
    (0x0370, 0x03FF),  # Greek and Coptic
)


def is_blocked(c: str) -> bool:
    cp = ord(c)
    if cp < 128:
        return False
    for lo, hi in ALLOWED_LETTER_RANGES:
        if lo <= cp <= hi:
            return False
    return unicodedata.category(c)[0] in ("L", "M")


def scan_text(text: str):
    """Yield (line, col, char, codepoint, name) for each blocked char.

    line/col are 1-based, counted in Unicode code units (Python str chars).
    """
    line = 1
    col = 1
    for c in text:
        if c == "\n":
            line += 1
            col = 1
            continue
        if is_blocked(c):
            try:
                name = unicodedata.name(c)
            except ValueError:
                name = "<unnamed>"
            yield line, col, c, ord(c), name
        col += 1


def collect_files(paths, extensions):
    """Walk paths; yield Path for each regular file matching extensions (None = all)."""
    for p in paths:
        path = Path(p)
        if not path.exists():
            print(f"warning: {path} not found, skipping", file=sys.stderr)
            continue
        if path.is_file():
            if extensions is None or path.suffix.lower() in extensions:
                yield path
            continue
        for sub in sorted(path.rglob("*")):
            if sub.is_file() and (extensions is None or sub.suffix.lower() in extensions):
                yield sub


def main(argv=None):
    ap = argparse.ArgumentParser(
        description="Check files contain English-only text (ASCII + Greek + symbols).",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog=__doc__,
    )
    ap.add_argument("paths", nargs="+", help="files or directories to scan")
    ext_group = ap.add_mutually_exclusive_group()
    ext_group.add_argument(
        "--code", action="store_true",
        help=f"restrict to built-in source-code extensions ({len(DEFAULT_CODE_EXTENSIONS)} types)",
    )
    ext_group.add_argument(
        "--extensions", action="append", metavar=".EXT", default=None,
        help="explicit extension (repeatable: --extensions .ts --extensions .py)",
    )
    ap.add_argument("--json", action="store_true", help="emit JSON output")
    args = ap.parse_args(argv)

    if args.code:
        extensions = DEFAULT_CODE_EXTENSIONS
    elif args.extensions:
        extensions = frozenset(
            (e if e.startswith(".") else "." + e).lower() for e in args.extensions
        )
    else:
        extensions = None

    violations = []
    for f in collect_files(args.paths, extensions):
        try:
            text = f.read_text(encoding="utf-8")
        except (UnicodeDecodeError, OSError) as e:
            print(f"warning: {f} not readable as utf-8: {e}", file=sys.stderr)
            continue
        for line, col, c, cp, name in scan_text(text):
            violations.append({
                "path": str(f),
                "line": line,
                "col": col,
                "char": c,
                "codepoint": f"U+{cp:04X}",
                "name": name,
            })

    if args.json:
        print(json.dumps({"violations": violations}, ensure_ascii=False, indent=2))
    else:
        for v in violations:
            print(f"{v['path']}:{v['line']}:{v['col']}: {v['codepoint']} {v['name']} ({v['char']!r})")
        files = len({v["path"] for v in violations})
        if violations:
            print(f"\n{len(violations)} violation(s) in {files} file(s)", file=sys.stderr)
        else:
            print("All clean.", file=sys.stderr)

    return 1 if violations else 0


if __name__ == "__main__":
    sys.exit(main())
