// sync-paths.test.mjs — regression guard for scripts/ci/sync-paths.mjs.
// Runs the synchroniser as a child process against a throwaway workspace whose
// workflow yml carries TWO ci-paths-ssot marker regions (mirrors ci.yml's
// push: + pull_request: blocks) and asserts BOTH regions get patched. The
// original single-indexOf implementation patched only the first region, letting
// the pull_request paths silently drift — the very hole that let a
// submodule-pin-only PR skip CI.
//
// Usage: node --test scripts/ci/__tests__/sync-paths.test.mjs

import assert from 'node:assert/strict';
import { execFileSync } from 'node:child_process';
import { mkdirSync, mkdtempSync, readFileSync, realpathSync, rmSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import test from 'node:test';
import { fileURLToPath } from 'node:url';

const __dirname = fileURLToPath(new URL('.', import.meta.url));
const scriptPath = realpathSync(join(__dirname, '..', 'sync-paths.mjs'));

const BEGIN = '# BEGIN ci-paths-ssot — generated by scripts/ci/sync-paths.mjs — DO NOT EDIT';
const END = '# END ci-paths-ssot';

// Build a workspace root: scripts/ci/paths.json + .github/workflows/<name>.yml.
function makeWorkspace(paths, ymlBody) {
  const root = mkdtempSync(join(tmpdir(), 'sync-paths-'));
  mkdirSync(join(root, 'scripts', 'ci'), { recursive: true });
  mkdirSync(join(root, '.github', 'workflows'), { recursive: true });
  writeFileSync(join(root, 'scripts', 'ci', 'paths.json'), JSON.stringify(paths, null, 2));
  writeFileSync(join(root, '.github', 'workflows', 'wf.yml'), ymlBody);
  return root;
}

// A region block with a deliberately stale path list, indented 6 spaces.
function staleRegion() {
  return [`      ${BEGIN}`, "      - 'old/**'", `      ${END}`].join('\n');
}

// Run the real script but point it at our fixture root by copying it in — the
// script resolves paths.json + workflows relative to its own location, so we
// copy it into the fixture's scripts/ci/ and run that copy.
function runSync(root, args = []) {
  const copied = join(root, 'scripts', 'ci', 'sync-paths.mjs');
  writeFileSync(copied, readFileSync(scriptPath, 'utf8'));
  try {
    const stdout = execFileSync(process.execPath, [copied, ...args], {
      encoding: 'utf-8',
      stdio: ['pipe', 'pipe', 'pipe'],
    });
    return { exitCode: 0, stdout: stdout.trim(), stderr: '' };
  } catch (err) {
    return {
      exitCode: err.status ?? 1,
      stdout: err.stdout?.toString()?.trim() ?? '',
      stderr: err.stderr?.toString()?.trim() ?? '',
    };
  }
}

test('patches EVERY marker region, not just the first', () => {
  const yml = [
    'on:',
    '  push:',
    '    paths:',
    staleRegion(),
    '  pull_request:',
    '    paths:',
    staleRegion(),
    'jobs: {}',
    '',
  ].join('\n');
  const root = makeWorkspace(['packages/**', 'forgeax-engine-assets'], yml);
  try {
    const res = runSync(root);
    assert.equal(res.exitCode, 0, res.stderr);
    const out = readFileSync(join(root, '.github', 'workflows', 'wf.yml'), 'utf8');
    // Both regions must now contain the new path — count occurrences.
    const hits = out.split("- 'forgeax-engine-assets'").length - 1;
    assert.equal(hits, 2, `expected both regions patched, got ${hits}`);
    assert.equal(out.includes("- 'old/**'"), false, 'stale path should be gone from all regions');
  } finally {
    rmSync(root, { recursive: true, force: true });
  }
});

test('--check fails when a NON-FIRST region is out of sync', () => {
  // First region already correct, second region stale — the old first-only
  // implementation would report in-sync and miss the drift.
  const goodRegion = [`      ${BEGIN}`, "      - 'packages/**'", `      ${END}`].join('\n');
  const yml = [
    'on:',
    '  push:',
    '    paths:',
    goodRegion,
    '  pull_request:',
    '    paths:',
    staleRegion(),
    'jobs: {}',
    '',
  ].join('\n');
  const root = makeWorkspace(['packages/**'], yml);
  try {
    const res = runSync(root, ['--check']);
    assert.equal(res.exitCode, 1, 'expected drift to be detected in the second region');
  } finally {
    rmSync(root, { recursive: true, force: true });
  }
});

test('is idempotent — second run is a no-op', () => {
  const yml = [
    'on:',
    '  push:',
    '    paths:',
    staleRegion(),
    '  pull_request:',
    '    paths:',
    staleRegion(),
    'jobs: {}',
    '',
  ].join('\n');
  const root = makeWorkspace(['packages/**'], yml);
  try {
    runSync(root);
    const first = readFileSync(join(root, '.github', 'workflows', 'wf.yml'), 'utf8');
    runSync(root);
    const second = readFileSync(join(root, '.github', 'workflows', 'wf.yml'), 'utf8');
    assert.equal(first, second, 'second run must produce identical output');
  } finally {
    rmSync(root, { recursive: true, force: true });
  }
});
