packages:
  - "packages/*"
  - "apps/*"
  - "apps/showcase/*"
  - "apps/hello/*"
  - "apps/perf/*"
  - "apps/bevy/*"
  - "apps/shadertoy/*"
  - "apps/parity/*"
  - "apps/learn-render/*/*"
  - "apps/learn-render/*/*/*"
  - "templates/empty"
  - "templates/game-3d"

allowBuilds:
  esbuild: true
  simple-git-hooks: true
  webgpu: true

patchedDependencies:
  '@deepseek-ai/cordis-plugin-loader@1.0.2': patches/@deepseek-ai__cordis-plugin-loader@1.0.2.patch

supportedArchitectures:
  os:
    - darwin
    - linux
    - win32
  cpu:
    - x64
    - arm64
  libc:
    - glibc
    - musl
