export {
  assetAddCommand,
  assetInspectCommand,
  assetListCommand,
  assetVerifyCommand,
  browserCaptureCommand,
  buildCommand,
  createCliRhiDebugOperationContext,
  devCommand,
  doctorCommand,
  engineDoctorCommand,
  engineStatusCommand,
  engineUnlinkCommand,
  engineUseLocalCommand,
  initCommand,
  newCommand,
  packageCommand,
  pluginConfigureCommand,
  pluginDisableCommand,
  pluginEnableCommand,
  pluginInspectCommand,
  pluginInstallCommand,
  pluginUninstallCommand,
  previewCommand,
  projectLintCommand,
  runRhiDebugCommand,
  sdkInstallCommand,
  shaderCheckCommand,
  skillInstallCommand,
  skillVerifyCommand,
  softwareCaptureCommand,
  testCommand,
} from './commands.js';
export { verifyDist, writeDistManifest } from './dist.js';
export type {
  EngineBinding,
  EngineBindingCommandOptions,
  EngineBindingMode,
  EnginePackageStatus,
  EngineStatusReport,
  EngineWorkspaceStatus,
} from './engine-binding.js';
export {
  ENGINE_BINDING_SCHEMA_VERSION,
  engineBindingFilePath,
  inspectEngineWorkspace,
  readEngineBinding,
} from './engine-binding.js';
export {
  createPluginTransaction,
  type PluginEntryTransactionError,
  type PluginTransaction,
  type PluginTransactionError,
  type PluginTransactionErrorCode,
  type PluginTransactionInput,
} from './plugin-authoring.js';
export {
  type BootstrapRoot,
  createInitPlan,
  type ProjectBootstrapPlan,
  type ResourceBootstrapPlan,
  type ResourceBootstrapTrace,
  readProjectFacts,
} from './project/index.js';
export type {
  ProjectLintDiagnostic,
  ProjectLintError,
  ProjectLintReport,
  ProjectLintResult,
  ProjectLintRuleId,
  ProjectOwnershipGraph,
  ProjectOwnershipNode,
} from './project/lint.js';
export type {
  ArtifactRef,
  CapturedRhiTape,
  RhiCaptureFrameValue,
  RhiDebugOperationContext,
  RhiDebugOperationDescriptor,
  RhiDebugOperationInput,
  RhiDebugOperationName,
  RhiDebugOperationOutput,
  RhiInspectInput,
  RhiInspectOutput,
  RhiSummaryInput,
  RhiSummaryOutput,
} from './rhi-debug/operations.js';
export {
  createRhiDebugOperationContext,
  discoverRhiDebugOperations,
  RHI_DEBUG_OPERATION_MANIFEST,
  recoverRhiDebugError,
  renderRhiDebugHelp,
  runRhiDebugOperation,
} from './rhi-debug/operations.js';
export type {
  SingleHtmlBundle,
  SingleHtmlBundleArtifact,
  SingleHtmlPackageOptions,
  SingleHtmlPackageResult,
} from './single-html.js';
export {
  bundleSingleHtmlEntry,
  packageFormatError,
  packageOutputError,
  writeSingleHtml,
} from './single-html.js';
export type {
  BrowserCapture,
  BrowserCaptureCheckpointOptions,
  BrowserCaptureOpenOptions,
  BrowserCaptureRecord,
  BrowserCaptureRequestReport,
  BrowserCaptureRequestWitness,
  BrowserCaptureRunReport,
  BrowserCaptureRuntimeWitness,
  BrowserCaptureTarget,
  BrowserLaunchProfile,
  CapturePixelWitness,
  SoftwareBrowser,
  SoftwareBrowserOpenOptions,
  SoftwareBrowserSession,
  SoftwareCaptureCheckpointOptions,
  SoftwareCaptureRecord,
  SoftwareCaptureRequestReport,
  SoftwareCaptureRequestWitness,
  SoftwareCaptureRunReport,
  SoftwareCaptureRuntimeWitness,
} from './software-capture.js';
export { createBrowserCapture, createSoftwareBrowser } from './software-capture.js';
export * from './tools/index.js';
export type {
  AssetAddOptions,
  AssetInspectOptions,
  BrowserCaptureOptions,
  BuildOptions,
  CaptureBackend,
  CommandError,
  CommandResult,
  InitOptions,
  NewOptions,
  PackageFormat,
  PackageOptions,
  PluginConfigureOptions,
  PluginInspectOptions,
  PluginInstallOptions,
  PluginToggleOptions,
  PluginUninstallOptions,
  ProjectCommandOptions,
  ProjectFacts,
  ShaderCheckOptions,
  SoftwareCaptureOptions,
} from './types.js';
export { resolveProjectPort } from './types.js';
export { runUnifiedCli, type UnifiedCliResult } from './unified-cli.js';
